### Filter gold standard list from manual literature review
### Julian Moran
### 2026-04-01

In [2]:
import logging
import os
import sys

from dotenv import load_dotenv
from pathlib import Path

import polars as pl

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]
sys.path.append(str(Path(INSTALL_PATH).resolve()))

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

### Goals

1. Filter for `Include = TRUE`

<br>


2.  Make pie plot of bacterial systems

In [4]:
# ────────────────────────────────────────────────────────────
#      Args
# ────────────────────────────────────────────────────────────

DATA_FILE = f"{INSTALL_PATH}/lit_review_manual/___bacterial_immuneSystem_goldStandard_manual.tsv"

In [6]:
# ────────────────────────────────────────────────────────────
#      In
# ────────────────────────────────────────────────────────────

df_goldStandard = pl.read_csv(
    DATA_FILE,
    separator="\t",
    has_header=True,
    encoding="latin1"
)

df_goldStandard

shape: (52, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PMID     ┆ Paper_tit ┆ Bacterial ┆ Bacterial ┆ … ┆ Cloned_in ┆ Did_struc ┆ Screening ┆ Note      │
│ ---      ┆ le        ┆ _gene_nam ┆ _species  ┆   ┆ to_organi ┆ tural_val ┆ _source   ┆ ---       │
│ i64      ┆ ---       ┆ e         ┆ ---       ┆   ┆ sm        ┆ idation   ┆ ---       ┆ str       │
│          ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆           │
│          ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 12110595 ┆ tadA, an  ┆ tadA      ┆ Escherich ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ 34% seque │
│          ┆ essential ┆           ┆ ia coli   ┆   ┆ assesed   ┆ assesed   ┆           ┆ nce-simil │
│          ┆ tRNA-spec ┆           ┆           ┆   ┆           ┆           ┆           ┆ ar to     │
│          ┆ if…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ yeast …   │
│ 30787435 ┆ Bacterial ┆ dncV      ┆ Vibrio    ┆ … ┆ HEK293T   ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ cholerae  ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ GMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Escherich ┆ … ┆ NA        ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ UMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Rhodother ┆ … ┆ NA        ┆ TRUE      ┆ C Trost   ┆ NA        │
│          ┆ cGAS-like ┆           ┆ mus       ┆   ┆           ┆           ┆           ┆           │
│          ┆ enzymes   ┆           ┆ marinus   ┆   ┆           ┆           ┆           ┆           │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31695182 ┆ The pan-i ┆ Cas1      ┆ Escherich ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ Not       │
│          ┆ mmune     ┆           ┆ ia coli   ┆   ┆ assesed   ┆ assesed   ┆           ┆ assessed  │
│          ┆ system of ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ bacte…    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 32937646 ┆ Prokaryot ┆ vip47     ┆ Flammeovi ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rga       ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ pacifica  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip50     ┆ Thermopla ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ smatales  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ archaeon  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip56     ┆ Fibrobact ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ er sp.    ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip58     ┆ Pseudoalt ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ eromonas  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ulvae     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip60     ┆ Lacinutri ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ x marinif ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ lava      ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# ────────────────────────────────────────────────────────────
#      Filter
# ────────────────────────────────────────────────────────────

df_filt = df_goldStandard.filter(
    pl.col("Include") == True
)

df_filt.write_csv(
    f"{OUT_DIR}/"
)
df_filt

shape: (29, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PMID     ┆ Paper_tit ┆ Bacterial ┆ Bacterial ┆ … ┆ Cloned_in ┆ Did_struc ┆ Screening ┆ Note      │
│ ---      ┆ le        ┆ _gene_nam ┆ _species  ┆   ┆ to_organi ┆ tural_val ┆ _source   ┆ ---       │
│ i64      ┆ ---       ┆ e         ┆ ---       ┆   ┆ sm        ┆ idation   ┆ ---       ┆ str       │
│          ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆           │
│          ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Escherich ┆ … ┆ NA        ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ UMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Rhodother ┆ … ┆ NA        ┆ TRUE      ┆ C Trost   ┆ NA        │
│          ┆ cGAS-like ┆           ┆ mus       ┆   ┆           ┆           ┆           ┆           │
│          ┆ enzymes   ┆           ┆ marinus   ┆   ┆           ┆           ┆           ┆           │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ NA        ┆ NA        ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ NA        ┆ NA        ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 32937646 ┆ Prokaryot ┆ vip47     ┆ Flammeovi ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rga       ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ pacifica  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip50     ┆ Thermopla ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ smatales  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ archaeon  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip56     ┆ Fibrobact ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ er sp.    ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip58     ┆ Pseudoalt ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ eromonas  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ulvae     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip60     ┆ Lacinutri ┆ … ┆ Escherich ┆ NA        ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ x marinif ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ lava      ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘