### Filter gold standard list from manual literature review
### Julian Moran
### 2026-04-01

In [1]:
import logging
import os
import sys

from dotenv import load_dotenv
from pathlib import Path

import polars as pl

# Env
pl.Config.set_tbl_rows(10)
load_dotenv("../.env")
INSTALL_PATH = os.environ["INSTALL_PATH"]
sys.path.append(str(Path(INSTALL_PATH).resolve()))

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

### Goals

1. Filter for `Include = TRUE`

<br>

2.  Make pie plot of bacterial systems

In [8]:
# ────────────────────────────────────────────────────────────
#      Args
# ────────────────────────────────────────────────────────────

DATA_FILE = f"{INSTALL_PATH}/lit_review_manual/___bacterial_immuneSystem_goldStandard_manual.tsv"
OUT_DIR = f"{INSTALL_PATH}/lit_review_manual/"

In [13]:
# ────────────────────────────────────────────────────────────
#      In
# ────────────────────────────────────────────────────────────

df_goldStandard = pl.read_csv(
    DATA_FILE,
    separator="\t",
    has_header=True,
    encoding="latin1",
    null_values=["NA", "Not assessed"]
)

df_goldStandard

shape: (52, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PMID     ┆ Paper_tit ┆ Bacterial ┆ Bacterial ┆ … ┆ Cloned_in ┆ Did_struc ┆ Screening ┆ Note      │
│ ---      ┆ le        ┆ _gene_nam ┆ _species  ┆   ┆ to_organi ┆ tural_val ┆ _source   ┆ ---       │
│ i64      ┆ ---       ┆ e         ┆ ---       ┆   ┆ sm        ┆ idation   ┆ ---       ┆ str       │
│          ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆           │
│          ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 12110595 ┆ tadA, an  ┆ tadA      ┆ Escherich ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ 34% seque │
│          ┆ essential ┆           ┆ ia coli   ┆   ┆ assesed   ┆ assesed   ┆           ┆ nce-simil │
│          ┆ tRNA-spec ┆           ┆           ┆   ┆           ┆           ┆           ┆ ar to     │
│          ┆ if…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ yeast …   │
│ 30787435 ┆ Bacterial ┆ dncV      ┆ Vibrio    ┆ … ┆ HEK293T   ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ cholerae  ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ GMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Escherich ┆ … ┆ null      ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ UMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Rhodother ┆ … ┆ null      ┆ TRUE      ┆ C Trost   ┆ null      │
│          ┆ cGAS-like ┆           ┆ mus       ┆   ┆           ┆           ┆           ┆           │
│          ┆ enzymes   ┆           ┆ marinus   ┆   ┆           ┆           ┆           ┆           │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31695182 ┆ The pan-i ┆ Cas1      ┆ Escherich ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ null      │
│          ┆ mmune     ┆           ┆ ia coli   ┆   ┆ assesed   ┆ assesed   ┆           ┆           │
│          ┆ system of ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ bacte…    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31695182 ┆ The pan-i ┆ Cas2      ┆ Escherich ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ null      │
│          ┆ mmune     ┆           ┆ ia coli   ┆   ┆ assesed   ┆ assesed   ┆           ┆           │
│          ┆ system of ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ bacte…    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31695182 ┆ The pan-i ┆ Cas9      ┆ Streptoco ┆ … ┆ Not       ┆ Not       ┆ C Trost   ┆ Cas9 is   │
│          ┆ mmune     ┆           ┆ ccus      ┆   ┆ assesed   ┆ assesed   ┆           ┆ not endog │
│          ┆ system of ┆           ┆ pyogenes  ┆   ┆           ┆           ┆           ┆ enously   │
│          ┆ bacte…    ┆           ┆ serotyp…  ┆   ┆           ┆           ┆           ┆ expre…    │
│ 31695182 ┆ The pan-i ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ C Trost   ┆ null      │
│          ┆ mmune     ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ system of ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ bacte…    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31932165 ┆ HORMA     ┆ cdnC      ┆ Escherich ┆ … ┆ Escherich ┆ TRUE      ┆ C Trost   ┆ null      │
│          ┆ Domain    ┆           ┆ ia coli   ┆   ┆ ia coli   ┆           ┆           ┆           │
│          ┆ Proteins  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ and a Tr… ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31932165 ┆ HORMA     ┆ cdnD      ┆ Pseudomon ┆ … ┆ Escherich ┆ TRUE      ┆ C Trost   ┆ null      │
│          ┆ Domain    ┆           ┆ as aerugi ┆   ┆ ia coli   ┆           ┆           ┆           │
│          ┆ Proteins  ┆           ┆ nosa      ┆   ┆           ┆           ┆           ┆           │
│          ┆ and a Tr… ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31932165 ┆ HORMA     ┆ cap7      ┆ Pseudomon ┆ … ┆ Escherich ┆ TRUE      ┆ C Trost   ┆ AKA       │
│          ┆ Domain    ┆           ┆ as aerugi ┆   ┆ ia coli   ┆           ┆           ┆ HORMA2    │
│          ┆ Proteins  ┆           ┆ nosa      ┆   ┆           ┆           ┆           ┆           │
│          ┆ and a Tr… ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31932165 ┆ HORMA     ┆ null      ┆ Pseudomon ┆ … ┆ Escherich ┆ TRUE      ┆ C Trost   ┆ AKA       │
│          ┆ Domain    ┆           ┆ as aerugi ┆   ┆ ia coli   ┆           ┆           ┆ HORMA1    │
│          ┆ Proteins  ┆           ┆ nosa      ┆   ┆           ┆           ┆           ┆           │
│          ┆ and a Tr… ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 31932165 ┆ HORMA     ┆ null      ┆ Rhizobial ┆ … ┆ Escherich ┆ TRUE      ┆ C Trost   ┆ AKA       │
│          ┆ Domain    ┆           ┆ es        ┆   ┆ ia coli   ┆           ┆           ┆ Trip13,   │
│          ┆ Proteins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Pch2;     │
│          ┆ and a Tr… ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ spec…     │
│ 32559405 ┆ Abortive  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ C Trost   ┆ null      │
│          ┆ Infection ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ :         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ Bacterial ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ …         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32839535 ┆ Diversity ┆ null      ┆ null      ┆ … ┆ null      ┆ FALSE     ┆ M         ┆ In-silico │
│          ┆ and class ┆           ┆           ┆   ┆           ┆           ┆ Umanowicz ┆ analysis  │
│          ┆ ification ┆           ┆           ┆   ┆           ┆           ┆           ┆ only;     │
│          ┆ o…        ┆           ┆           ┆   ┆           ┆           ┆           ┆ leads…    │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 40705877 ┆ A human   ┆ AbiH      ┆ Klebsiell ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AFDB ID   │
│          ┆ homolog   ┆           ┆ a pneumon ┆   ┆           ┆           ┆           ┆ given by  │
│          ┆ of SIR2   ┆           ┆ iae       ┆   ┆           ┆           ┆           ┆ authors   │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ as "A…    │
│ 40705877 ┆ A human   ┆ PD-T7-2 A ┆ Belliella ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ Checked   │
│          ┆ homolog   ┆           ┆ baltica   ┆   ┆           ┆           ┆           ┆ supplemen │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ taries    │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ for fu…   │
│ 32937646 ┆ Prokaryot ┆ null      ┆ Lutibacte ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ r oricola ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ null      ┆ Chryseoba ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ cterium   ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ gambrini  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ null      ┆ Methanofo ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ llis limi ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ natans    ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip6      ┆ Selenomon ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ as rumina ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ntium     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip8      ┆ Psychroba ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ cter luti ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ phocae    ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip15     ┆ Coralioma ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rgarita   ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ akajimens ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆ is        ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ null      ┆ Methanopl ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ anus      ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ limicola  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip21     ┆ Lewinella ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ persica   ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip47     ┆ Flammeovi ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rga       ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ pacifica  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip50     ┆ Thermopla ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ smatales  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ archaeon  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip56     ┆ Fibrobact ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ er sp.    ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip58     ┆ Pseudoalt ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ eromonas  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ulvae     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip60     ┆ Lacinutri ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ x marinif ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ lava      ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
# ────────────────────────────────────────────────────────────
#      Filter
# ────────────────────────────────────────────────────────────

df_filt = df_goldStandard.filter(
    (pl.col("Include") == True) &
    (~pl.col("Bacterial_gene_name").is_null())
)

df_filt.write_csv(
    f"{OUT_DIR}/bacterial_immSys_goldStnd_man_inclusionSet.tsv",
    separator="\t",
    include_header=True
)

unique_pairs = df_filt.select(
    ["Bacterial_UniProt_accession", "Human_UniProt_accession"]
).unique()

logger.info(f"Unique bacteria-human protein pairs: {len(unique_pairs)}")


df_filt

INFO:__main__:Unique bacteria-human protein pairs: 18

shape: (25, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ PMID     ┆ Paper_tit ┆ Bacterial ┆ Bacterial ┆ … ┆ Cloned_in ┆ Did_struc ┆ Screening ┆ Note      │
│ ---      ┆ le        ┆ _gene_nam ┆ _species  ┆   ┆ to_organi ┆ tural_val ┆ _source   ┆ ---       │
│ i64      ┆ ---       ┆ e         ┆ ---       ┆   ┆ sm        ┆ idation   ┆ ---       ┆ str       │
│          ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆           │
│          ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Escherich ┆ … ┆ null      ┆ TRUE      ┆ C Trost   ┆ protein   │
│          ┆ cGAS-like ┆           ┆ ia coli   ┆   ┆           ┆           ┆           ┆ full      │
│          ┆ enzymes   ┆           ┆           ┆   ┆           ┆           ┆           ┆ name:     │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cyclic    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ UMP-…     │
│ 30787435 ┆ Bacterial ┆ cdnE      ┆ Rhodother ┆ … ┆ null      ┆ TRUE      ┆ C Trost   ┆ null      │
│          ┆ cGAS-like ┆           ┆ mus       ┆   ┆           ┆           ┆           ┆           │
│          ┆ enzymes   ┆           ┆ marinus   ┆   ┆           ┆           ┆           ┆           │
│          ┆ sy…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 40705877 ┆ A human   ┆ ThsA      ┆ Bacillus  ┆ … ┆ null      ┆ null      ┆ ChatGPT   ┆ AKA       │
│          ┆ homolog   ┆           ┆ cereus    ┆   ┆           ┆           ┆           ┆ "Thoeris  │
│          ┆ of SIR2   ┆           ┆           ┆   ┆           ┆           ┆           ┆ A" by     │
│          ┆ antiph…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ authors;  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an…       │
│ 32499527 ┆ Structura ┆ ThsA      ┆ Bacillus  ┆ … ┆ Escherich ┆ TRUE      ┆ ChatGPT   ┆ "Fig. 2   │
│          ┆ l and fun ┆           ┆ cereus    ┆   ┆ ia coli   ┆           ┆           ┆ Crystal   │
│          ┆ ctional   ┆           ┆           ┆   ┆           ┆           ┆           ┆ structure │
│          ┆ evid…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ of T…     │
│ 32937646 ┆ Prokaryot ┆ vip6      ┆ Selenomon ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ as rumina ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ntium     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip8      ┆ Psychroba ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ cter luti ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ phocae    ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip15     ┆ Coralioma ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rgarita   ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ akajimens ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆ is        ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip21     ┆ Lewinella ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ persica   ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip47     ┆ Flammeovi ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ rga       ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ pacifica  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip50     ┆ Thermopla ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ smatales  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ archaeon  ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip56     ┆ Fibrobact ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ er sp.    ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip58     ┆ Pseudoalt ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ eromonas  ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ ulvae     ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 32937646 ┆ Prokaryot ┆ vip60     ┆ Lacinutri ┆ … ┆ Escherich ┆ null      ┆ M         ┆ From fig  │
│          ┆ ic        ┆           ┆ x marinif ┆   ┆ ia coli   ┆           ┆ Umanowicz ┆ 1 descrip │
│          ┆ viperins  ┆           ┆ lava      ┆   ┆           ┆           ┆           ┆ tion:     │
│          ┆ produce   ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Homol…   │
│          ┆ d…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
pl.Config.set_tbl_rows(30)

df_filt[["PMID", "Bacterial_gene_name", "Bacterial_Uniprot", "Human_gene_name"]]

shape: (29, 3)
┌──────────┬─────────────────────┬─────────────────┐
│ PMID     ┆ Bacterial_gene_name ┆ Human_gene_name │
│ ---      ┆ ---                 ┆ ---             │
│ i64      ┆ str                 ┆ str             │
╞══════════╪═════════════════════╪═════════════════╡
│ 30787435 ┆ cdnE                ┆ CGAS            │
│ 30787435 ┆ cdnE                ┆ CGAS            │
│ 40705877 ┆ ThsA                ┆ FAM118B         │
│ 32499527 ┆ ThsA                ┆ FAM118B         │
│ 40705877 ┆ ThsA                ┆ SIRT1           │
│ 32499527 ┆ ThsA                ┆ SIRT1           │
│ 40705877 ┆ ThsA                ┆ SIRT2           │
│ 32499527 ┆ ThsA                ┆ SIRT2           │
│ 40705877 ┆ ThsA                ┆ SIRT4           │
│ 32499527 ┆ ThsA                ┆ SIRT4           │
│ 40705877 ┆ ThsA                ┆ SIRT5           │
│ 32499527 ┆ ThsA                ┆ SIRT5           │
│ 40705877 ┆ ThsA                ┆ SIRT6           │
│ 32499527 ┆ ThsA                ┆ SIRT6           │
│ 40705877 ┆ ThsA                ┆ SIRT7           │
│ 32499527 ┆ ThsA                ┆ SIRT7           │
│ 32937646 ┆ NA                  ┆ RSAD2           │
│ 32937646 ┆ NA                  ┆ RSAD2           │
│ 32937646 ┆ NA                  ┆ RSAD2           │
│ 32937646 ┆ vip6                ┆ RSAD2           │
│ 32937646 ┆ vip8                ┆ RSAD2           │
│ 32937646 ┆ vip15               ┆ RSAD2           │
│ 32937646 ┆ NA                  ┆ RSAD2           │
│ 32937646 ┆ vip21               ┆ RSAD2           │
│ 32937646 ┆ vip47               ┆ RSAD2           │
│ 32937646 ┆ vip50               ┆ RSAD2           │
│ 32937646 ┆ vip56               ┆ RSAD2           │
│ 32937646 ┆ vip58               ┆ RSAD2           │
│ 32937646 ┆ vip60               ┆ RSAD2           │
└──────────┴─────────────────────┴─────────────────┘