In [1]:
import pandas as pd

In [3]:
df_refseq=pd.read_excel("../data/defense_finder/df-RefSeq.xlsx")
df_refseq

,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species
0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis
1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis
4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172328,GCF_012029695_NZ_CP061390_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061390,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061390_00118,GCF_012029695.2_NZ_CP061390_00121,"GCF_012029695_NZ_CP061390_00118,GCF_012029695_...",4.0,"Zorya__ZorA,Zorya__ZorB,Zorya_TypeI__ZorC,Zory...","WP_004182103.1,WP_004182101.1,WP_004182099.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172329,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975.1,NZ_CP060719,Zorya,Zorya_TypeI,GCF_014396975.1_NZ_CP060719_00618,GCF_014396975.1_NZ_CP060719_00621,"GCF_014396975_NZ_CP060719_00618,GCF_014396975_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_187553130.1,WP_187553131.1,WP_187553132.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Xanthomonadales,Xanthomonadaceae,Thermomonas,Thermomonas carbonis
172330,GCF_002055855_NZ_CP020067_Zorya_TypeI_1,GCF_002055855.1,NZ_CP020067,Zorya,Zorya_TypeI,GCF_002055855.1_NZ_CP020067_01216,GCF_002055855.1_NZ_CP020067_01219,"GCF_002055855_NZ_CP020067_01216,GCF_002055855_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172331,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,"GCF_012029695_NZ_CP061389_04302,GCF_012029695_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,"GCF_002356355_NZ_AP018052_01338,GCF_002356355_...",4.0,"Zorya__ZorA2,Zorya__ZorB,Zorya_TypeI__ZorC,Zor...","WP_096365918.1,WP_197703019.1,WP_157745444.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus

In [4]:
df_refseq_na_values = df_refseq[df_refseq['accession_in_sys'].isna()]
df_refseq_na_values

,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species
66089,GCF_016592595_NZ_AP012977,GCF_016592595.1,NZ_AP012977,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Gammaproteobacteria,NaN,NaN,NaN,Abyssogena phaseoliformis symbiont
66090,GCF_001602115_NZ_CP014353,GCF_001602115.1,NZ_CP014353,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Actinomycetota,Actinomycetes,Propionibacteriales,Propionibacteriaceae,Acidipropionibacterium,Acidipropionibacterium acidipropionici
66091,GCF_000193495_NZ_AP023412,GCF_000193495.2,NZ_AP023412,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhodospirillales,Acetobacteraceae,Acetobacter,Acetobacter aceti
66092,GCF_000193495_NZ_AP023413,GCF_000193495.2,NZ_AP023413,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhodospirillales,Acetobacteraceae,Acetobacter,Acetobacter aceti
66093,GCF_000193495_NZ_AP023414,GCF_000193495.2,NZ_AP023414,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Rhodospirillales,Acetobacteraceae,Acetobacter,Acetobacter aceti
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86031,GCF_019316745_NZ_CP079223,GCF_019316745.1,NZ_CP079223,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Zymomonadaceae,Zymomonas,Zymomonas mobilis
86032,GCF_020162135_NZ_CP083899,GCF_020162135.1,NZ_CP083899,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Zymomonadaceae,Zymomonas,Zymomonas mobilis
86033,GCF_020162135_NZ_CP083900,GCF_020162135.1,NZ_CP083900,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Zymomonadaceae,Zymomonas,Zymomonas mobilis
86034,GCF_020162135_NZ_CP083901,GCF_020162135.1,NZ_CP083901,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Alphaproteobacteria,Sphingomonadales,Zymomonadaceae,Zymomonas,Zymomonas mobilis
86035,GCF_003610015_NZ_AP018934,GCF_003610015.1,NZ_AP018934,No system found,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacteria,Pseudomonadota,Gammaproteobacteria,Oceanospirillales,Halomonadaceae,Zymobacter,Zymobacter palmae

In [5]:
# Remove all rows with NA
df_refseq_no_na=df_refseq[df_refseq['accession_in_sys'].notna()][["sys_id","sys_beg","sys_end","type","subtype","accession_in_sys","species"]]
df_refseq_no_na

,sys_id,sys_beg,sys_end,type,subtype,accession_in_sys,species
0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,Abi2,Abi2,WP_010728290.1,Enterococcus lactis
1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,Abi2,Abi2,WP_129646131.1,Mycoplasmopsis maculosa
2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,Abi2,Abi2,WP_129647121.1,Mycoplasmopsis maculosa
3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,Abi2,Abi2,WP_149208562.1,Bacillus paralicheniformis
4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,Abi2,Abi2,WP_097001356.1,Leuconostoc gasicomitatum
...,...,...,...,...,...,...,...
172328,GCF_012029695_NZ_CP061390_Zorya_TypeI_1,GCF_012029695.2_NZ_CP061390_00118,GCF_012029695.2_NZ_CP061390_00121,Zorya,Zorya_TypeI,"WP_004182103.1,WP_004182101.1,WP_004182099.1,W...",Klebsiella pneumoniae
172329,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975.1_NZ_CP060719_00618,GCF_014396975.1_NZ_CP060719_00621,Zorya,Zorya_TypeI,"WP_187553130.1,WP_187553131.1,WP_187553132.1,W...",Thermomonas carbonis
172330,GCF_002055855_NZ_CP020067_Zorya_TypeI_1,GCF_002055855.1_NZ_CP020067_01216,GCF_002055855.1_NZ_CP020067_01219,Zorya,Zorya_TypeI,"WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Klebsiella pneumoniae
172331,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,Zorya,Zorya_TypeI,"WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Klebsiella pneumoniae
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,Zorya,Zorya_TypeI,"WP_096365918.1,WP_197703019.1,WP_157745444.1,W...",Thiohalobacter thiocyanaticus

### Clean up

- The "accession_in_sys" column may contain comma-separated lists of accessions in each row.
- Some accessions appear multiple times across rows, possibly with different "type", "subtype", or "species". The sys_id, sys_beg and sys_end will remain unique
- For clean up:
    - Split those comma-separated accessions into separate rows.
    - Deduplicate based on individual accessions.
        - Group by each unique accession and aggregate other columns into lists of ALL values:
        
            `../data/defense_finder/2025-06-20_df_refseq_unique_accessions.tsv`
        - Group by each unique accession and aggregate other columns into lists of ALL values, also count replicate accessions and rank them from most to least prevalent:
        
            `../data/defense_finder/2025-06-24_df_refseq_unique_accessions_ranked.tsv`
        - Group by each unique accession and aggregate other columns into lists of their unique values. Also count replicate accessions and rank them from most to least prevalent:
        
            `../data/defense_finder/2025-06-24_df_refseq_unique_accessions_w_unique_values_ranked.tsv`

In [6]:
# Step 1: Split the 'accession' column into multiple rows
df_refseq_no_na_expanded = df_refseq_no_na.assign(accession_in_sys=df_refseq_no_na['accession_in_sys'].str.split(',')).explode('accession_in_sys')
df_refseq_no_na_expanded

,sys_id,sys_beg,sys_end,type,subtype,accession_in_sys,species
0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,Abi2,Abi2,WP_010728290.1,Enterococcus lactis
1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,Abi2,Abi2,WP_129646131.1,Mycoplasmopsis maculosa
2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,Abi2,Abi2,WP_129647121.1,Mycoplasmopsis maculosa
3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,Abi2,Abi2,WP_149208562.1,Bacillus paralicheniformis
4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,Abi2,Abi2,WP_097001356.1,Leuconostoc gasicomitatum
...,...,...,...,...,...,...,...
172331,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,Zorya,Zorya_TypeI,WP_004178700.1,Klebsiella pneumoniae
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,Zorya,Zorya_TypeI,WP_096365918.1,Thiohalobacter thiocyanaticus
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,Zorya,Zorya_TypeI,WP_197703019.1,Thiohalobacter thiocyanaticus
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,Zorya,Zorya_TypeI,WP_157745444.1,Thiohalobacter thiocyanaticus
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,Zorya,Zorya_TypeI,WP_096365920.1,Thiohalobacter thiocyanaticus

In [7]:
# Step 2: Strip whitespace (just in case)
df_refseq_no_na_expanded['accession_in_sys'] = df_refseq_no_na_expanded['accession_in_sys'].str.strip()

In [8]:
# Step 3: Get duplicate accession counts
accession_counts = df_refseq_no_na_expanded['accession_in_sys'].value_counts().rename_axis('accession_in_sys').reset_index(name='duplicate_count')
accession_counts

       accession_in_sys  duplicate_count
0        WP_000581937.1             1490
1        WP_000254738.1             1012
2        WP_001398199.1              851
3        WP_000557619.1              848
4        WP_001372321.1              692
...                 ...              ...
198353   WP_038474928.1                1
198354   WP_221260368.1                1
198355   WP_221260369.1                1
198356   WP_221260371.1                1
198357   WP_096365920.1                1

[198358 rows x 2 columns]

In [9]:
# Step 4: Group by accession and aggregate other columns into lists
df_refseq_no_na_grouped = df_refseq_no_na_expanded.groupby('accession_in_sys', as_index=False).agg({
    'type': lambda x: ','.join(x),
    'subtype': lambda x: ','.join(x),
    'species': lambda x: ','.join(x),
    "sys_id": lambda x: ','.join(x),
    "sys_beg": lambda x: ','.join(x),
    "sys_end": lambda x: ','.join(x)
})


# Step 5: Merge the accession counts with the merged dataframe
df_refseq_no_na_grouped_w_counts = df_refseq_no_na_grouped.merge(accession_counts, on='accession_in_sys')

# Step 6: Add the rank and sort the dataframe in descending order
df_refseq_no_na_grouped_w_counts['rank'] = df_refseq_no_na_grouped_w_counts['duplicate_count'].rank(method='dense', ascending=False).astype(int)
df_refseq_no_na_grouped_w_counts = df_refseq_no_na_grouped_w_counts.sort_values(by='rank', ascending=True).reset_index(drop=True)
df_refseq_no_na_grouped_w_counts

,accession_in_sys,type,subtype,species,sys_id,sys_beg,sys_end,duplicate_count,rank
0,WP_000581937.1,"MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","Escherichia coli,Escherichia coli,Escherichia ...","GCF_009176965_NZ_AP019675_MazEF_1,GCF_02265424...","GCF_009176965.1_NZ_AP019675_00923,GCF_02265424...","GCF_009176965.1_NZ_AP019675_00924,GCF_02265424...",1490,1
1,WP_000254738.1,"MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","Escherichia coli,Escherichia coli,Escherichia ...","GCF_009176965_NZ_AP019675_MazEF_1,GCF_00943221...","GCF_009176965.1_NZ_AP019675_00923,GCF_00943221...","GCF_009176965.1_NZ_AP019675_00924,GCF_00943221...",1012,2
2,WP_001398199.1,"MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","Klebsiella pneumoniae,Escherichia coli,Escheri...","GCF_013349045_NZ_CP054770_MazEF_1,GCF_00201194...","GCF_013349045.1_NZ_CP054770_00003,GCF_00201194...","GCF_013349045.1_NZ_CP054770_00004,GCF_00201194...",851,3
3,WP_000557619.1,"MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazEF,MazE...","Klebsiella pneumoniae,Escherichia coli,Escheri...","GCF_013349045_NZ_CP054770_MazEF_1,GCF_00201194...","GCF_013349045.1_NZ_CP054770_00003,GCF_00201194...","GCF_013349045.1_NZ_CP054770_00004,GCF_00201194...",848,4
4,WP_001372321.1,"Mok_Hok_Sok,Mok_Hok_Sok,Mok_Hok_Sok,Mok_Hok_So...","Mok_Hok_Sok,Mok_Hok_Sok,Mok_Hok_Sok,Mok_Hok_So...","Klebsiella pneumoniae,Klebsiella pneumoniae,Es...","GCF_013349045_NZ_CP054770_Mok_Hok_Sok_1,GCF_90...","GCF_013349045.1_NZ_CP054770_00048,GCF_90486632...","GCF_013349045.1_NZ_CP054770_00048,GCF_90486632...",692,5
...,...,...,...,...,...,...,...,...,...
198353,WP_086625893.1,RM,RM_Type_II,Enterobacter kobei,GCF_023333675_NZ_CP083862_RM_Type_II_2,GCF_023333675.1_NZ_CP083862_03290,GCF_023333675.1_NZ_CP083862_03291,1,202
198354,WP_086627698.1,Dpd,Dpd,Klebsiella pneumoniae,GCF_013305325_NZ_CP054303_Dpd_5,GCF_013305325.1_NZ_CP054303_05013,GCF_013305325.1_NZ_CP054303_05024,1,202
198355,WP_086631304.1,Lamassu-Fam,Lamassu-Mrr,Klebsiella variicola,GCF_900622615_NZ_LR130543_Lamassu-Mrr_2,GCF_900622615.1_NZ_LR130543_01680,GCF_900622615.1_NZ_LR130543_01682,1,202
198356,WP_086621734.1,Cas,CAS_Class1-Subtype-I-F,Kushneria konosiri,GCF_002155145_NZ_CP021323_CAS_Class1-Subtype-I...,GCF_002155145.1_NZ_CP021323_01777,GCF_002155145.1_NZ_CP021323_01782,1,202
198357,YP_008877601.2,CARD_NLR,CARD_NLR_Endonuclease,Caulobacter vibrioides,GCF_000022005_NC_011916_CARD_NLR_Endonuclease_1,GCF_000022005.1_NC_011916_00613,GCF_000022005.1_NC_011916_00615,1,202

In [10]:
# Step 7: Repeat the grouping of accession but this time only retain unique type, subtype and species
df_refseq_no_na_grouped_uniq = df_refseq_no_na_expanded.groupby('accession_in_sys', as_index=False).agg({
    'type': lambda x: ','.join(set(x)),
    'subtype': lambda x: ','.join(set(x)),
    'species': lambda x: ','.join(set(x)),
    "sys_id": lambda x: ','.join(set(x)),
    "sys_beg": lambda x: ','.join(set(x)),
    "sys_end": lambda x: ','.join(set(x))
})

# Step 8: Merge the accession counts with the merged dataframe
df_refseq_no_na_grouped_uniq_w_counts = df_refseq_no_na_grouped_uniq.merge(accession_counts, on='accession_in_sys')

# Step 9: Add the rank and sort the dataframe in descending order
df_refseq_no_na_grouped_uniq_w_counts['rank'] = df_refseq_no_na_grouped_uniq_w_counts['duplicate_count'].rank(method='dense', ascending=False).astype(int)
df_refseq_no_na_grouped_uniq_w_counts = df_refseq_no_na_grouped_uniq_w_counts.sort_values(by='rank', ascending=True).reset_index(drop=True)

In [11]:
df_refseq_no_na_grouped_uniq_w_counts

,accession_in_sys,type,subtype,species,sys_id,sys_beg,sys_end,duplicate_count,rank
0,WP_000581937.1,MazEF,MazEF,"Shigella dysenteriae,Shigella sp. PIB,Escheric...","GCF_002787545_NZ_CP024815_MazEF_4,GCF_00522154...","GCF_022558645.1_NZ_CP060867_03480,GCF_02082757...","GCF_016776085.1_NZ_CP068814_01184,GCF_02235470...",1490,1
1,WP_000254738.1,MazEF,MazEF,"Shigella dysenteriae,Shigella sp. PIB,Escheric...","GCF_003956225_NZ_CP025913_MazEF_1,GCF_00190071...","GCF_022558645.1_NZ_CP060867_03480,GCF_01337427...","GCF_905330145.2_NZ_OW967802_01017,GCF_00301807...",1012,2
2,WP_001398199.1,MazEF,MazEF,"Klebsiella aerogenes,Enterobacter sp. MGH 7,Pr...","GCF_019375055_NZ_CP089135_MazEF_1,GCF_00198953...","GCF_002012025.1_NZ_CP018969_00098,GCF_02235388...","GCF_003031795.1_NZ_CP020519_00079,GCF_00869344...",851,3
3,WP_000557619.1,MazEF,MazEF,"Klebsiella aerogenes,Enterobacter sp. MGH 7,Pr...","GCF_019375055_NZ_CP089135_MazEF_1,GCF_00198953...","GCF_002012025.1_NZ_CP018969_00098,GCF_02235388...","GCF_003031795.1_NZ_CP020519_00079,GCF_00869344...",848,4
4,WP_001372321.1,Mok_Hok_Sok,Mok_Hok_Sok,"Klebsiella aerogenes,Escherichia coli,Citrobac...","GCF_022559325_NZ_CP060980_Mok_Hok_Sok_1,GCF_01...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...",692,5
...,...,...,...,...,...,...,...,...,...
198353,WP_086625893.1,RM,RM_Type_II,Enterobacter kobei,GCF_023333675_NZ_CP083862_RM_Type_II_2,GCF_023333675.1_NZ_CP083862_03290,GCF_023333675.1_NZ_CP083862_03291,1,202
198354,WP_086627698.1,Dpd,Dpd,Klebsiella pneumoniae,GCF_013305325_NZ_CP054303_Dpd_5,GCF_013305325.1_NZ_CP054303_05013,GCF_013305325.1_NZ_CP054303_05024,1,202
198355,WP_086631304.1,Lamassu-Fam,Lamassu-Mrr,Klebsiella variicola,GCF_900622615_NZ_LR130543_Lamassu-Mrr_2,GCF_900622615.1_NZ_LR130543_01680,GCF_900622615.1_NZ_LR130543_01682,1,202
198356,WP_086621734.1,Cas,CAS_Class1-Subtype-I-F,Kushneria konosiri,GCF_002155145_NZ_CP021323_CAS_Class1-Subtype-I...,GCF_002155145.1_NZ_CP021323_01777,GCF_002155145.1_NZ_CP021323_01782,1,202
198357,YP_008877601.2,CARD_NLR,CARD_NLR_Endonuclease,Caulobacter vibrioides,GCF_000022005_NC_011916_CARD_NLR_Endonuclease_1,GCF_000022005.1_NC_011916_00613,GCF_000022005.1_NC_011916_00615,1,202

In [12]:
# Write to csv file
with pd.ExcelWriter('../data/defense_finder/2025-06-24_df_refseq_clean_up.xlsx') as writer:   
    df_refseq_na_values.to_excel(writer,sheet_name="no_accs",index=False)
    df_refseq_no_na_grouped.to_excel(writer,sheet_name="uniq_accs",index=False)
    df_refseq_no_na_grouped_w_counts.to_excel(writer,sheet_name="uniq_accs_ranked",index=False)
    df_refseq_no_na_grouped_uniq_w_counts.to_excel(writer,sheet_name="uniq_accs_w_uniq_values_ranked",index=False)

In [ ]:
# This data has been moved to archive
#df_refseq_no_na_grouped.to_csv("../data/defense_finder/2025-06-20_df_refseq_unique_accessions.tsv",sep="\t",index=False)
#df_refseq_na_values.to_csv("../data/defense_finder/2025-06-20_df_refseq_no_accessions.tsv",sep="\t",index=False)
#df_refseq_no_na_grouped_w_counts.to_csv("../data/defense_finder/2025-06-24_df_refseq_unique_accessions_ranked.tsv",sep="\t",index=False)
#df_refseq_no_na_grouped_uniq_w_counts.to_csv("../data/defense_finder/2025-06-24_df_refseq_unique_accessions_w_unique_values_ranked.tsv",sep="\t",index=False)