### Fetch UniParc IDs for RefSeq accessions that didn't map to a Uniprot ID

In [1]:
import re
import time
import json
import requests
from requests.adapters import HTTPAdapter, Retry
import pandas as pd


## This code was adapted from https://www.uniprot.org/help/id_mapping_prog


## Functions to retrieve UniParc ID
POLLING_INTERVAL = 3
API_URL = "https://rest.uniprot.org"

retries = Retry(total=5, backoff_factor=0.25, status_forcelist=[500, 502, 503, 504])
session = requests.Session()
session.mount("https://", HTTPAdapter(max_retries=retries))


def check_response(response):
    try:
        response.raise_for_status()
    except requests.HTTPError:
        print(response.json())
        raise


def submit_id_mapping(from_db, to_db, ids):
    request = requests.post(
        f"{API_URL}/idmapping/run",
        data={"from": from_db, "to": to_db, "ids": ",".join(ids)},
    )
    check_response(request)
    return request.json()["jobId"]


def check_id_mapping_results_ready(job_id):
    while True:
        request = session.get(f"{API_URL}/idmapping/status/{job_id}")
        check_response(request)
        j = request.json()
        if "jobStatus" in j:
            if j["jobStatus"] in ("NEW", "RUNNING"):
                print(f"Retrying in {POLLING_INTERVAL}s")
                time.sleep(POLLING_INTERVAL)
            else:
                raise Exception(j["jobStatus"])
        else:
            return bool(j["results"] or j["failedIds"] or j["suggestedIds"])

def get_id_mapping_results_link(job_id):
    url = f"{API_URL}/idmapping/details/{job_id}"
    request = session.get(url)
    check_response(request)
    return request.json()["redirectURL"]


def get_id_mapping_results_search(url):
    results = requests.get(url)
    return results.json()

In [2]:
no_uniprot_acc=pd.read_excel("../data/defense_finder/refseq2uniprot_script/2025-06-24_RefSeq2Uniprot_mapping.xlsx",sheet_name="no_uniprot_matches")
no_uniprot_acc

,accession_in_sys,type,subtype,species,sys_id,sys_beg,sys_end,duplicate_count,rank
0,WP_001372321.1,Mok_Hok_Sok,Mok_Hok_Sok,"Klebsiella aerogenes,Escherichia coli,Citrobac...","GCF_022559325_NZ_CP060980_Mok_Hok_Sok_1,GCF_01...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...",692,5
1,WP_096937776.1,Mok_Hok_Sok,Mok_Hok_Sok,"Escherichia coli,Escherichia fergusonii,Klebsi...","GCF_016026215_NZ_CP065610_Mok_Hok_Sok_1,GCF_01...","GCF_010365485.1_NZ_CP048362_00038,GCF_02042404...","GCF_010365485.1_NZ_CP048362_00038,GCF_02042404...",262,25
2,WP_003917092.1,Cas,CAS_Class1-Subtype-III-A,"Mycobacterium tuberculosis,Mycobacterium orygis",GCF_014884645_NZ_CP043996_CAS_Class1-Subtype-I...,"GCF_002975475.1_NZ_CP027035_02939,GCF_01490083...","GCF_013010385.1_NZ_CP053092_02977,GCF_01691777...",257,27
3,WP_001381369.1,Cas,CAS_Class1-Subtype-I-E,"Shigella flexneri,Escherichia coli,Escherichia...",GCF_013167055_NZ_CP053605_CAS_Class1-Subtype-I...,"GCF_014075915.1_NZ_CP050031_00968,GCF_02260534...","GCF_014075795.1_NZ_CP050036_00976,GCF_00803329...",254,28
4,WP_020277900.1,MazEF,MazEF,"Klebsiella aerogenes,Enterobacter roggenkampii...","GCF_905330065_NZ_OW967005_MazEF_1,GCF_01677594...","GCF_011106605.1_NZ_CP040031_00014,GCF_02275994...","GCF_018274525.2_NZ_CP086665_00007,GCF_00190859...",215,39
...,...,...,...,...,...,...,...,...,...
122259,WP_086613943.1,BREX,BREX_I,Klebsiella pneumoniae,GCF_016925315_NZ_CP070438_BREX_I_2,GCF_016925315.1_NZ_CP070438_00016,GCF_016925315.1_NZ_CP070438_00021,1,202
122260,WP_086414403.1,RM,RM_Type_I,Eggerthella lenta,GCF_002148255_NZ_CP021140_RM_Type_I_1,GCF_002148255.1_NZ_CP021140_00899,GCF_002148255.1_NZ_CP021140_00901,1,202
122261,WP_086625893.1,RM,RM_Type_II,Enterobacter kobei,GCF_023333675_NZ_CP083862_RM_Type_II_2,GCF_023333675.1_NZ_CP083862_03290,GCF_023333675.1_NZ_CP083862_03291,1,202
122262,WP_086627698.1,Dpd,Dpd,Klebsiella pneumoniae,GCF_013305325_NZ_CP054303_Dpd_5,GCF_013305325.1_NZ_CP054303_05013,GCF_013305325.1_NZ_CP054303_05024,1,202
122263,WP_086631304.1,Lamassu-Fam,Lamassu-Mrr,Klebsiella variicola,GCF_900622615_NZ_LR130543_Lamassu-Mrr_2,GCF_900622615.1_NZ_LR130543_01680,GCF_900622615.1_NZ_LR130543_01682,1,202

In [3]:
no_uniprot_acc_list=no_uniprot_acc["accession_in_sys"].tolist()
len(no_uniprot_acc_list),no_uniprot_acc_list

(122264,
 ['WP_001372321.1',
  'WP_096937776.1',
  'WP_003917092.1',
  'WP_001381369.1',
  'WP_020277900.1',
  'WP_000357807.1',
  'WP_159376494.1',
  'WP_001443175.1',
  'WP_223178619.1',
  'WP_000880885.1',
  'WP_000571783.1',
  'WP_000937120.1',
  'WP_000061856.1',
  'WP_000777275.1',
  'WP_010922512.1',
  'WP_001323520.1',
  'WP_001084115.1',
  'WP_167876495.1',
  'WP_000960581.1',
  'WP_071532149.1',
  'WP_168876894.1',
  'WP_006250003.1',
  'WP_000433154.1',
  'WP_004195968.1',
  'WP_032433805.1',
  'WP_032433488.1',
  'WP_000562556.1',
  'WP_009308509.1',
  'WP_004178703.1',
  'WP_004178705.1',
  'WP_019842341.1',
  'WP_004178700.1',
  'WP_000101606.1',
  'WP_000443455.1',
  'WP_003689382.1',
  'WP_223349259.1',
  'WP_001356249.1',
  'WP_001425460.1',
  'WP_223340727.1',
  'WP_001096907.1',
  'WP_002220782.1',
  'WP_000063179.1',
  'WP_032875608.1',
  'WP_000020778.1',
  'WP_012503916.1',
  'WP_003907189.1',
  'WP_001104341.1',
  'WP_012602456.1',
  'WP_000192872.1',
  'WP_005014373.1',
  'WP_012503917.1',
  'WP_001521154.1',
  'WP_023283164.1',
  'WP_022630855.1',
  'WP_000063170.1',
  'WP_080229150.1',
  'WP_002224275.1',
  'WP_001678529.1',
  'WP_000385105.1',
  'WP_002934299.1',
  'WP_000915483.1',
  'WP_016187290.1',
  'WP_002989949.1',
  'WP_002242331.1',
  'WP_002932805.1',
  'WP_021575209.1',
  'WP_015059139.1',
  'WP_032875349.1',
  'WP_032875605.1',
  'WP_003694912.1',
  'WP_006248462.1',
  'WP_227746616.1',
  'WP_006250671.1',
  'WP_022649084.1',
  'WP_006250672.1',
  'WP_002211866.1',
  'WP_001041189.1',
  'WP_032415893.1',
  'WP_023982161.1',
  'WP_000108736.1',
  'WP_012737279.1',
  'WP_012737253.1',
  'WP_004180290.1',
  'WP_224553826.1',
  'WP_017146687.1',
  'WP_224553828.1',
  'WP_012737314.1',
  'WP_224557923.1',
  'WP_000150995.1',
  'WP_003691372.1',
  'WP_001352286.1',
  'WP_022648718.1',
  'WP_224557853.1',
  'WP_224557855.1',
  'WP_114276004.1',
  'WP_012446057.1',
  'WP_006250674.1',
  'WP_227746614.1',
  'WP_001593930.1',
  'WP_032433950.1',
  'WP_013242856.1',
  'WP_001521911.1',
  'WP_071562429.1',
  'WP_021312557.1',
  'WP_100067201.1',
  'WP_223349791.1',
  'WP_032416923.1',
  'WP_012737310.1',
  'WP_012737312.1',
  'WP_223716397.1',
  'WP_006250670.1',
  'WP_000110087.1',
  'WP_001101565.1',
  'WP_012737252.1',
  'WP_002946668.1',
  'WP_020824140.1',
  'WP_000187069.1',
  'WP_002982804.1',
  'WP_023330142.1',
  'WP_002211867.1',
  'WP_011285159.1',
  'WP_223225479.1',
  'WP_014325846.1',
  'WP_022652238.1',
  'WP_032418879.1',
  'WP_000889014.1',
  'WP_015444231.1',
  'WP_123836165.1',
  'WP_123618666.1',
  'WP_071959649.1',
  'WP_223814687.1',
  'WP_004521208.1',
  'WP_000012516.1',
  'WP_223156217.1',
  'WP_000584997.1',
  'WP_229020258.1',
  'WP_014326283.1',
  'WP_014326282.1',
  'WP_014325848.1',
  'WP_011284745.1',
  'WP_094136088.1',
  'WP_001551050.1',
  'WP_011285158.1',
  'WP_196529333.1',
  'WP_016211530.1',
  'WP_032418443.1',
  'WP_032418188.1',
  'WP_032414549.1',
  'WP_078055966.1',
  'WP_020824151.1',
  'WP_197736718.1',
  'WP_196547718.1',
  'WP_017627993.1',
  'WP_102734060.1',
  'WP_015484256.1',
  'WP_015484257.1',
  'WP_172621306.1',
  'WP_032418459.1',
  'WP_001325828.1',
  'WP_014326278.1',
  'WP_000739990.1',
  'WP_229001947.1',
  'WP_042465377.1',
  'WP_001376998.1',
  'WP_002222491.1',
  'WP_000599828.1',
  'WP_011407754.1',
  'WP_199285672.1',
  'WP_002211868.1',
  'WP_000062282.1',
  'WP_010922510.1',
  'WP_142778025.1',
  'WP_000168559.1',
  'WP_000281434.1',
  'WP_017154976.1',
  'WP_023303963.1',
  'WP_004222271.1',
  'WP_001223964.1',
  'WP_004343803.1',
  'WP_000447780.1',
  'WP_001375150.1',
  'WP_071836746.1',
  'WP_011225936.1',
  'WP_002321314.1',
  'WP_053513661.1',
  'WP_227985893.1',
  'WP_002321313.1',
  'WP_024745666.1',
  'WP_000132365.1',
  'WP_003488925.1',
  'WP_011284986.1',
  'WP_033003220.1',
  'WP_001513536.1',
  'WP_003105626.1',
  'WP_000829994.1',
  'WP_024744457.1',
  'WP_024744456.1',
  'WP_002340336.1',
  'WP_002344971.1',
  'WP_024745594.1',
  'WP_014522909.1',
  'WP_223176087.1',
  'WP_223293117.1',
  'WP_033004264.1',
  'WP_032647082.1',
  'WP_001514500.1',
  'WP_015463226.1',
  'WP_001513535.1',
  'WP_032408834.1',
  'WP_011409831.1',
  'WP_053513660.1',
  'WP_237025418.1',
  'WP_223175346.1',
  'WP_206640390.1',
  'WP_227944641.1',
  'WP_032408833.1',
  'WP_223251341.1',
  'WP_231139811.1',
  'WP_033638854.1',
  'WP_032414116.1',
  'WP_032414117.1',
  'WP_010922509.1',
  'WP_064162471.1',
  'WP_022646034.1',
  'WP_042919266.1',
  'WP_223293119.1',
  'WP_002210191.1',
  'WP_230374854.1',
  'WP_016504384.1',
  'WP_024744455.1',
  'WP_015376197.1',
  'WP_003422618.1',
  'WP_230937716.1',
  'WP_003422619.1',
  'WP_003422610.1',
  'WP_064162472.1',
  'WP_032414115.1',
  'WP_053067569.1',
  'WP_003422614.1',
  'WP_023302105.1',
  'WP_077681940.1',
  'WP_015444645.1',
  'WP_071534647.1',
  'WP_000469823.1',
  'WP_233145404.1',
  'WP_001193075.1',
  'WP_001207938.1',
  'WP_011409829.1',
  'WP_014326450.1',
  'WP_001398805.1',
  'WP_009906182.1',
  'WP_237025420.1',
  'WP_062826779.1',
  'WP_025458713.1',
  'WP_001114356.1',
  'WP_011528583.1',
  'WP_003159837.1',
  'WP_078072093.1',
  'WP_005927106.1',
  'WP_023909157.1',
  'WP_023343022.1',
  'WP_077907039.1',
  'WP_000383016.1',
  'WP_039023230.1',
  'WP_230078415.1',
  'WP_001090220.1',
  'WP_000447773.1',
  'WP_003424503.1',
  'WP_041181951.1',
  'WP_003424506.1',
  'WP_015379640.1',
  'WP_002221142.1',
  'WP_003424499.1',
  'WP_000433147.1',
  'WP_000887497.1',
  'WP_235658924.1',
  'WP_000229085.1',
  'WP_000469832.1',
  'WP_036781349.1',
  'WP_050885114.1',
  'WP_000915960.1',
  'WP_011407656.1',
  'WP_015484771.1',
  'WP_125168758.1',
  'WP_223235436.1',
  'WP_001379612.1',
  'WP_032440985.1',
  'WP_053513436.1',
  'WP_011921992.1',
  'WP_021359714.1',
  'WP_152687277.1',
  'WP_001024666.1',
  'WP_016504385.1',
  'WP_010729551.1',
  'WP_000427097.1',
  'WP_000788537.1',
  'WP_012027389.1',
  'WP_050885115.1',
  'WP_188348580.1',
  'WP_000790512.1',
  'WP_000806084.1',
  'WP_000548124.1',
  'WP_000428596.1',
  'WP_001297700.1',
  'WP_041182275.1',
  'WP_229687174.1',
  'WP_023302104.1',
  'WP_023301568.1',
  'WP_001988174.1',
  'WP_040174621.1',
  'WP_001193928.1',
  'WP_000613299.1',
  'WP_000602661.1',
  'WP_015484058.1',
  'WP_015484059.1',
  'WP_102734057.1',
  'WP_014326158.1',
  'WP_229940495.1',
  'WP_023341070.1',
  'WP_023325100.1',
  'WP_000094925.1',
  'WP_000278666.1',
  'WP_001170530.1',
  'WP_001154483.1',
  'WP_000362741.1',
  'WP_000050006.1',
  'WP_088607455.1',
  'WP_022615726.1',
  'WP_000558913.1',
  'WP_011579220.1',
  'WP_000996748.1',
  'WP_000693661.1',
  'WP_004348746.1',
  'WP_000386439.1',
  'WP_000724528.1',
  'WP_001006082.1',
  'WP_000258887.1',
  'WP_001139750.1',
  'WP_044383147.1',
  'WP_000346715.1',
  'WP_001129183.1',
  'WP_000735207.1',
  'WP_053320758.1',
  'WP_006250001.1',
  'WP_017628493.1',
  'WP_000756058.1',
  'WP_102741079.1',
  'WP_001447084.1',
  'WP_014608283.1',
  'WP_050598711.1',
  'WP_023317235.1',
  'WP_202976311.1',
  'WP_094139126.1',
  'WP_000254493.1',
  'WP_223364258.1',
  'WP_011109507.1',
  'WP_001201808.1',
  'WP_001147690.1',
  'WP_002946669.1',
  'WP_224557857.1',
  'WP_002882659.1',
  'WP_251266265.1',
  'WP_015240924.1',
  'WP_001987716.1',
  'WP_001129176.1',
  'WP_022196948.1',
  'WP_049254555.1',
  'WP_020862545.1',
  'WP_000824288.1',
  'WP_049253269.1',
  'WP_047351814.1',
  'WP_044383143.1',
  'WP_017627989.1',
  'WP_147810693.1',
  'WP_029505552.1',
  'WP_017627991.1',
  'WP_053320759.1',
  'WP_017283224.1',
  'WP_002989041.1',
  'WP_072652752.1',
  'WP_022645928.1',
  'WP_023316685.1',
  'WP_230453483.1',
  'WP_010922252.1',
  'WP_002229413.1',
  'WP_229001945.1',
  'WP_200866217.1',
  'WP_004348749.1',
  'WP_012952176.1',
  'WP_197665280.1',
  'WP_000040318.1',
  'WP_000022533.1',
  'WP_000392522.1',
  'WP_000251225.1',
  'WP_202557271.1',
  'WP_014635701.1',
  'WP_014608135.1',
  'WP_001297331.1',
  'WP_010922657.1',
  'WP_223201512.1',
  'WP_004555439.1',
  'WP_224230667.1',
  'WP_000931915.1',
  'WP_048994039.1',
  'WP_010922656.1',
  'WP_000136607.1',
  'WP_038270864.1',
  'WP_014608284.1',
  'WP_001513100.1',
  'WP_102733860.1',
  'WP_102733859.1',
  'WP_000006268.1',
  'WP_001442952.1',
  'WP_085962535.1',
  'WP_001357997.1',
  'WP_230428187.1',
  'WP_074193709.1',
  'WP_001519853.1',
  'WP_000880882.1',
  'WP_000041884.1',
  'WP_047951660.1',
  'WP_012816355.1',
  'WP_017627987.1',
  'WP_000312400.1',
  'WP_017628125.1',
  'WP_011285506.1',
  'WP_004155177.1',
  'WP_000186145.1',
  'WP_016922464.1',
  'WP_016504218.1',
  'WP_040181140.1',
  'WP_009891261.1',
  'WP_009890657.1',
  'WP_004155179.1',
  'WP_011408818.1',
  'WP_000390795.1',
  'WP_009349902.1',
  'WP_020862963.1',
  'WP_124072201.1',
  'WP_001095581.1',
  'WP_024431614.1',
  'WP_004159620.1',
  'WP_004159622.1',
  'WP_004159607.1',
  'WP_004159615.1',
  'WP_004159618.1',
  'WP_004159610.1',
  'WP_004159604.1',
  'WP_004159613.1',
  'WP_000632676.1',
  'WP_014490283.1',
  'WP_009891270.1',
  'WP_002856642.1',
  'WP_000968685.1',
  'WP_062627966.1',
  'WP_001598204.1',
  'WP_004545288.1',
  'WP_009891533.1',
  'WP_001594372.1',
  'WP_009891534.1',
  'WP_009891263.1',
  'WP_000251226.1',
  'WP_009893753.1',
  'WP_016211321.1',
  'WP_003162915.1',
  'WP_015647862.1',
  'WP_010922655.1',
  'WP_000200813.1',
  'WP_072161528.1',
  'WP_048993388.1',
  'WP_002378777.1',
  'WP_002378778.1',
  'WP_251266343.1',
  'WP_001233958.1',
  'WP_197723474.1',
  'WP_010733696.1',
  'WP_002807242.1',
  'WP_000880884.1',
  'WP_004155178.1',
  'WP_002245104.1',
  'WP_016487840.1',
  'WP_065213378.1',
  'WP_227522504.1',
  'WP_000190898.1',
  'WP_065213379.1',
  'WP_002401675.1',
  'WP_031488520.1',
  'WP_004155171.1',
  'WP_004155172.1',
  'WP_020862964.1',
  'WP_000424707.1',
  'WP_032740191.1',
  'WP_000394003.1',
  'WP_223195031.1',
  'WP_004155173.1',
  'WP_004222275.1',
  'WP_002378012.1',
  'WP_197718008.1',
  'WP_004156059.1',
  'WP_000171970.1',
  'WP_001711193.1',
  'WP_003422607.1',
  'WP_003734551.1',
  'WP_001068338.1',
  'WP_071959651.1',
  'WP_014608149.1',
  'WP_011257518.1',
  'WP_023317463.1',
  'WP_000469831.1',
  'WP_017627986.1',
  'WP_023317460.1',
  'WP_023317457.1',
  'WP_023317456.1',
  'WP_023313538.1',
  'WP_014608150.1',
  'WP_001144731.1',
  'WP_158003452.1',
  'WP_000447781.1',
  'WP_040147678.1',
  'WP_040147680.1',
  'WP_000447782.1',
  'WP_040147676.1',
  'WP_001084113.1',
  'WP_005686774.1',
  'WP_031488317.1',
  'WP_031488518.1',
  'WP_040222467.1',
  'WP_162836934.1',
  'WP_064152120.1',
  'WP_023317461.1',
  'WP_031601176.1',
  'WP_001129548.1',
  'WP_011409186.1',
  'WP_020750495.1',
  'WP_000819026.1',
  'WP_023092930.1',
  'WP_023157773.1',
  'WP_023157771.1',
  'WP_020824268.1',
  'WP_010793036.1',
  'WP_020831153.1',
  'WP_224557713.1',
  'WP_050164902.1',
  'WP_041421443.1',
  'WP_161994025.1',
  'WP_040182250.1',
  'WP_002378009.1',
  'WP_002378852.1',
  'WP_224557717.1',
  'WP_224557718.1',
  'WP_002867064.1',
  'WP_101237090.1',
  'WP_101237089.1',
  'WP_000981121.1',
  'WP_229023896.1',
  'WP_033881505.1',
  'WP_157742853.1',
  'WP_012118876.1',
  'WP_001987701.1',
  'WP_046026264.1',
  'WP_000209422.1',
  'WP_009928196.1',
  'WP_000469819.1',
  'WP_014484097.1',
  'WP_014483362.1',
  'WP_001836567.1',
  'WP_230864114.1',
  'WP_230864112.1',
  'WP_031697658.1',
  'WP_001180889.1',
  'WP_000345320.1',
  'WP_192188808.1',
  'WP_031488318.1',
  'WP_001136879.1',
  'WP_107317317.1',
  'WP_048994042.1',
  'WP_023157769.1',
  'WP_029182927.1',
  'WP_072094655.1',
  'WP_102734924.1',
  'WP_021535603.1',
  'WP_000368660.1',
  'WP_001033638.1',
  'WP_014480487.1',
  'WP_015729769.1',
  'WP_192188663.1',
  'WP_002348758.1',
  'WP_022196947.1',
  'WP_001019641.1',
  'WP_000357145.1',
  'WP_009996237.1',
  'WP_192188656.1',
  'WP_192188655.1',
  'WP_001251763.1',
  'WP_192188567.1',
  'WP_192188503.1',
  'WP_162855567.1',
  'WP_048946584.1',
  'WP_192188465.1',
  'WP_059245788.1',
  'WP_000040320.1',
  'WP_017418302.1',
  'WP_032608431.1',
  'WP_011409185.1',
  'WP_000065488.1',
  'WP_032460799.1',
  'WP_000427131.1',
  'WP_237025426.1',
  'WP_226060773.1',
  'WP_003904761.1',
  'WP_012117017.1',
  'WP_012094491.1',
  'WP_000580210.1',
  'WP_014608286.1',
  'WP_020863093.1',
  'WP_225315236.1',
  'WP_229020950.1',
  'WP_002935598.1',
  'WP_003158585.1',
  'WP_003158575.1',
  'WP_012094493.1',
  'WP_000040321.1',
  'WP_001894910.1',
  'WP_229031336.1',
  'WP_077907258.1',
  'WP_172825117.1',
  'WP_001044652.1',
  'WP_039282029.1',
  'WP_005134924.1',
  'WP_021535605.1',
  'WP_016239773.1',
  'WP_102734577.1',
  'WP_003036324.1',
  'WP_024104722.1',
  'WP_048994043.1',
  'WP_024104824.1',
  'WP_024104825.1',
  'WP_094139127.1',
  'WP_024104822.1',
  'WP_102734925.1',
  'WP_002950323.1',
  'WP_023157766.1',
  'WP_005109921.1',
  'WP_002950682.1',
  'WP_128990601.1',
  'WP_024430097.1',
  'WP_000446879.1',
  'WP_010793760.1',
  'WP_000006271.1',
  'WP_071703476.1',
  'WP_169309831.1',
  'WP_000777273.1',
  'WP_088314140.1',
  'WP_032448282.1',
  'WP_107317702.1',
  'WP_012296384.1',
  'WP_032459867.1',
  'WP_156573900.1',
  'WP_032424556.1',
  'WP_000766113.1',
  'WP_000065489.1',
  'WP_031488521.1',
  'WP_021469938.1',
  'WP_089086750.1',
  'WP_002229511.1',
  'WP_009979570.1',
  'WP_075204526.1',
  'WP_080511163.1',
  'WP_009962363.1',
  'WP_180975534.1',
  'WP_002229512.1',
  'WP_089086486.1',
  'WP_013447111.1',
  'WP_104731855.1',
  'WP_016212366.1',
  'WP_061092613.1',
  'WP_000337109.1',
  'WP_001018786.1',
  'WP_011861558.1',
  'WP_011861557.1',
  'WP_096864992.1',
  'WP_008807102.1',
  'WP_023302769.1',
  'WP_186808989.1',
  'WP_024108598.1',
  'WP_024108597.1',
  'WP_024108553.1',
  'WP_015438479.1',
  'WP_236787384.1',
  'WP_024108552.1',
  'WP_024108551.1',
  'WP_236787383.1',
  'WP_024108550.1',
  'WP_064125960.1',
  'WP_024108191.1',
  'WP_024108177.1',
  'WP_024108134.1',
  'WP_023302261.1',
  'WP_001223212.1',
  'WP_023302262.1',
  'WP_001046727.1',
  'WP_180971319.1',
  'WP_156667986.1',
  'WP_231102461.1',
  'WP_021314762.1',
  'WP_061301082.1',
  'WP_023550420.1',
  'WP_061301083.1',
  'WP_011272659.1',
  'WP_049525800.1',
  'WP_014228897.1',
  'WP_003584381.1',
  'WP_065757139.1',
  'WP_031488519.1',
  'WP_013910445.1',
  'WP_075294316.1',
  'WP_022554017.1',
  'WP_010793762.1',
  'WP_010793761.1',
  'WP_129556480.1',
  'WP_219327075.1',
  'WP_075293458.1',
  'WP_014300533.1',
  'WP_102734061.1',
  'WP_236945344.1',
  'WP_048994040.1',
  'WP_010906580.1',
  'WP_001029743.1',
  'WP_001097549.1',
  'WP_000062284.1',
  'WP_069964578.1',
  'WP_232483738.1',
  'WP_000080845.1',
  'WP_147363570.1',
  'WP_062923441.1',
  'WP_005753654.1',
  'WP_229016561.1',
  'WP_147363575.1',
  'WP_088351336.1',
  'WP_021548591.1',
  'WP_011285646.1',
  'WP_000916889.1',
  'WP_235659509.1',
  'WP_000860009.1',
  'WP_226347323.1',
  'WP_014601266.1',
  'WP_034100130.1',
  'WP_071703486.1',
  'WP_004918085.1',
  'WP_223255056.1',
  'WP_002250238.1',
  'WP_002229287.1',
  'WP_000026162.1',
  'WP_000435028.1',
  'WP_001080631.1',
  'WP_049120017.1',
  'WP_001083255.1',
  'WP_009988403.1',
  'WP_027821587.1',
  'WP_012951699.1',
  'WP_012951698.1',
  'WP_001670222.1',
  'WP_023157768.1',
  'WP_002780989.1',
  'WP_053810728.1',
  'WP_024108685.1',
  'WP_024108974.1',
  'WP_236787596.1',
  'WP_047052567.1',
  'WP_029384585.1',
  'WP_024108975.1',
  'WP_023157774.1',
  'WP_000853368.1',
  'WP_046436568.1',
  'WP_024704119.1',
  'WP_000342496.1',
  'WP_231405987.1',
  'WP_014635616.1',
  'WP_001223207.1',
  'WP_000105407.1',
  'WP_085569942.1',
  'WP_003439781.1',
  'WP_000029336.1',
  'WP_040104419.1',
  'WP_061405936.1',
  'WP_061405933.1',
  'WP_061535633.1',
  'WP_023226816.1',
  'WP_076983447.1',
  'WP_023193101.1',
  'WP_040236935.1',
  'WP_064138164.1',
  'WP_023301563.1',
  'WP_000168568.1',
  'WP_027821350.1',
  'WP_027228133.1',
  'WP_004250449.1',
  'WP_064661102.1',
  'WP_009996724.1',
  'WP_060415572.1',
  'WP_234003769.1',
  'WP_004297851.1',
  'WP_002854304.1',
  'WP_002854318.1',
  'WP_014367523.1',
  'WP_032676599.1',
  'WP_010923377.1',
  'WP_002320757.1',
  'WP_064151720.1',
  'WP_060565276.1',
  'WP_089046459.1',
  'WP_031488711.1',
  'WP_031488710.1',
  'WP_031488517.1',
  'WP_060556841.1',
  'WP_060556840.1',
  'WP_236787140.1',
  'WP_099745325.1',
  'WP_032460891.1',
  'WP_010922513.1',
  'WP_000064451.1',
  'WP_223200550.1',
  'WP_002365303.1',
  'WP_000175354.1',
  'WP_236787381.1',
  'WP_032425512.1',
  'WP_000058885.1',
  'WP_012094490.1',
  'WP_033547770.1',
  'WP_003036334.1',
  'WP_037543195.1',
  'WP_094374045.1',
  'WP_000254731.1',
  'WP_001407279.1',
  'WP_001399745.1',
  'WP_011681113.1',
  'WP_004739688.1',
  'WP_003151440.1',
  'WP_003691297.1',
  'WP_003139228.1',
  'WP_011681111.1',
  'WP_003319726.1',
  'WP_003036330.1',
  'WP_223343766.1',
  'WP_012027386.1',
  'WP_059332346.1',
  'WP_229223219.1',
  'WP_128971749.1',
  'WP_229505539.1',
  'WP_024704120.1',
  'WP_059110995.1',
  'WP_059110994.1',
  'WP_001570652.1',
  'WP_001586614.1',
  'WP_112923079.1',
  'WP_047052566.1',
  'WP_047052344.1',
  'WP_003740299.1',
  'WP_047052342.1',
  'WP_001621109.1',
  'WP_014602882.1',
  'WP_000893102.1',
  'WP_072157211.1',
  'WP_001084103.1',
  'WP_231573530.1',
  'WP_000985714.1',
  'WP_005722692.1',
  'WP_103415730.1',
  'WP_050489294.1',
  'WP_001019638.1',
  'WP_001050399.1',
  'WP_020945768.1',
  'WP_005109923.1',
  'WP_016239398.1',
  'WP_001080634.1',
  'WP_004918207.1',
  'WP_050484125.1',
  'WP_019843018.1',
  'WP_103415798.1',
  'WP_103415840.1',
  'WP_103415865.1',
  'WP_148237948.1',
  'WP_103415742.1',
  'WP_103415973.1',
  'WP_000383117.1',
  'WP_022065798.1',
  'WP_103415839.1',
  'WP_014498023.1',
  'WP_014498022.1',
  'WP_016534561.1',
  'WP_001233967.1',
  'WP_041850728.1',
  'WP_228722646.1',
  'WP_016534564.1',
  'WP_099745326.1',
  'WP_048488836.1',
  'WP_032415895.1',
  'WP_012311912.1',
  'WP_236493375.1',
  'WP_039268593.1',
  'WP_004082345.1',
  'WP_014608136.1',
  'WP_004082344.1',
  'WP_001357996.1',
  'WP_012813213.1',
  'WP_119196702.1',
  'WP_231837864.1',
  'WP_119196703.1',
  'WP_023337662.1',
  'WP_014484098.1',
  'WP_001003363.1',
  'WP_014608282.1',
  'WP_002878198.1',
  'WP_001704287.1',
  'WP_225319242.1',
  'WP_032868090.1',
  'WP_046559974.1',
  'WP_023302441.1',
  'WP_000558149.1',
  'WP_023302442.1',
  'WP_225319243.1',
  'WP_024477883.1',
  'WP_225368539.1',
  'WP_014835680.1',
  'WP_004739679.1',
  'WP_004739683.1',
  'WP_023302443.1',
  'WP_000281457.1',
  'WP_080288371.1',
  'WP_048653242.1',
  'WP_024901007.1',
  'WP_003955338.1',
  'WP_043118638.1',
  'WP_024199421.1',
  'WP_023280428.1',
  'WP_043118640.1',
  'WP_042593615.1',
  'WP_042593613.1',
  'WP_016263850.1',
  'WP_001586613.1',
  'WP_042593612.1',
  'WP_000934358.1',
  'WP_032608405.1',
  'WP_032608399.1',
  'WP_014837241.1',
  'WP_001586615.1',
  'WP_232518734.1',
  'WP_000555091.1',
  'WP_224517554.1',
  'WP_017694611.1',
  'WP_014326279.1',
  'WP_048946567.1',
  'WP_047052340.1',
  'WP_000281401.1',
  'WP_058654869.1',
  'WP_032634496.1',
  'WP_000286996.1',
  'WP_000433153.1',
  'WP_032595884.1',
  'WP_119196699.1',
  'WP_128836354.1',
  'WP_031488516.1',
  'WP_000105684.1',
  'WP_088428977.1',
  'WP_021137775.1',
  'WP_000063173.1',
  'WP_002385122.1',
  'WP_027228129.1',
  'WP_223861284.1',
  'WP_094304446.1',
  'WP_005499652.1',
  'WP_000101224.1',
  'WP_026042305.1',
  'WP_016349791.1',
  'WP_000344096.1',
  'WP_127913991.1',
  'WP_127897268.1',
  'WP_088360587.1',
  'WP_031488712.1',
  'WP_005499650.1',
  'WP_016351278.1',
  'WP_002989036.1',
  'WP_227889159.1',
  'WP_048215043.1',
  'WP_049525803.1',
  'WP_000861932.1',
  'WP_180819948.1',
  'WP_180819949.1',
  'WP_180820009.1',
  'WP_198351453.1',
  'WP_027821586.1',
  'WP_086046991.1',
  'WP_016349787.1',
  'WP_061405934.1',
  'WP_024085992.1',
  'WP_013724047.1',
  'WP_000144879.1',
  'WP_020862866.1',
  'WP_016349785.1',

### Currently there is a limit of 100,000 IDs per API request so we're going to break this down

#### Submit job for batch 1

In [4]:
no_uniprot_acc_list_batch1=no_uniprot_acc_list[:100000]
len(no_uniprot_acc_list_batch1)

100000

In [5]:
print(no_uniprot_acc_list_batch1)

['WP_001372321.1', 'WP_096937776.1', 'WP_003917092.1', 'WP_001381369.1', 'WP_020277900.1', 'WP_000357807.1', 'WP_159376494.1', 'WP_001443175.1', 'WP_223178619.1', 'WP_000880885.1', 'WP_000571783.1', 'WP_000937120.1', 'WP_000061856.1', 'WP_000777275.1', 'WP_010922512.1', 'WP_001323520.1', 'WP_001084115.1', 'WP_167876495.1', 'WP_000960581.1', 'WP_071532149.1', 'WP_168876894.1', 'WP_006250003.1', 'WP_000433154.1', 'WP_004195968.1', 'WP_032433805.1', 'WP_032433488.1', 'WP_000562556.1', 'WP_009308509.1', 'WP_004178703.1', 'WP_004178705.1', 'WP_019842341.1', 'WP_004178700.1', 'WP_000101606.1', 'WP_000443455.1', 'WP_003689382.1', 'WP_223349259.1', 'WP_001356249.1', 'WP_001425460.1', 'WP_223340727.1', 'WP_001096907.1', 'WP_002220782.1', 'WP_000063179.1', 'WP_032875608.1', 'WP_000020778.1', 'WP_012503916.1', 'WP_003907189.1', 'WP_001104341.1', 'WP_012602456.1', 'WP_000192872.1', 'WP_005014373.1', 'WP_012503917.1', 'WP_001521154.1', 'WP_023283164.1', 'WP_022630855.1', 'WP_000063170.1', 'WP_080229150.1', 'WP_002224275.1', 'WP_001678529.1', 'WP_000385105.1', 'WP_002934299.1', 'WP_000915483.1', 'WP_016187290.1', 'WP_002989949.1', 'WP_002242331.1', 'WP_002932805.1', 'WP_021575209.1', 'WP_015059139.1', 'WP_032875349.1', 'WP_032875605.1', 'WP_003694912.1', 'WP_006248462.1', 'WP_227746616.1', 'WP_006250671.1', 'WP_022649084.1', 'WP_006250672.1', 'WP_002211866.1', 'WP_001041189.1', 'WP_032415893.1', 'WP_023982161.1', 'WP_000108736.1', 'WP_012737279.1', 'WP_012737253.1', 'WP_004180290.1', 'WP_224553826.1', 'WP_017146687.1', 'WP_224553828.1', 'WP_012737314.1', 'WP_224557923.1', 'WP_000150995.1', 'WP_003691372.1', 'WP_001352286.1', 'WP_022648718.1', 'WP_224557853.1', 'WP_224557855.1', 'WP_114276004.1', 'WP_012446057.1', 'WP_006250674.1', 'WP_227746614.1', 'WP_001593930.1', 'WP_032433950.1', 'WP_013242856.1', 'WP_001521911.1', 'WP_071562429.1', 'WP_021312557.1', 'WP_100067201.1', 'WP_223349791.1', 'WP_032416923.1', 'WP_012737310.1', 'WP_012737312.1', 'WP_223716397.1', 'WP_006250670.1', 'WP_000110087.1', 'WP_001101565.1', 'WP_012737252.1', 'WP_002946668.1', 'WP_020824140.1', 'WP_000187069.1', 'WP_002982804.1', 'WP_023330142.1', 'WP_002211867.1', 'WP_011285159.1', 'WP_223225479.1', 'WP_014325846.1', 'WP_022652238.1', 'WP_032418879.1', 'WP_000889014.1', 'WP_015444231.1', 'WP_123836165.1', 'WP_123618666.1', 'WP_071959649.1', 'WP_223814687.1', 'WP_004521208.1', 'WP_000012516.1', 'WP_223156217.1', 'WP_000584997.1', 'WP_229020258.1', 'WP_014326283.1', 'WP_014326282.1', 'WP_014325848.1', 'WP_011284745.1', 'WP_094136088.1', 'WP_001551050.1', 'WP_011285158.1', 'WP_196529333.1', 'WP_016211530.1', 'WP_032418443.1', 'WP_032418188.1', 'WP_032414549.1', 'WP_078055966.1', 'WP_020824151.1', 'WP_197736718.1', 'WP_196547718.1', 'WP_017627993.1', 'WP_102734060.1', 'WP_015484256.1', 'WP_015484257.1', 'WP_172621306.1', 'WP_032418459.1', 'WP_001325828.1', 'WP_014326278.1', 'WP_000739990.1', 'WP_229001947.1', 'WP_042465377.1', 'WP_001376998.1', 'WP_002222491.1', 'WP_000599828.1', 'WP_011407754.1', 'WP_199285672.1', 'WP_002211868.1', 'WP_000062282.1', 'WP_010922510.1', 'WP_142778025.1', 'WP_000168559.1', 'WP_000281434.1', 'WP_017154976.1', 'WP_023303963.1', 'WP_004222271.1', 'WP_001223964.1', 'WP_004343803.1', 'WP_000447780.1', 'WP_001375150.1', 'WP_071836746.1', 'WP_011225936.1', 'WP_002321314.1', 'WP_053513661.1', 'WP_227985893.1', 'WP_002321313.1', 'WP_024745666.1', 'WP_000132365.1', 'WP_003488925.1', 'WP_011284986.1', 'WP_033003220.1', 'WP_001513536.1', 'WP_003105626.1', 'WP_000829994.1', 'WP_024744457.1', 'WP_024744456.1', 'WP_002340336.1', 'WP_002344971.1', 'WP_024745594.1', 'WP_014522909.1', 'WP_223176087.1', 'WP_223293117.1', 'WP_033004264.1', 'WP_032647082.1', 'WP_001514500.1', 'WP_015463226.1', 'WP_001513535.1', 'WP_032408834.1', 'WP_011409831.1', 'WP_053513660.1', 'WP_237025418.1', 'WP_223175346.1', 'WP_206640390.1', 'WP_227944641.1', 'WP_032408833.1', 'WP_223251341.1', 'WP_231139811.1', 'WP_033638854.1', 'WP_032414116.1', 'WP_032414117.1', 'WP_010922509.1', 'WP_064162471.1', 'WP_022646034.1', 'WP_042919266.1', 'WP_223293119.1', 'WP_002210191.1', 'WP_230374854.1', 'WP_016504384.1', 'WP_024744455.1', 'WP_015376197.1', 'WP_003422618.1', 'WP_230937716.1', 'WP_003422619.1', 'WP_003422610.1', 'WP_064162472.1', 'WP_032414115.1', 'WP_053067569.1', 'WP_003422614.1', 'WP_023302105.1', 'WP_077681940.1', 'WP_015444645.1', 'WP_071534647.1', 'WP_000469823.1', 'WP_233145404.1', 'WP_001193075.1', 'WP_001207938.1', 'WP_011409829.1', 'WP_014326450.1', 'WP_001398805.1', 'WP_009906182.1', 'WP_237025420.1', 'WP_062826779.1', 'WP_025458713.1', 'WP_001114356.1', 'WP_011528583.1', 'WP_003159837.1', 'WP_078072093.1', 'WP_005927106.1', 'WP_023909157.1', 'WP_023343022.1', 'WP_077907039.1', 'WP_000383016.1', 'WP_039023230.1', 'WP_230078415.1', 'WP_001090220.1', 'WP_000447773.1', 'WP_003424503.1', 'WP_041181951.1', 'WP_003424506.1', 'WP_015379640.1', 'WP_002221142.1', 'WP_003424499.1', 'WP_000433147.1', 'WP_000887497.1', 'WP_235658924.1', 'WP_000229085.1', 'WP_000469832.1', 'WP_036781349.1', 'WP_050885114.1', 'WP_000915960.1', 'WP_011407656.1', 'WP_015484771.1', 'WP_125168758.1', 'WP_223235436.1', 'WP_001379612.1', 'WP_032440985.1', 'WP_053513436.1', 'WP_011921992.1', 'WP_021359714.1', 'WP_152687277.1', 'WP_001024666.1', 'WP_016504385.1', 'WP_010729551.1', 'WP_000427097.1', 'WP_000788537.1', 'WP_012027389.1', 'WP_050885115.1', 'WP_188348580.1', 'WP_000790512.1', 'WP_000806084.1', 'WP_000548124.1', 'WP_000428596.1', 'WP_001297700.1', 'WP_041182275.1', 'WP_229687174.1', 'WP_023302104.1', 'WP_023301568.1', 'WP_001988174.1', 'WP_040174621.1', 'WP_001193928.1', 'WP_000613299.1', 'WP_000602661.1', 'WP_015484058.1', 'WP_015484059.1', 'WP_102734057.1', 'WP_014326158.1', 'WP_229940495.1', 'WP_023341070.1', 'WP_023325100.1', 'WP_000094925.1', 'WP_000278666.1', 'WP_001170530.1', 'WP_001154483.1', 'WP_000362741.1', 'WP_000050006.1', 'WP_088607455.1', 'WP_022615726.1', 'WP_000558913.1', 'WP_011579220.1', 'WP_000996748.1', 'WP_000693661.1', 'WP_004348746.1', 'WP_000386439.1', 'WP_000724528.1', 'WP_001006082.1', 'WP_000258887.1', 'WP_001139750.1', 'WP_044383147.1', 'WP_000346715.1', 'WP_001129183.1', 'WP_000735207.1', 'WP_053320758.1', 'WP_006250001.1', 'WP_017628493.1', 'WP_000756058.1', 'WP_102741079.1', 'WP_001447084.1', 'WP_014608283.1', 'WP_050598711.1', 'WP_023317235.1', 'WP_202976311.1', 'WP_094139126.1', 'WP_000254493.1', 'WP_223364258.1', 'WP_011109507.1', 'WP_001201808.1', 'WP_001147690.1', 'WP_002946669.1', 'WP_224557857.1', 'WP_002882659.1', 'WP_251266265.1', 'WP_015240924.1', 'WP_001987716.1', 'WP_001129176.1', 'WP_022196948.1', 'WP_049254555.1', 'WP_020862545.1', 'WP_000824288.1', 'WP_049253269.1', 'WP_047351814.1', 'WP_044383143.1', 'WP_017627989.1', 'WP_147810693.1', 'WP_029505552.1', 'WP_017627991.1', 'WP_053320759.1', 'WP_017283224.1', 'WP_002989041.1', 'WP_072652752.1', 'WP_022645928.1', 'WP_023316685.1', 'WP_230453483.1', 'WP_010922252.1', 'WP_002229413.1', 'WP_229001945.1', 'WP_200866217.1', 'WP_004348749.1', 'WP_012952176.1', 'WP_197665280.1', 'WP_000040318.1', 'WP_000022533.1', 'WP_000392522.1', 'WP_000251225.1', 'WP_202557271.1', 'WP_014635701.1', 'WP_014608135.1', 'WP_001297331.1', 'WP_010922657.1', 'WP_223201512.1', 'WP_004555439.1', 'WP_224230667.1', 'WP_000931915.1', 'WP_048994039.1', 'WP_010922656.1', 'WP_000136607.1', 'WP_038270864.1', 'WP_014608284.1', 'WP_001513100.1', 'WP_102733860.1', 'WP_102733859.1', 'WP_000006268.1', 'WP_001442952.1', 'WP_085962535.1', 'WP_001357997.1', 'WP_230428187.1', 'WP_074193709.1', 'WP_001519853.1', 'WP_000880882.1', 'WP_000041884.1', 'WP_047951660.1', 'WP_012816355.1', 'WP_017627987.1', 'WP_000312400.1', 'WP_017628125.1', 'WP_011285506.1', 'WP_004155177.1', 'WP_000186145.1', 'WP_016922464.1', 'WP_016504218.1', 'WP_040181140.1', 'WP_009891261.1', 'WP_009890657.1', 'WP_004155179.1', 'WP_011408818.1', 'WP_000390795.1', 'WP_009349902.1', 'WP_020862963.1', 'WP_124072201.1', 'WP_001095581.1', 'WP_024431614.1', 'WP_004159620.1', 'WP_004159622.1', 'WP_004159607.1', 'WP_004159615.1', 'WP_004159618.1', 'WP_004159610.1', 'WP_004159604.1', 'WP_004159613.1', 'WP_000632676.1', 'WP_014490283.1', 'WP_009891270.1', 'WP_002856642.1', 'WP_000968685.1', 'WP_062627966.1', 'WP_001598204.1', 'WP_004545288.1', 'WP_009891533.1', 'WP_001594372.1', 'WP_009891534.1', 'WP_009891263.1', 'WP_000251226.1', 'WP_009893753.1', 'WP_016211321.1', 'WP_003162915.1', 'WP_015647862.1', 'WP_010922655.1', 'WP_000200813.1', 'WP_072161528.1', 'WP_048993388.1', 'WP_002378777.1', 'WP_002378778.1', 'WP_251266343.1', 'WP_001233958.1', 'WP_197723474.1', 'WP_010733696.1', 'WP_002807242.1', 'WP_000880884.1', 'WP_004155178.1', 'WP_002245104.1', 'WP_016487840.1', 'WP_065213378.1', 'WP_227522504.1', 'WP_000190898.1', 'WP_065213379.1', 'WP_002401675.1', 'WP_031488520.1', 'WP_004155171.1', 'WP_004155172.1', 'WP_020862964.1', 'WP_000424707.1', 'WP_032740191.1', 'WP_000394003.1', 'WP_223195031.1', 'WP_004155173.1', 'WP_004222275.1', 'WP_002378012.1', 'WP_197718008.1', 'WP_004156059.1', 'WP_000171970.1', 'WP_001711193.1', 'WP_003422607.1', 'WP_003734551.1', 'WP_001068338.1', 'WP_071959651.1', 'WP_014608149.1', 'WP_011257518.1', 'WP_023317463.1', 'WP_000469831.1', 'WP_017627986.1', 'WP_023317460.1', 'WP_023317457.1', 'WP_023317456.1', 'WP_023313538.1', 'WP_014608150.1', 'WP_001144731.1', 'WP_158003452.1', 'WP_000447781.1', 'WP_040147678.1', 'WP_040147680.1', 'WP_000447782.1', 'WP_040147676.1', 'WP_001084113.1', 'WP_005686774.1', 'WP_031488317.1', 'WP_031488518.1', 'WP_040222467.1', 'WP_162836934.1', 'WP_064152120.1', 'WP_023317461.1', 'WP_031601176.1', 'WP_001129548.1', 'WP_011409186.1', 'WP_020750495.1', 'WP_000819026.1', 'WP_023092930.1', 'WP_023157773.1', 'WP_023157771.1', 'WP_020824268.1', 'WP_010793036.1', 'WP_020831153.1', 'WP_224557713.1', 'WP_050164902.1', 'WP_041421443.1', 'WP_161994025.1', 'WP_040182250.1', 'WP_002378009.1', 'WP_002378852.1', 'WP_224557717.1', 'WP_224557718.1', 'WP_002867064.1', 'WP_101237090.1', 'WP_101237089.1', 'WP_000981121.1', 'WP_229023896.1', 'WP_033881505.1', 'WP_157742853.1', 'WP_012118876.1', 'WP_001987701.1', 'WP_046026264.1', 'WP_000209422.1', 'WP_009928196.1', 'WP_000469819.1', 'WP_014484097.1', 'WP_014483362.1', 'WP_001836567.1', 'WP_230864114.1', 'WP_230864112.1', 'WP_031697658.1', 'WP_001180889.1', 'WP_000345320.1', 'WP_192188808.1', 'WP_031488318.1', 'WP_001136879.1', 'WP_107317317.1', 'WP_048994042.1', 'WP_023157769.1', 'WP_029182927.1', 'WP_072094655.1', 'WP_102734924.1', 'WP_021535603.1', 'WP_000368660.1', 'WP_001033638.1', 'WP_014480487.1', 'WP_015729769.1', 'WP_192188663.1', 'WP_002348758.1', 'WP_022196947.1', 'WP_001019641.1', 'WP_000357145.1', 'WP_009996237.1', 'WP_192188656.1', 'WP_192188655.1', 'WP_001251763.1', 'WP_192188567.1', 'WP_192188503.1', 'WP_162855567.1', 'WP_048946584.1', 'WP_192188465.1', 'WP_059245788.1', 'WP_000040320.1', 'WP_017418302.1', 'WP_032608431.1', 'WP_011409185.1', 'WP_000065488.1', 'WP_032460799.1', 'WP_000427131.1', 'WP_237025426.1', 'WP_226060773.1', 'WP_003904761.1', 'WP_012117017.1', 'WP_012094491.1', 'WP_000580210.1', 'WP_014608286.1', 'WP_020863093.1', 'WP_225315236.1', 'WP_229020950.1', 'WP_002935598.1', 'WP_003158585.1', 'WP_003158575.1', 'WP_012094493.1', 'WP_000040321.1', 'WP_001894910.1', 'WP_229031336.1', 'WP_077907258.1', 'WP_172825117.1', 'WP_001044652.1', 'WP_039282029.1', 'WP_005134924.1', 'WP_021535605.1', 'WP_016239773.1', 'WP_102734577.1', 'WP_003036324.1', 'WP_024104722.1', 'WP_048994043.1', 'WP_024104824.1', 'WP_024104825.1', 'WP_094139127.1', 'WP_024104822.1', 'WP_102734925.1', 'WP_002950323.1', 'WP_023157766.1', 'WP_005109921.1', 'WP_002950682.1', 'WP_128990601.1', 'WP_024430097.1', 'WP_000446879.1', 'WP_010793760.1', 'WP_000006271.1', 'WP_071703476.1', 'WP_169309831.1', 'WP_000777273.1', 'WP_088314140.1', 'WP_032448282.1', 'WP_107317702.1', 'WP_012296384.1', 'WP_032459867.1', 'WP_156573900.1', 'WP_032424556.1', 'WP_000766113.1', 'WP_000065489.1', 'WP_031488521.1', 'WP_021469938.1', 'WP_089086750.1', 'WP_002229511.1', 'WP_009979570.1', 'WP_075204526.1', 'WP_080511163.1', 'WP_009962363.1', 'WP_180975534.1', 'WP_002229512.1', 'WP_089086486.1', 'WP_013447111.1', 'WP_104731855.1', 'WP_016212366.1', 'WP_061092613.1', 'WP_000337109.1', 'WP_001018786.1', 'WP_011861558.1', 'WP_011861557.1', 'WP_096864992.1', 'WP_008807102.1', 'WP_023302769.1', 'WP_186808989.1', 'WP_024108598.1', 'WP_024108597.1', 'WP_024108553.1', 'WP_015438479.1', 'WP_236787384.1', 'WP_024108552.1', 'WP_024108551.1', 'WP_236787383.1', 'WP_024108550.1', 'WP_064125960.1', 'WP_024108191.1', 'WP_024108177.1', 'WP_024108134.1', 'WP_023302261.1', 'WP_001223212.1', 'WP_023302262.1', 'WP_001046727.1', 'WP_180971319.1', 'WP_156667986.1', 'WP_231102461.1', 'WP_021314762.1', 'WP_061301082.1', 'WP_023550420.1', 'WP_061301083.1', 'WP_011272659.1', 'WP_049525800.1', 'WP_014228897.1', 'WP_003584381.1', 'WP_065757139.1', 'WP_031488519.1', 'WP_013910445.1', 'WP_075294316.1', 'WP_022554017.1', 'WP_010793762.1', 'WP_010793761.1', 'WP_129556480.1', 'WP_219327075.1', 'WP_075293458.1', 'WP_014300533.1', 'WP_102734061.1', 'WP_236945344.1', 'WP_048994040.1', 'WP_010906580.1', 'WP_001029743.1', 'WP_001097549.1', 'WP_000062284.1', 'WP_069964578.1', 'WP_232483738.1', 'WP_000080845.1', 'WP_147363570.1', 'WP_062923441.1', 'WP_005753654.1', 'WP_229016561.1', 'WP_147363575.1', 'WP_088351336.1', 'WP_021548591.1', 'WP_011285646.1', 'WP_000916889.1', 'WP_235659509.1', 'WP_000860009.1', 'WP_226347323.1', 'WP_014601266.1', 'WP_034100130.1', 'WP_071703486.1', 'WP_004918085.1', 'WP_223255056.1', 'WP_002250238.1', 'WP_002229287.1', 'WP_000026162.1', 'WP_000435028.1', 'WP_001080631.1', 'WP_049120017.1', 'WP_001083255.1', 'WP_009988403.1', 'WP_027821587.1', 'WP_012951699.1', 'WP_012951698.1', 'WP_001670222.1', 'WP_023157768.1', 'WP_002780989.1', 'WP_053810728.1', 'WP_024108685.1', 'WP_024108974.1', 'WP_236787596.1', 'WP_047052567.1', 'WP_029384585.1', 'WP_024108975.1', 'WP_023157774.1', 'WP_000853368.1', 'WP_046436568.1', 'WP_024704119.1', 'WP_000342496.1', 'WP_231405987.1', 'WP_014635616.1', 'WP_001223207.1', 'WP_000105407.1', 'WP_085569942.1', 'WP_003439781.1', 'WP_000029336.1', 'WP_040104419.1', 'WP_061405936.1', 'WP_061405933.1', 'WP_061535633.1', 'WP_023226816.1', 'WP_076983447.1', 'WP_023193101.1', 'WP_040236935.1', 'WP_064138164.1', 'WP_023301563.1', 'WP_000168568.1', 'WP_027821350.1', 'WP_027228133.1', 'WP_004250449.1', 'WP_064661102.1', 'WP_009996724.1', 'WP_060415572.1', 'WP_234003769.1', 'WP_004297851.1', 'WP_002854304.1', 'WP_002854318.1', 'WP_014367523.1', 'WP_032676599.1', 'WP_010923377.1', 'WP_002320757.1', 'WP_064151720.1', 'WP_060565276.1', 'WP_089046459.1', 'WP_031488711.1', 'WP_031488710.1', 'WP_031488517.1', 'WP_060556841.1', 'WP_060556840.1', 'WP_236787140.1', 'WP_099745325.1', 'WP_032460891.1', 'WP_010922513.1', 'WP_000064451.1', 'WP_223200550.1', 'WP_002365303.1', 'WP_000175354.1', 'WP_236787381.1', 'WP_032425512.1', 'WP_000058885.1', 'WP_012094490.1', 'WP_033547770.1', 'WP_003036334.1', 'WP_037543195.1', 'WP_094374045.1', 'WP_000254731.1', 'WP_001407279.1', 'WP_001399745.1', 'WP_011681113.1', 'WP_004739688.1', 'WP_003151440.1', 'WP_003691297.1', 'WP_003139228.1', 'WP_011681111.1', 'WP_003319726.1', 'WP_003036330.1', 'WP_223343766.1', 'WP_012027386.1', 'WP_059332346.1', 'WP_229223219.1', 'WP_128971749.1', 'WP_229505539.1', 'WP_024704120.1', 'WP_059110995.1', 'WP_059110994.1', 'WP_001570652.1', 'WP_001586614.1', 'WP_112923079.1', 'WP_047052566.1', 'WP_047052344.1', 'WP_003740299.1', 'WP_047052342.1', 'WP_001621109.1', 'WP_014602882.1', 'WP_000893102.1', 'WP_072157211.1', 'WP_001084103.1', 'WP_231573530.1', 'WP_000985714.1', 'WP_005722692.1', 'WP_103415730.1', 'WP_050489294.1', 'WP_001019638.1', 'WP_001050399.1', 'WP_020945768.1', 'WP_005109923.1', 'WP_016239398.1', 'WP_001080634.1', 'WP_004918207.1', 'WP_050484125.1', 'WP_019843018.1', 'WP_103415798.1', 'WP_103415840.1', 'WP_103415865.1', 'WP_148237948.1', 'WP_103415742.1', 'WP_103415973.1', 'WP_000383117.1', 'WP_022065798.1', 'WP_103415839.1', 'WP_014498023.1', 'WP_014498022.1', 'WP_016534561.1', 'WP_001233967.1', 'WP_041850728.1', 'WP_228722646.1', 'WP_016534564.1', 'WP_099745326.1', 'WP_048488836.1', 'WP_032415895.1', 'WP_012311912.1', 'WP_236493375.1', 'WP_039268593.1', 'WP_004082345.1', 'WP_014608136.1', 'WP_004082344.1', 'WP_001357996.1', 'WP_012813213.1', 'WP_119196702.1', 'WP_231837864.1', 'WP_119196703.1', 'WP_023337662.1', 'WP_014484098.1', 'WP_001003363.1', 'WP_014608282.1', 'WP_002878198.1', 'WP_001704287.1', 'WP_225319242.1', 'WP_032868090.1', 'WP_046559974.1', 'WP_023302441.1', 'WP_000558149.1', 'WP_023302442.1', 'WP_225319243.1', 'WP_024477883.1', 'WP_225368539.1', 'WP_014835680.1', 'WP_004739679.1', 'WP_004739683.1', 'WP_023302443.1', 'WP_000281457.1', 'WP_080288371.1', 'WP_048653242.1', 'WP_024901007.1', 'WP_003955338.1', 'WP_043118638.1', 'WP_024199421.1', 'WP_023280428.1', 'WP_043118640.1', 'WP_042593615.1', 'WP_042593613.1', 'WP_016263850.1', 'WP_001586613.1', 'WP_042593612.1', 'WP_000934358.1', 'WP_032608405.1', 'WP_032608399.1', 'WP_014837241.1', 'WP_001586615.1', 'WP_232518734.1', 'WP_000555091.1', 'WP_224517554.1', 'WP_017694611.1', 'WP_014326279.1', 'WP_048946567.1', 'WP_047052340.1', 'WP_000281401.1', 'WP_058654869.1', 'WP_032634496.1', 'WP_000286996.1', 'WP_000433153.1', 'WP_032595884.1', 'WP_119196699.1', 'WP_128836354.1', 'WP_031488516.1', 'WP_000105684.1', 'WP_088428977.1', 'WP_021137775.1', 'WP_000063173.1', 'WP_002385122.1', 'WP_027228129.1', 'WP_223861284.1', 'WP_094304446.1', 'WP_005499652.1', 'WP_000101224.1', 'WP_026042305.1', 'WP_016349791.1', 'WP_000344096.1', 'WP_127913991.1', 'WP_127897268.1', 'WP_088360587.1', 'WP_031488712.1', 'WP_005499650.1', 'WP_016351278.1', 'WP_002989036.1', 'WP_227889159.1', 'WP_048215043.1', 'WP_049525803.1', 'WP_000861932.1', 'WP_180819948.1', 'WP_180819949.1', 'WP_180820009.1', 'WP_198351453.1', 'WP_027821586.1', 'WP_086046991.1', 'WP_016349787.1', 'WP_061405934.1', 'WP_024085992.1', 'WP_013724047.1', 'WP_000144879.1', 'WP_020862866.1', 'WP_016349785.1', 'WP_023518371.1', 'WP_232051479.1', 'WP_023156030.1', 'WP_236609017.1', 'WP_039570179.1', 'WP_075242182.1', 'WP_014727389.1', 'WP_023149703.1', 'WP_223271244.1', 'WP_002229869.1', 'WP_019486756.1', 'WP_061405932.1', 'WP_019484542.1', 'WP_019484546.1', 'WP_044555027.1', 'WP_016349782.1', 'WP_019484545.1', 'WP_014480488.1', 'WP_019484547.1', 'WP_128153805.1', 'WP_086037960.1', 'WP_128153803.1', 'WP_046947815.1', 'WP_000608706.1', 'WP_002989033.1', 'WP_086037959.1', 'WP_128153804.1', 'WP_001564336.1', 'WP_071556223.1', 'WP_128153802.1', 'WP_162877566.1', 'WP_094031878.1', 'WP_121547626.1', 'WP_000074845.1', 'WP_009308514.1', 'WP_087095029.1', 'WP_223307968.1', 'WP_086046572.1', 'WP_000254732.1', 'WP_024383472.1', 'WP_034448603.1', 'WP_086046550.1', 'WP_047052332.1', 'WP_033547713.1', 'WP_176817301.1', 'WP_005751837.1', 'WP_024085993.1', 'WP_022552863.1', 'WP_000149676.1', 'WP_011014322.1', 'WP_001023266.1', 'WP_001546943.1', 'WP_042465160.1', 'WP_012054518.1', 'WP_042593611.1', 'WP_002988121.1', 'WP_034020197.1', 'WP_223237540.1', 'WP_000085038.1', 'WP_002384923.1', 'WP_002234786.1', 'WP_002234910.1', 'WP_002234912.1', 'WP_016349784.1', 'WP_031586076.1', 'WP_031582170.1', 'WP_016349792.1', 'WP_002260408.1', 'WP_009972612.1', 'WP_014480489.1', 'WP_012754398.1', 'WP_009935580.1', 'WP_060579109.1', 'WP_009935581.1', 'WP_031756783.1', 'WP_031756420.1', 'WP_031690888.1', 'WP_002263546.1', 'WP_026594603.1', 'WP_016350102.1', 'WP_027821588.1', 'WP_228161298.1', 'WP_016350103.1', 'WP_012619752.1', 'WP_004219075.1', 'WP_016350104.1', 'WP_045176823.1', 'WP_004218214.1', 'WP_045176825.1', 'WP_016351272.1', 'WP_132106656.1', 'WP_205596020.1', 'WP_000058875.1', 'WP_009996725.1', 'WP_031299144.1', 'WP_064670493.1', 'WP_045621209.1', 'WP_045621205.1', 'WP_016350101.1', 'WP_021241921.1', 'WP_027228130.1', 'WP_004160031.1', 'WP_064355517.1', 'WP_016351274.1', 'WP_016351273.1', 'WP_064055656.1', 'WP_020002865.1', 'WP_002803980.1', 'WP_001797289.1', 'WP_010946968.1', 'WP_172042057.1', 'WP_032634492.1', '

In [6]:
job_id = submit_id_mapping(
    from_db="RefSeq_Protein", to_db="UniProtKB", ids=no_uniprot_acc_list_batch1
)

In [7]:
print(job_id)

pkqEtDCTyz

#### Submit job for batch 2

In [13]:
no_uniprot_acc_list_batch2=no_uniprot_acc_list[100000:]
len(no_uniprot_acc_list_batch2)

22264

In [14]:
print(no_uniprot_acc_list_batch2)

['WP_120172199.1', 'WP_120173271.1', 'WP_119946308.1', 'WP_119944944.1', 'WP_119944956.1', 'WP_119945366.1', 'WP_119945367.1', 'WP_119945368.1', 'WP_119945425.1', 'WP_119945426.1', 'WP_119945427.1', 'WP_119945665.1', 'WP_119945666.1', 'WP_119945667.1', 'WP_119945833.1', 'WP_119945834.1', 'WP_119946031.1', 'WP_119946034.1', 'WP_119946254.1', 'WP_119946307.1', 'WP_119953980.1', 'WP_119985449.1', 'WP_119980130.1', 'WP_119980122.1', 'WP_114936010.1', 'WP_118663612.1', 'WP_115763930.1', 'WP_115765971.1', 'WP_115765978.1', 'WP_115766712.1', 'WP_115766781.1', 'WP_115766820.1', 'WP_115766867.1', 'WP_115766870.1', 'WP_115766872.1', 'WP_115766873.1', 'WP_115769682.1', 'WP_115770971.1', 'WP_115770972.1', 'WP_115776209.1', 'WP_115776210.1', 'WP_115777727.1', 'WP_115763895.1', 'WP_115780135.1', 'WP_115759545.1', 'WP_115759528.1', 'WP_115725099.1', 'WP_115725103.1', 'WP_115725104.1', 'WP_115725105.1', 'WP_115735561.1', 'WP_115736045.1', 'WP_115737005.1', 'WP_115747009.1', 'WP_115757426.1', 'WP_115759281.1', 'WP_115759543.1', 'WP_115720773.1', 'WP_115780136.1', 'WP_115895355.1', 'WP_115938779.1', 'WP_115969095.1', 'WP_115996191.1', 'WP_116100084.1', 'WP_116100233.1', 'WP_116100234.1', 'WP_116100298.1', 'WP_116100410.1', 'WP_116100411.1', 'WP_116100414.1', 'WP_116100471.1', 'WP_116100473.1', 'WP_116100475.1', 'WP_116100476.1', 'WP_115877126.1', 'WP_115781496.1', 'WP_115875507.1', 'WP_115875503.1', 'WP_115783952.1', 'WP_115786729.1', 'WP_115791372.1', 'WP_115791373.1', 'WP_115791393.1', 'WP_115794467.1', 'WP_115794652.1', 'WP_115801319.1', 'WP_115875505.1', 'WP_116109679.1', 'WP_115719878.1', 'WP_115719509.1', 'WP_115635960.1', 'WP_115635961.1', 'WP_115648594.1', 'WP_115648736.1', 'WP_115650655.1', 'WP_115650661.1', 'WP_115651059.1', 'WP_115633348.1', 'WP_115651063.1', 'WP_115633344.1', 'WP_115633334.1', 'WP_115625931.1', 'WP_115625932.1', 'WP_115632488.1', 'WP_115632489.1', 'WP_115632492.1', 'WP_115632618.1', 'WP_115632772.1', 'WP_115632807.1', 'WP_115632974.1', 'WP_115632976.1', 'WP_115632978.1', 'WP_115633119.1', 'WP_115633332.1', 'WP_115633333.1', 'WP_115633343.1', 'WP_115719510.1', 'WP_115651064.1', 'WP_115652336.1', 'WP_115703438.1', 'WP_115705122.1', 'WP_115717623.1', 'WP_115717624.1', 'WP_115718414.1', 'WP_115718415.1', 'WP_115718416.1', 'WP_115718417.1', 'WP_115719058.1', 'WP_115719504.1', 'WP_115719505.1', 'WP_115719506.1', 'WP_115719507.1', 'WP_115719508.1', 'WP_115702903.1', 'WP_115651864.1', 'WP_115701429.1', 'WP_115671136.1', 'WP_115677024.1', 'WP_115677130.1', 'WP_115701417.1', 'WP_116109680.1', 'WP_116109682.1', 'WP_116110773.1', 'WP_116605324.1', 'WP_116605409.1', 'WP_116605410.1', 'WP_116605411.1', 'WP_116672556.1', 'WP_116787003.1', 'WP_116605323.1', 'WP_116787017.1', 'WP_116605322.1', 'WP_116587163.1', 'WP_116439002.1', 'WP_116439163.1', 'WP_116439847.1', 'WP_116495172.1', 'WP_116506007.1', 'WP_116506009.1', 'WP_116508953.1', 'WP_116510078.1', 'WP_116510080.1', 'WP_116541160.1', 'WP_116541229.1', 'WP_116541313.1', 'WP_116541315.1', 'WP_116541316.1', 'WP_116541322.1', 'WP_116546163.1', 'WP_116587063.1', 'WP_116605321.1', 'WP_116438964.1', 'WP_116787018.1', 'WP_116787020.1', 'WP_116823050.1', 'WP_116823051.1', 'WP_116823053.1', 'WP_116823054.1', 'WP_116823056.1', 'WP_116831561.1', 'WP_116831562.1', 'WP_116833278.1', 'WP_116836094.1', 'WP_116836095.1', 'WP_116836106.1', 'WP_116836108.1', 'WP_116836366.1', 'WP_116836367.1', 'WP_116836368.1', 'WP_116836369.1', 'WP_116836614.1', 'WP_116822769.1', 'WP_116787019.1', 'WP_116822545.1', 'WP_116820937.1', 'WP_116787331.1', 'WP_116787332.1', 'WP_116787802.1', 'WP_116787803.1', 'WP_116787817.1', 'WP_116788555.1', 'WP_116788556.1', 'WP_116788557.1', 'WP_116789167.1', 'WP_116789175.1', 'WP_116789439.1', 'WP_116790308.1', 'WP_116800556.1', 'WP_116800557.1', 'WP_116801474.1', 'WP_116815510.1', 'WP_116820368.1', 'WP_116820938.1', 'WP_116437936.1', 'WP_116437925.1', 'WP_116431336.1', 'WP_116163586.1', 'WP_116163587.1', 'WP_116163893.1', 'WP_116163895.1', 'WP_116164483.1', 'WP_116164485.1', 'WP_116164487.1', 'WP_116164638.1', 'WP_116164640.1', 'WP_116165020.1', 'WP_116165022.1', 'WP_116165026.1', 'WP_116166358.1', 'WP_116166359.1', 'WP_116186198.1', 'WP_116209906.1', 'WP_116163584.1', 'WP_116209908.1', 'WP_116163582.1', 'WP_116163579.1', 'WP_116111104.1', 'WP_116111105.1', 'WP_116112647.1', 'WP_116112902.1', 'WP_116112904.1', 'WP_116112906.1', 'WP_116112909.1', 'WP_116112927.1', 'WP_116113426.1', 'WP_116156157.1', 'WP_116162583.1', 'WP_116162585.1', 'WP_116162587.1', 'WP_116162589.1', 'WP_116162669.1', 'WP_116162855.1', 'WP_116163306.1', 'WP_116163580.1', 'WP_116209909.1', 'WP_116209910.1', 'WP_116209911.1', 'WP_116325677.1', 'WP_116326916.1', 'WP_116326940.1', 'WP_116326941.1', 'WP_116326962.1', 'WP_116327699.1', 'WP_116328925.1', 'WP_116329934.1', 'WP_116335582.1', 'WP_116335587.1', 'WP_116335629.1', 'WP_116350187.1', 'WP_116362404.1', 'WP_116397392.1', 'WP_116431271.1', 'WP_116325669.1', 'WP_116322096.1', 'WP_116311996.1', 'WP_116307247.1', 'WP_116213062.1', 'WP_116214230.1', 'WP_116214231.1', 'WP_116214232.1', 'WP_116215101.1', 'WP_116215103.1', 'WP_116215105.1', 'WP_116238052.1', 'WP_116267905.1', 'WP_116281103.1', 'WP_116290087.1', 'WP_116300112.1', 'WP_116306735.1', 'WP_116307245.1', 'WP_116268194.1', 'WP_116836778.1', 'WP_115613435.1', 'WP_115600567.1', 'WP_115173438.1', 'WP_115173488.1', 'WP_115188612.1', 'WP_115188897.1', 'WP_115191056.1', 'WP_115193688.1', 'WP_115194607.1', 'WP_115209593.1', 'WP_115224610.1', 'WP_115224650.1', 'WP_115230688.1', 'WP_115231209.1', 'WP_115234336.1', 'WP_115173243.1', 'WP_115239789.1', 'WP_115117186.1', 'WP_115130225.1', 'WP_115154636.1', 'WP_115154637.1', 'WP_115154638.1', 'WP_115166985.1', 'WP_115117078.1', 'WP_115239790.1', 'WP_115239792.1', 'WP_115283795.1', 'WP_115286881.1', 'WP_115287395.1', 'WP_115287420.1', 'WP_115287421.1', 'WP_115287425.1', 'WP_115288221.1', 'WP_115288849.1', 'WP_115293112.1', 'WP_115299549.1', 'WP_115299550.1', 'WP_115299553.1', 'WP_115299857.1', 'WP_115299858.1', 'WP_115299859.1', 'WP_115239791.1', 'WP_115266334.1', 'WP_115240039.1', 'WP_115243220.1', 'WP_115243376.1', 'WP_115245435.1', 'WP_115249799.1', 'WP_115249800.1', 'WP_115257859.1', 'WP_115257861.1', 'WP_115257868.1', 'WP_115257869.1', 'WP_115257870.1', 'WP_115257871.1', 'WP_115257872.1', 'WP_115262428.1', 'WP_115264245.1', 'WP_115264246.1', 'WP_115266465.1', 'WP_115299860.1', 'WP_115116830.1', 'WP_115116828.1', 'WP_115048315.1', 'WP_115048958.1', 'WP_115048960.1', 'WP_115049155.1', 'WP_115050249.1', 'WP_115060301.1', 'WP_115060856.1', 'WP_115075891.1', 'WP_115075893.1', 'WP_115075895.1', 'WP_115075896.1', 'WP_115075897.1', 'WP_115046947.1', 'WP_114936057.1', 'WP_114949741.1', 'WP_114967855.1', 'WP_114975558.1', 'WP_114995769.1', 'WP_114995772.1', 'WP_115015343.1', 'WP_115015347.1', 'WP_115046685.1', 'WP_115116829.1', 'WP_115075898.1', 'WP_115098398.1', 'WP_115098399.1', 'WP_115098400.1', 'WP_115098401.1', 'WP_115098402.1', 'WP_115098406.1', 'WP_115098407.1', 'WP_115098408.1', 'WP_115098536.1', 'WP_115098537.1', 'WP_115098539.1', 'WP_115098540.1', 'WP_115098541.1', 'WP_115098647.1', 'WP_115116444.1', 'WP_115116445.1', 'WP_115116825.1', 'WP_115098397.1', 'WP_115075900.1', 'WP_115098396.1', 'WP_115097915.1', 'WP_115097899.1', 'WP_115097914.1', 'WP_115097916.1', 'WP_115299936.1', 'WP_115299937.1', 'WP_115299968.1', 'WP_115429194.1', 'WP_115430790.1', 'WP_115430796.1', 'WP_115430840.1', 'WP_115435259.1', 'WP_115435439.1', 'WP_115435440.1', 'WP_115435441.1', 'WP_115435442.1', 'WP_115435443.1', 'WP_115435444.1', 'WP_115435586.1', 'WP_115423771.1', 'WP_115423365.1', 'WP_115423473.1', 'WP_115423474.1', 'WP_115423475.1', 'WP_115423476.1', 'WP_115423768.1', 'WP_115423770.1', 'WP_115436435.1', 'WP_115436595.1', 'WP_115587182.1', 'WP_115596100.1', 'WP_115599124.1', 'WP_115599125.1', 'WP_115539260.1', 'WP_115436436.1', 'WP_115539010.1', 'WP_115538439.1', 'WP_115436737.1', 'WP_115436905.1', 'WP_115437086.1', 'WP_115437168.1', 'WP_115444372.1', 'WP_115489314.1', 'WP_115490352.1', 'WP_115511033.1', 'WP_115538170.1', 'WP_115538171.1', 'WP_115538172.1', 'WP_115538173.1', 'WP_115538174.1', 'WP_115538175.1', 'WP_115538180.1', 'WP_115538356.1', 'WP_115538362.1', 'WP_115538992.1', 'WP_115312101.1', 'WP_115312102.1', 'WP_115323102.1', 'WP_115323103.1', 'WP_115324241.1', 'WP_115336319.1', 'WP_115346620.1', 'WP_115350785.1', 'WP_115352738.1', 'WP_115352739.1', 'WP_115299969.1', 'WP_115299971.1', 'WP_115304631.1', 'WP_115304820.1', 'WP_115304821.1', 'WP_115305918.1', 'WP_115305980.1', 'WP_115354279.1', 'WP_115389979.1', 'WP_115399249.1', 'WP_115359431.1', 'WP_115359432.1', 'WP_115609437.1', 'WP_115363061.1', 'WP_118654665.1', 'WP_117714081.1', 'WP_117717133.1', 'WP_117738574.1', 'WP_117706945.1', 'WP_117631418.1', 'WP_117660150.1', 'WP_117660152.1', 'WP_117673233.1', 'WP_117689369.1', 'WP_117757939.1', 'WP_117839559.1', 'WP_117840679.1', 'WP_117858351.1', 'WP_117858384.1', 'WP_117860212.1', 'WP_117860225.1', 'WP_117860480.1', 'WP_117860556.1', 'WP_117905973.1', 'WP_117906008.1', 'WP_117906156.1', 'WP_117831463.1', 'WP_117762687.1', 'WP_117764516.1', 'WP_117765512.1', 'WP_117784313.1', 'WP_117801100.1', 'WP_117811210.1', 'WP_117906158.1', 'WP_117387335.1', 'WP_117394447.1', 'WP_117398551.1', 'WP_117423354.1', 'WP_117440271.1', 'WP_117385113.1', 'WP_117452949.1', 'WP_117380940.1', 'WP_117368105.1', 'WP_117362393.1', 'WP_117363058.1', 'WP_117364569.1', 'WP_117365805.1', 'WP_117366796.1', 'WP_117452973.1', 'WP_117453281.1', 'WP_117536278.1', 'WP_117536279.1', 'WP_117536280.1', 'WP_117536281.1', 'WP_117536502.1', 'WP_117563508.1', 'WP_117576160.1', 'WP_117581268.1', 'WP_117581613.1', 'WP_117596322.1', 'WP_117601164.1', 'WP_117536263.1', 'WP_117453280.1', 'WP_117534272.1', 'WP_117453282.1', 'WP_117453766.1', 'WP_117453767.1', 'WP_117455581.1', 'WP_117455583.1', 'WP_117455585.1', 'WP_117455587.1', 'WP_117455589.1', 'WP_117455591.1', 'WP_117455598.1', 'WP_117460826.1', 'WP_117500393.1', 'WP_117500394.1', 'WP_117502239.1', 'WP_117530175.1', 'WP_117906159.1', 'WP_118292629.1', 'WP_118292725.1', 'WP_118296011.1', 'WP_118327601.1', 'WP_118327603.1', 'WP_118379553.1', 'WP_118249266.1', 'WP_118249267.1', 'WP_118253527.1', 'WP_118259134.1', 'WP_118268302.1', 'WP_118268303.1', 'WP_118276695.1', 'WP_118214710.1', 'WP_118381969.1', 'WP_118394059.1', 'WP_118549294.1', 'WP_118549917.1', 'WP_118549918.1', 'WP_118549920.1', 'WP_118549921.1', 'WP_118549923.1', 'WP_118590918.1', 'WP_118591112.1', 'WP_118594100.1', 'WP_118594114.1', 'WP_118393788.1', 'WP_118395468.1', 'WP_118395470.1', 'WP_118433759.1', 'WP_118435362.1', 'WP_118214709.1', 'WP_118210366.1', 'WP_118210358.1', 'WP_118058920.1', 'WP_118058921.1', 'WP_118058922.1', 'WP_118058923.1', 'WP_118058924.1', 'WP_118058925.1', 'WP_118058926.1', 'WP_118058980.1', 'WP_118058981.1', 'WP_118058982.1', 'WP_118067512.1', 'WP_118067513.1', 'WP_118069179.1', 'WP_118069181.1', 'WP_118069184.1', 'WP_118072438.1', 'WP_118072439.1', 'WP_118058492.1', 'WP_118072440.1', 'WP_118058491.1', 'WP_118049907.1', 'WP_117918592.1', 'WP_117920032.1', 'WP_117920034.1', 'WP_117922819.1', 'WP_117940223.1', 'WP_117941805.1', 'WP_117943518.1', 'WP_117964426.1', 'WP_117964429.1', 'WP_117965651.1', 'WP_118024020.1', 'WP_118027837.1', 'WP_118038062.1', 'WP_118038381.1', 'WP_118049893.1', 'WP_118058460.1', 'WP_118072443.1', 'WP_118072635.1', 'WP_118072649.1', 'WP_118120959.1', 'WP_118120960.1', 'WP_118120961.1', 'WP_118120962.1', 'WP_118121350.1', 'WP_118121351.1', 'WP_118147469.1', 'WP_118166690.1', 'WP_118166691.1', 'WP_118166692.1', 'WP_118166695.1', 'WP_118166840.1', 'WP_118166977.1', 'WP_118188779.1', 'WP_118209081.1', 'WP_118209449.1', 'WP_118119733.1', 'WP_118119419.1', 'WP_118119417.1', 'WP_118119279.1', 'WP_118072653.1', 'WP_118072655.1', 'WP_118074424.1', 'WP_118074504.1', 'WP_118074685.1', 'WP_118075136.1', 'WP_118075330.1', 'WP_117362318.1', 'WP_118075890.1', 'WP_118112278.1', 'WP_118117675.1', 'WP_118117906.1', 'WP_118117994.1', 'WP_118119273.1', 'WP_118119275.1', 'WP_118119277.1', 'WP_118075962.1', 'WP_117362066.1', 'WP_117355318.1', 'WP_117084169.1', 'WP_117084170.1', 'WP_117084551.1', 'WP_117086312.1', 'WP_117088840.1', 'WP_117091838.1', 'WP_117094345.1', 'WP_117095655.1', 'WP_117096069.1', 'WP_117096445.1', 'WP_117101167.1', 'WP_117102714.1', 'WP_117103017.1', 'WP_117103503.1', 'WP_117103504.1', 'WP_117103505.1', 'WP_117084124.1', 'WP_117106424.1', 'WP_117084118.1', 'WP_117083342.1', 'WP_117062787.1', 'WP_117062788.1', 'WP_117062789.1', 'WP_117063368.1', 'WP_117063942.1', 'WP_117064014.1', 'WP_117064015.1', 'WP_117064016.1', 'WP_117064017.1', 'WP_117064018.1', 'WP_117064019.1', 'WP_117065130.1', 'WP_117074187.1', 'WP_117076894.1', 'WP_117079139.1', 'WP_117079486.1', 'WP_117082580.1', 'WP_117084117.1', 'WP_117062786.1', 'WP_117106425.1', 'WP_117108863.1', 'WP_117172583.1', 'WP_117172584.1', 'WP_117172585.1', 'WP_117172616.1', 'WP_117172617.1', 'WP_117172618.1', 'WP_117174868.1', 'WP_117175631.1', 'WP_117175633.1', 'WP_117176620.1', 'WP_117176622.1', 'WP_117176818.1', 'WP_117176832.1', 'WP_117176834.1', 'WP_117176836.1', 'WP_117176838.1', 'WP_117176955.1', 'WP_117172581.1', 'WP_117107380.1', 'WP_117172576.1', 'WP_117137822.1', 'WP_117108864.1', 'WP_117108865.1', 'WP_117108868.1', 'WP_117108869.1', 'WP_117116603.1', 'WP_117117226.1', 'WP_117118906.1', 'WP_117118908.1', 'WP_117118909.1', 'WP_117120777.1', 'WP_117121207.1', 'WP_117121465.1', 'WP_117121466.1', 'WP_117121551.1', 'WP_117130746.1', 'WP_117131015.1', 'WP_117131016.1', 'WP_117144952.1', 'WP_117176957.1', 'WP_117062769.1', 'WP_117054145.1', 'WP_116886429.1', 'WP_116892731.1', 'WP_116920169.1', 'WP_116920184.1', 'WP_116868642.1', 'WP_116869984.1', 'WP_117058230.1', 'WP_116937960.1', 'WP_116939696.1', 'WP_117030974.1', 'WP_117031219.1', 'WP_117031492.1', 'WP_117031493.1', 'WP_117034489.1', 'WP_117035078.1', 'WP_117037052.1', 'WP_117037053.1', 'WP_117039762.1', 'WP_117040066.1', 'WP_117043706.1', 'WP_117047012.1', 'WP_117048564.1', 'WP_117049162.1', 'WP_117049174.1', 'WP_117049193.1', 'WP_117049204.1', 'WP_117026221.1', 'WP_116939694.1', 'WP_117025227.1', 'WP_117023254.1', 'WP_116939721.1', 'WP_116939915.1', 'WP_116940086.1', 'WP_116961687.1', 'WP_116968897.1', 'WP_116968898.1', 'WP_116968899.1', 'WP_116987748.1', 'WP_116987749.1', 'WP_117006024.1', 'WP_117008223.1', 'WP_117009617.1', 'WP_117021939.1', 'WP_117023253.1', 'WP_117024726.1', 'WP_117176958.1', 'WP_117176959.1', 'WP_117176960.1', 'WP_117309385.1', 'WP_117309386.1', 'WP_117310053.1', 'WP_117310395.1', 'WP_117311785.1', 'WP_117285534.1', 'WP_117285915.1', 'WP_117285916.1', 'WP_117286877.1', 'WP_117286878.1', 'WP_117287182.1', 'WP_117287183.1', 'WP_117287242.1', 'WP_117285425.1', 'WP_117349632.1', 'WP_117350943.1', 'WP_117351337.1', 'WP_117353758.1', 'WP_117355315.1', 'WP_117341316.1', 'WP_117319931.1', 'WP_117319971.1', 'WP_117320101.1', 'WP_117320149.1', 'WP_117320151.1', 'WP_117338632.1', 'WP_117338694.1', 'WP_117338695.1', 'WP_117339672.1', 'WP_117339721.1', 'WP_117339723.1', 'WP_117339846.1', 'WP_117339848.1', 'WP_117339850.1', 'WP_117341188.1', 'WP_117341304.1', 'WP_117341305.1', 'WP_117345741.1', 'WP_117285423.1', 'WP_117285422.1', 'WP_117285421.1', 'WP_117229926.1', 'WP_117230563.1', 'WP_117177549.1', 'WP_117177551.1', 'WP_117177811.1', 'WP_117177813.1', 'WP_117177817.1', 'WP_117177890.1', 'WP_117177936.1', 'WP_117177938.1', 'WP_117177940.1', 'WP_117177942.1', 'WP_117178553.1', 'WP_117178555.1', 'WP_117189263.1', 'WP_117196569.1', 'WP_117196570.1', 'WP_117196571.1', 'WP_117230999.1', 'WP_117266121.1', 'WP_117274954.1', 'WP_117274955.1', 'WP_117274956.1', 'WP_117274957.1', 'WP_117275180.1', 'WP_117275194.1', 'WP_117275210.1', 'WP_117275212.1', 'WP_117275214.1', 'WP_117275424.1', 'WP_117285354.1', 'WP_117285355.1', 'WP_117285356.1', 'WP_117285357.1', 'WP_117285377.1', 'WP_117285378.1', 'WP_117264774.1', 'WP_117264346.1', 'WP_117263703.1', 'WP_117255098.1', 'WP_117355320.1', 'WP_117231380.1', 'WP_117239715.1', 'WP_117247353.1', 'WP_117247354.1', 'WP_117247356.1', 'WP_117247368.1', 'WP_117249004.1', 'WP_117249005.1', 'WP_109887679.1', 'WP_109886427.1', 'WP_109880167.1', 'WP_103364192.1', 'WP_103364194.1', 'WP_103364226.1', 'WP_103364432.1', 'WP_103364433.1', 'WP_103364435.1', 'WP_103370377.1', 'WP_103377301.1', 'WP_103410062.1', 'WP_103410063.1', 'WP_103410065.1', 'WP_103410066.1', 'WP_103410136.1', 'WP_103410137.1', 'WP_103410138.1', 'WP_103410139.1', 'WP_103410140.1', 'WP_103364191.1', 'WP_103410200.1', 'WP_103364113.1', 'WP_103322422.1', 'WP_103284783.1', 'WP_103284784.1', 'WP_103286029.1', 'WP_103286503.1', 'WP_103286504.1', 'WP_103287661.1', 'WP_103287662.1', 'WP_103287663.1', 'WP_103294775.1', 'WP_103294776.1', 'WP_103294777.1', 'WP_103300131.1', 'WP_103301410.1', 'WP_103301411.1', 'WP_103301779.1', 'WP_103322250.1', 'WP_103322421.1', 'WP_103363942.1', 'WP_103284782.1', 'WP_103410336.1', 'WP_103410339.1', 'WP_103413527.1', 'WP_103413528.1', 'WP_103413602.1', 'WP_103413603.1', 'WP_103413606.1', 'WP_103414075.1', 'WP_103414857.1', 'WP_103415169.1', 'WP_103429223.1', 'WP_103413526.1', 'WP_103410338.1', 'WP_103413485.1', 'WP_103413223.1', 'WP_103410406.1', 'WP_103410408.1', 'WP_103410409.1', 'WP_103410457.1', 'WP_103410820.1', 'WP_103411520.1', 'WP_103411521.1', 'WP_103412111.1', 'WP_103412112.1', 'WP_103412113.1', 'WP_103412115.1', 'WP_103412262.1', 'WP_103412263.1', 'WP_103413096.1', 'WP_103413097.1', 'WP_103413221.1', 'WP_103413222.1', 'WP_103413353.1', 'WP_103433602.1', 'WP_103284781.1', 'WP_103284610.1', 'WP_103259713.1', 'WP_103259714.1', 'WP_103260513.1', 'WP_103260577.1', 'WP_103260578.1', 'WP_103260580.1', 'WP_103260581.1', 'WP_103260698.1', 'WP_103261332.1', 'WP_103261342.1', 'WP_103261346.1', 'WP_103261347.1', 'WP_103261634.1', 'WP_103261717.1', 'WP_103261720.1', 'WP_103261721.1', 'WP_103259712.1', 'WP_103261722.1', 'WP_103255317.1', 'WP_103255199.1', 'WP_103242905.1', 'WP_103242906.1', 'WP_103242908.1', 'WP_103242909.1', 'WP_103242921.1', 'WP_103242922.1', 'WP_103243563.1', 'WP_103243566.1', 'WP_103243859.1', 'WP_103244178.1', 'WP_103244181.1', 'WP_103244183.1', 'WP_103244184.1', 'WP_103244330.1', 'WP_103244331.1', 'WP_103244723.1', 'WP_103245476.1', 'WP_103255316.1', 'WP_103284780.1', 'WP_103261757.1', 'WP_103277404.1', 'WP_103283432.1', 'WP_103283575.1', 'WP_103283585.1', 'WP_103283586.1', 'WP_103283588.1', 'WP_103283589.1', 'WP_103283927.1', 'WP_103283929.1', 'WP_103283931.1', 'WP_103283932.1', 'WP_103283947.1', 'WP_103283948.1', 'WP_103283959.1', 'WP_103284449.1', 'WP_103261760.1', 'WP_103263488.1', 'WP_103263489.1', 'WP_103263648.1', 'WP_103270853.1', 'WP_103270855.1', 'WP_103270957.1', 'WP_103270958.1', 'WP_103434628.1', 'WP_103469184.1', 'WP_103815382.1', 'WP_103822010.1', 'WP_103826984.1', 'WP_103826985.1', 'WP_103826986.1', 'WP_103826987.1', 'WP_103826988.1', 'WP_103827288.1', 'WP_103827289.1', 'WP_103827290.1', 'WP_103827387.1', 'WP_103827388.1', 'WP_103827390.1', 'WP_103828274.1', 'WP_103828276.1', 'WP_103828277.1', 'WP_103828952.1', 'WP_103799330.1', 'WP_103828954.1', 'WP_103797697.1', 'WP_103797507.1', 'WP_103792562.1', 'WP_103792904.1', 'WP_103793375.1', 'WP_103793509.1', 'WP_103793510.1', 'WP_103793511.1', 'WP_103793540.1', 'WP_103793541.1', 'WP_103793542.1', 'WP_103793614.1', 'WP_103793814.1', 'WP_103793815.1', 'WP_103794587.1', 'WP_103795709.1', 'WP_103796256.1', 'WP_103797208.1', 'WP_103797209.1', 'WP_103797508.1', 'WP_103765718.1', 'WP_103828962.1', 'WP_103828996.1', 'WP_103905098.1', 'WP_103929102.1', 'WP_103942488.1', 'WP_103892995.1', 'WP_103828963.1', 'WP_103892948.1', 'WP_103828997.1', 'WP_103829202.1', 'WP_103829203.1', 'WP_103829210.1', 'WP_103829211.1', 'WP_103849111.1', 'WP_103851180.1', 'WP_103858990.1', 'WP_103858991.1', 'WP_103861018.1', 'WP_103861561.1', 'WP_103861597.1', 'WP_103861598.1', 'WP_103861796.1', 'WP_103863248.1', 'WP_103863249.1', 'WP_103891417.1', 'WP_103892601.1', 'WP_103752921.1', 'WP_103750405.1', 'WP_103750404.1', 'WP_103498715.1', 'WP_103498716.1', 'WP_103524192.1', 'WP_103526848.1', 'WP_103557753.1', 'WP_103595140.1', 'WP_103492406.1', 'WP_103492565.1', 'WP_103607996.1', 'WP_103607997.1', '

In [15]:
job_id_2 = submit_id_mapping(
    from_db="RefSeq_Protein", to_db="UniProtKB", ids=no_uniprot_acc_list_batch2
)

print(job_id_2)

8IttPMUNt8

### Checking progress

#### Batch 1

In [23]:
if check_id_mapping_results_ready(job_id):
    link_batch1 = get_id_mapping_results_link(job_id)
    print(link_batch1)
    results_batch1 = get_id_mapping_results_search(link_batch1)
    print(results_batch1)

https://rest.uniprot.org/idmapping/uniprotkb/results/pkqEtDCTyz

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [24]:
batch1_failed_ids=results_batch1["failedIds"]

batch1_ids = pd.DataFrame(results_batch1["suggestedIds"])
batch1_ids

                 from             to
0      WP_001372321.1  UPI00025C98FA
1      WP_096937776.1  UPI000BDF8CB7
2      WP_003917092.1  UPI0001E62B16
3      WP_001381369.1  UPI000013B026
4      WP_020277900.1  UPI00000B9DB1
...               ...            ...
92666  WP_120161578.1  UPI000BB9DD26
92667  WP_120161586.1  UPI000BB9E5F5
92668  WP_120161589.1  UPI000BB9D94F
92669  WP_120171879.1  UPI000E74A980
92670  WP_120172190.1  UPI000E721F9C

[92671 rows x 2 columns]

#### Batch 2

In [25]:
if check_id_mapping_results_ready(job_id_2):
    link_batch2 = get_id_mapping_results_link(job_id_2)
    print(link_batch2)
    results_batch2 = get_id_mapping_results_search(link_batch2)
    print(results_batch2)

https://rest.uniprot.org/idmapping/uniprotkb/results/8IttPMUNt8

In [26]:
batch2_failed_ids=results_batch2["failedIds"]

batch2_ids = pd.DataFrame(results_batch2["suggestedIds"])
batch2_ids

                 from             to
0      WP_120172199.1  UPI000E74ADBD
1      WP_120173271.1  UPI000E711358
2      WP_119946308.1  UPI000E75E813
3      WP_119944944.1  UPI000E75BC82
4      WP_119944956.1  UPI000E726677
...               ...            ...
20833  WP_086613943.1  UPI000A39145F
20834  WP_086414403.1  UPI000A3BF26F
20835  WP_086625893.1  UPI000A3A7E04
20836  WP_086627698.1  UPI000A3D305F
20837  WP_086631304.1  UPI000A3786AE

[20838 rows x 2 columns]

### Concatenate dataframes and merge with no_uniprot_acc df

In [29]:
uniparc_ids=pd.concat([batch1_ids,batch2_ids])
uniparc_ids = uniparc_ids.rename(columns={'from': 'accession_in_sys', 'to': 'UniParc_ID'})
uniparc_ids

      accession_in_sys     UniParc_ID
0       WP_001372321.1  UPI00025C98FA
1       WP_096937776.1  UPI000BDF8CB7
2       WP_003917092.1  UPI0001E62B16
3       WP_001381369.1  UPI000013B026
4       WP_020277900.1  UPI00000B9DB1
...                ...            ...
20833   WP_086613943.1  UPI000A39145F
20834   WP_086414403.1  UPI000A3BF26F
20835   WP_086625893.1  UPI000A3A7E04
20836   WP_086627698.1  UPI000A3D305F
20837   WP_086631304.1  UPI000A3786AE

[113509 rows x 2 columns]

In [32]:
len(set(uniparc_ids["accession_in_sys"].tolist()))

113509

In [35]:
no_uniprot_acc_w_uniparc_ids=no_uniprot_acc.merge(uniparc_ids,on="accession_in_sys",how="left")
no_uniprot_acc_w_uniparc_ids

,accession_in_sys,type,subtype,species,sys_id,sys_beg,sys_end,duplicate_count,rank,UniParc_ID
0,WP_001372321.1,Mok_Hok_Sok,Mok_Hok_Sok,"Klebsiella aerogenes,Escherichia coli,Citrobac...","GCF_022559325_NZ_CP060980_Mok_Hok_Sok_1,GCF_01...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...","GCF_002156845.1_NZ_CP021341_00030,GCF_00218019...",692,5,UPI00025C98FA
1,WP_096937776.1,Mok_Hok_Sok,Mok_Hok_Sok,"Escherichia coli,Escherichia fergusonii,Klebsi...","GCF_016026215_NZ_CP065610_Mok_Hok_Sok_1,GCF_01...","GCF_010365485.1_NZ_CP048362_00038,GCF_02042404...","GCF_010365485.1_NZ_CP048362_00038,GCF_02042404...",262,25,UPI000BDF8CB7
2,WP_003917092.1,Cas,CAS_Class1-Subtype-III-A,"Mycobacterium tuberculosis,Mycobacterium orygis",GCF_014884645_NZ_CP043996_CAS_Class1-Subtype-I...,"GCF_002975475.1_NZ_CP027035_02939,GCF_01490083...","GCF_013010385.1_NZ_CP053092_02977,GCF_01691777...",257,27,UPI0001E62B16
3,WP_001381369.1,Cas,CAS_Class1-Subtype-I-E,"Shigella flexneri,Escherichia coli,Escherichia...",GCF_013167055_NZ_CP053605_CAS_Class1-Subtype-I...,"GCF_014075915.1_NZ_CP050031_00968,GCF_02260534...","GCF_014075795.1_NZ_CP050036_00976,GCF_00803329...",254,28,UPI000013B026
4,WP_020277900.1,MazEF,MazEF,"Klebsiella aerogenes,Enterobacter roggenkampii...","GCF_905330065_NZ_OW967005_MazEF_1,GCF_01677594...","GCF_011106605.1_NZ_CP040031_00014,GCF_02275994...","GCF_018274525.2_NZ_CP086665_00007,GCF_00190859...",215,39,UPI00000B9DB1
...,...,...,...,...,...,...,...,...,...,...
122259,WP_086613943.1,BREX,BREX_I,Klebsiella pneumoniae,GCF_016925315_NZ_CP070438_BREX_I_2,GCF_016925315.1_NZ_CP070438_00016,GCF_016925315.1_NZ_CP070438_00021,1,202,UPI000A39145F
122260,WP_086414403.1,RM,RM_Type_I,Eggerthella lenta,GCF_002148255_NZ_CP021140_RM_Type_I_1,GCF_002148255.1_NZ_CP021140_00899,GCF_002148255.1_NZ_CP021140_00901,1,202,UPI000A3BF26F
122261,WP_086625893.1,RM,RM_Type_II,Enterobacter kobei,GCF_023333675_NZ_CP083862_RM_Type_II_2,GCF_023333675.1_NZ_CP083862_03290,GCF_023333675.1_NZ_CP083862_03291,1,202,UPI000A3A7E04
122262,WP_086627698.1,Dpd,Dpd,Klebsiella pneumoniae,GCF_013305325_NZ_CP054303_Dpd_5,GCF_013305325.1_NZ_CP054303_05013,GCF_013305325.1_NZ_CP054303_05024,1,202,UPI000A3D305F
122263,WP_086631304.1,Lamassu-Fam,Lamassu-Mrr,Klebsiella variicola,GCF_900622615_NZ_LR130543_Lamassu-Mrr_2,GCF_900622615.1_NZ_LR130543_01680,GCF_900622615.1_NZ_LR130543_01682,1,202,UPI000A3786AE

In [36]:
no_uniprot_acc_w_uniparc_ids.to_excel("../data/defense_finder/refseq2uniprot_script/2025-06-27_no_uniprot_acc_w_uniparc_ids.xlsx",index=False)