In [11]:
import boto3
import io
import glob
import logging
import math
import os
import requests
import s3fs
import subprocess
import tempfile
import time

import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from dotenv import load_dotenv
from pathlib import Path

# Env
load_dotenv("../.env", override=True)
REPO_ROOT = os.environ["INSTALL_PATH"]
MINIO_KEY = os.environ["MINIO_KEY"]
MINIO_SECRET = os.environ["MINIO_SECRET"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

pl.Config.set_tbl_cols(-1)

polars.config.Config

- This notebook is meant to be run after `./get_gene_list.ipynb`

<br>

- This notebook performs the following steps:
<br>
<br>
    1. annotate gene list with C Marshall subpanel
    2. reorder cols in accordance with cols in `f"{REPO_ROOT}/notes/2026-10-15_c_trost_target_data_format.xlsx"`
    3. drop extraneous cols in accordance with cols in `f"{REPO_ROOT}/notes/2026-10-15_c_trost_target_data_format.xlsx"`
    3. drop rows with missing AA sequences

In [22]:
# ============================================================
#       Args
# ============================================================

# File intake
FILE_GENE_LIST = f"{REPO_ROOT}/results/2026-10-07_for_c_marshal.tsv"
FILE_MARSHALL_AI = f"{REPO_ROOT}/data_sync/c_marshal_ai_panel_genes.xlsx"
FILE_TARGET_SCHEMA = f"{REPO_ROOT}/notes/2026-10-15_c_trost_target_data_format.xlsx"

# Dirs
OUT_DIR = f"{REPO_ROOT}/results"

In [12]:
# ============================================================
#       In -- gene list
# ============================================================

df_gene_list = pl.read_csv(
    FILE_GENE_LIST,
    separator="\t",
    has_header=True,
    infer_schema_length=None,
    null_values="NA"
)

df_gene_list

shape: (1_848, 77)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ def ┆ def ┆ def ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ uni ┆ Gen ┆ Gen ┆ Gen ┆ Gen ┆ Gen ┆ Fun ┆ CDD ┆ Gen ┆ Int ┆ PAN ┆ Pfa ┆ PRO ┆ SMA ┆ Ref ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ hum ┆ def ┆ tm_ ┆ tm_ ┆ rms ┆ pym ┆ pym ┆ pym ┆ hum ┆ hum ┆ bac ┆ bac ┆ eva ┆ gri ┆ bac ┆ bac ┆ in_ ┆ mod ┆ mod ┆ pld ┆ pld ┆ tm_ ┆ tm_ ┆ tm_ ┆ q_v ┆ str ┆ str ┆ ali ┆ imm ┆ com ┆ alp ┆ run ┆ hum ┆ def ┆ hum ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla │
│ ens ┆ ens ┆ ens ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ pro ┆ e   ┆ e   ┆ e   ┆ e   ┆ e   ┆ Fam ┆ --- ┆ e3D ┆ erP ┆ THE ┆ m   ┆ SIT ┆ RT  ┆ Seq ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ an_ ┆ ens ┆ sco ┆ sco ┆ d   ┆ ol_ ┆ ol_ ┆ ol_ ┆ an_ ┆ an_ ┆ t_a ┆ t_a ┆ lue ┆ id_ ┆ ter ┆ ter ┆ con ┆ ule ┆ ule ┆ dt_ ┆ dt_ ┆ pva ┆ pva ┆ pva ┆ alu ┆ uct ┆ uct ┆ gnm ┆ une ┆ pos ┆ haf ┆ _da ┆ an_ ┆ ens ┆ an_ ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp │
│ e_u ┆ e_f ┆ e_t ┆ uni ┆ uni ┆ pro ┆ gen ┆ len ┆ gen ┆ t_r ┆ Ont ┆ Ont ┆ Ont ┆ Ont ┆ Ont ┆ --- ┆ str ┆ --- ┆ ro  ┆ R   ┆ --- ┆ E   ┆ --- ┆ --- ┆ e_t ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ e_d ┆ e_r ┆ dom ┆ e_g ┆ re_ ┆ re_ ┆ --- ┆ rms ┆ ali ┆ ali ┆ ali ┆ ali ┆ lig ┆ lig ┆ _fo ┆ gen ┆ ial ┆ ial ┆ ser ┆ _co ┆ _pa ┆ hum ┆ bac ┆ lue ┆ lue ┆ lue ┆ e   ┆ ure ┆ ure ┆ ent ┆ _re ┆ ite ┆ old ┆ te  ┆ gen ┆ e_A ┆ AA_ ┆ _pi ┆ _le ┆ _mi ┆ _ga ┆ _qs ┆ _qe ┆ _ss ┆ _se ┆ _ev ┆ _bi │
│ nip ┆ old ┆ axI ┆ pro ┆ pro ┆ tei ┆ e_n ┆ gth ┆ e_n ┆ ef_ ┆ olo ┆ olo ┆ olo ┆ olo ┆ olo ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ ype ┆ ubt ┆ pec ┆ ys_ ┆ ys_ ┆ ys_ ┆ upl ┆ ank ┆ ain ┆ ene ┆ hum ┆ bac ┆ f64 ┆ d   ┆ gne ┆ gne ┆ gne ┆ gne ┆ ned ┆ ned ┆ lds ┆ e   ┆ _le ┆ _do ┆ ved ┆ unt ┆ rtn ┆ an_ ┆ ter ┆ _hu ┆ _ba ┆ --- ┆ --- ┆ _so ┆ _so ┆ _st ┆ lev ┆ _sc ┆ _mo ┆ --- ┆ e_i ┆ A_s ┆ seq ┆ den ┆ ngt ┆ sma ┆ pop ┆ tar ┆ nd  ┆ tar ┆ nd  ┆ alu ┆ tsc │
│ rot ┆ see ┆ d   ┆ t_a ┆ t_r ┆ n_n ┆ ame ┆ _AA ┆ ame ┆ pro ┆ gy  ┆ gy  ┆ gy  ┆ gy  ┆ gy  ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ ype ┆ ies ┆ id  ┆ beg ┆ end ┆ ica ┆ --- ┆ s   ┆ _na ┆ an  ┆ ter ┆     ┆ --- ┆ d_a ┆ d_r ┆ d_s ┆ d_e ┆ _st ┆ _en ┆ eek ┆ --- ┆ ngt ┆ mai ┆ _mo ┆ --- ┆ er_ ┆ mea ┆ ia_ ┆ man ┆ cte ┆ f64 ┆ f64 ┆ urc ┆ urc ┆ atu ┆ ant ┆ ore ┆ del ┆ str ┆ n_I ┆ equ ┆ uen ┆ t   ┆ h   ┆ tch ┆ en  ┆ t   ┆ --- ┆ t   ┆ --- ┆ e   ┆ ore │
│ _ac ┆ k_r ┆ --- ┆ c   ┆ evi ┆ ame ┆ s   ┆ s   ┆ _pr ┆ teo ┆ (bi ┆ (ce ┆ (mo ┆ (GO ┆ IDs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ te_ ┆ i64 ┆ --- ┆ me  ┆ --- ┆ ia  ┆     ┆ f64 ┆ tom ┆ esi ┆ tar ┆ nd  ┆ art ┆ d   ┆ --- ┆ boo ┆ h   ┆ ns  ┆ dul ┆ i64 ┆ gen ┆ n   ┆ mea ┆ --- ┆ ria ┆     ┆     ┆ e_h ┆ e_b ┆ s   ┆ --- ┆ --- ┆ _ve ┆     ┆ UIS ┆ enc ┆ ce  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ i64 ┆ --- ┆ i64 ┆ --- ┆ --- │
│ --- ┆ epI ┆ i64 ┆ --- ┆ ewe ┆ s   ┆ --- ┆ --- ┆ ima ┆ me_ ┆ olo ┆ llu ┆ lec ┆ )   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ cou ┆     ┆ str ┆ --- ┆ f64 ┆ --- ┆     ┆     ┆ s   ┆ due ┆ t   ┆ --- ┆ --- ┆ --- ┆ f64 ┆ l   ┆ --- ┆ --- ┆ e   ┆     ┆ es  ┆ --- ┆ n   ┆ f64 ┆ --- ┆     ┆     ┆ uma ┆ act ┆ --- ┆ boo ┆ f64 ┆ rsi ┆     ┆ --- ┆ e   ┆ --- ┆ f64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆ f64 ┆ f64 │
│ str ┆ d   ┆     ┆ str ┆ d   ┆ --- ┆ str ┆ i64 ┆ ry  ┆ chr ┆ gic ┆ lar ┆ ula ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆ str ┆     ┆ f64 ┆     ┆     ┆ --- ┆ s   ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ str ┆ --- ┆     ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆ n   ┆ eri ┆ str ┆ l   ┆     ┆ on  ┆     ┆ boo ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ --- ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆ al  ┆ com ┆ r   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆     ┆ str ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ a   ┆     ┆     ┆     ┆ --- ┆     ┆ l   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆ pro ┆ pon ┆ fun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c…  ┆ …   ┆ ct… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Q47 ┆ A0A ┆ 167 ┆ Q8I ┆ unr ┆ GTP ┆ nul ┆ 177 ┆ nul ┆ nul ┆ reg ┆ cyt ┆ GTP ┆ cyt ┆ GO: ┆ 1.1 ┆ cd0 ┆ 1.1 ┆ IPR ┆ PTH ┆ PF0 ┆ PS0 ┆ nul ┆ NP_ ┆ Dpd ┆ Dpd ┆ Col ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ DOM ┆ Dpd ┆ 0.9 ┆ 0.9 ┆ 0.5 ┆ 0.2 ┆ 986 ┆ 175 ┆ 1   ┆ 176 ┆ 6   ┆ 181 ┆ 0.0 ┆ fal ┆ 182 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 95. ┆ 97. ┆ 8.8 ┆ 2.5 ┆ 2.5 ┆ 1.7 ┆ afd ┆ afd ┆ ok  ┆ fal ┆ 0.9 ┆ mod ┆     ┆ nul ┆ MTI ┆ AYS ┆ 56. ┆ 175 ┆ 77  ┆ 0   ┆ 7   ┆ 181 ┆ 2   ┆ 176 ┆ 7.3 ┆ 227 │
│ ZY9 ┆ 2E5 ┆ 879 ┆ ZH9 ┆ evi ┆ cyc ┆ l   ┆     ┆ l   ┆ l   ┆ ula ┆ opl ┆ bin ┆ opl ┆ 000 ┆ 0.2 ┆ 064 ┆ 0.2 ┆ 043 ┆ R11 ┆ 122 ┆ 085 ┆ l   ┆ 001 ┆     ┆     ┆ wel ┆ _00 ┆ _00 ┆ _00 ┆     ┆     ┆ AIN ┆ __F ┆ 91  ┆ 64  ┆ 1   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 53  ┆ 12  ┆ 818 ┆ 535 ┆ 535 ┆ 883 ┆ b_v ┆ b_v ┆     ┆ se  ┆ 962 ┆ el_ ┆     ┆ l   ┆ ENN ┆ SIL ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ .0  │
│     ┆ CU0 ┆     ┆     ┆ ewe ┆ loh ┆     ┆     ┆     ┆     ┆ tio ┆ asm ┆ din ┆ asm ┆ 393 ┆ 86. ┆ 2;  ┆ 86. ┆ 133 ┆ 109 ┆ 7;  ┆ 9;P ┆     ┆ 019 ┆     ┆     ┆ lia ┆ 001 ┆ 001 ┆ 001 ┆     ┆     ┆ 2.. ┆ olE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.. ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆ e-1 ┆ e-1 ┆ e-9 ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ YRE ┆ SSL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-8 ┆     │
│     ┆ 8   ┆     ┆     ┆ d   ┆ ydr ┆     ┆     ┆     ┆     ┆ n   ┆ [GO ┆ g   ┆ [GO ┆ 4;  ┆ 10: ┆     ┆ 10; ┆ ;IP ┆ :SF ┆     ┆ S00 ┆     ┆ 195 ┆     ┆     ┆ psy ┆ 232 ┆ 232 ┆ 232 ┆     ┆     ┆ 176 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 180 ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ILA ┆ GEN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     ┆ of  ┆ :00 ┆ [GO ┆ :00 ┆ GO: ┆ FF: ┆     ┆ 3.3 ┆ R04 ┆ 11; ┆     ┆ 860 ┆     ┆ .1; ┆     ┆     ┆ chr ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TIG ┆ PQR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆ blo ┆ 057 ┆ :00 ┆ 057 ┆ 000 ┆ 000 ┆     ┆ 0.1 ┆ 313 ┆ PTH ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆ ery ┆ C_0 ┆ _NC ┆ _NC ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDI ┆ QGL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ od  ┆ 37] ┆ 055 ┆ 37] ┆ 552 ┆ 003 ┆     ┆ 130 ┆ 4;I ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆     ┆ thr ┆ 039 ┆ _00 ┆ _00 ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NRG ┆ LKT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ (EC ┆     ┆     ┆     ┆     ┆ pre ┆ ;   ┆ 25] ┆ ;   ┆ 5;  ┆ ;3. ┆     ┆ .10 ┆ PR0 ┆ 109 ┆     ┆     ┆     ┆     ┆     ┆     ┆ aea ┆ 10_ ┆ 391 ┆ 391 ┆     ┆     ┆ "GT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "GT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GLL ┆ PWR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 3.5 ┆     ┆     ┆     ┆     ┆ ssu ┆ nuc ┆ ;   ┆ nuc ┆ GO: ┆ 30. ┆     ┆ ;   ┆ 014 ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dpd ┆ 0_0 ┆ 0_0 ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DTP ┆ AAS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ .4… ┆     ┆     ┆     ┆     ┆ re  ┆ leu ┆ GTP ┆ leu ┆ 000 ┆ 113 ┆     ┆     ┆ 74; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆ 264 ┆ 265 ┆     ┆     ┆ cyc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cyc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ KRA ┆ AMQ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ […  ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ A0A ┆ A0A ┆ 582 ┆ Q5Q ┆ unr ┆ Cys ┆ NFS ┆ 397 ┆ NFS ┆ nul ┆ [2F ┆ cyt ┆ cys ┆ cyt ┆ GO: ┆ 3.4 ┆ nul ┆ 3.9 ┆ IPR ┆ PTH ┆ PF0 ┆ PS0 ┆ nul ┆ nul ┆ Dnd ┆ Dnd ┆ Rho ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ DOM ┆ Dnd ┆ 0.9 ┆ 0.9 ┆ 1.3 ┆ 0.5 ┆ 187 ┆ 367 ┆ 1   ┆ 376 ┆ 9   ┆ 386 ┆ 0.0 ┆ fal ┆ 386 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 94. ┆ 95. ┆ 1.3 ┆ 4.6 ┆ 1.3 ┆ 1.7 ┆ afd ┆ afd ┆ ok  ┆ fal ┆ 0.9 ┆ mod ┆     ┆ fal ┆ MSD ┆ MDV ┆ 44. ┆ 378 ┆ 208 ┆ 3   ┆ 9   ┆ 385 ┆ 1   ┆ 376 ┆ 5.3 ┆ 326 │
│ 5B9 ┆ 7C2 ┆ 702 ┆ P19 ┆ evi ┆ tei ┆ 1   ┆     ┆ 1   ┆ l   ┆ e-2 ┆ oso ┆ tei ┆ oso ┆ 000 ┆ 0.6 ┆ l   ┆ 0.1 ┆ 000 ┆ R11 ┆ 026 ┆ 059 ┆ l   ┆ l   ┆     ┆ _AB ┆ dan ┆ _00 ┆ _00 ┆ _00 ┆     ┆     ┆ AIN ┆ __D ┆ 237 ┆ 496 ┆     ┆ 4   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 52  ┆ 11  ┆ 656 ┆ 629 ┆ 656 ┆ 883 ┆ b_v ┆ b_v ┆     ┆ se  ┆ 863 ┆ el_ ┆     ┆ se  ┆ GRP ┆ QAT ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 700 ┆ .0  │
│ E1W ┆ NS9 ┆     ┆     ┆ ewe ┆ ne  ┆ hCG ┆     ┆     ┆     ┆ S]  ┆ l   ┆ ne  ┆ l   ┆ 565 ┆ 40. ┆     ┆ 150 ┆ 192 ┆ 601 ┆ 6;  ┆ 5;  ┆     ┆     ┆     ┆ CDE ┆ oba ┆ 800 ┆ 800 ┆ 800 ┆     ┆     ┆ 2.. ┆ ndA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7.. ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆ e-1 ┆ e-1 ┆ e-9 ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ IYL ┆ TPL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆     │
│ 6   ┆ 4   ┆     ┆     ┆ d   ┆ des ┆ _38 ┆     ┆     ┆     ┆ clu ┆ [GO ┆ des ┆ [GO ┆ 4;  ┆ 10: ┆     ┆ .10 ┆ ;IP ┆ :SF ┆     ┆     ┆     ┆     ┆     ┆     ┆ cte ┆ 079 ┆ 079 ┆ 079 ┆     ┆     ┆ 361 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 369 ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 5   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DHN ┆ DPR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     │
│     ┆     ┆     ┆     ┆     ┆ ulf ┆ 220 ┆     ┆     ┆     ┆ ste ┆ :00 ┆ ulf ┆ :00 ┆ GO: ┆ FF: ┆     ┆ ;3. ┆ R02 ┆ 34; ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATT ┆ VLD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ura ┆     ┆     ┆     ┆     ┆ r   ┆ 058 ┆ ura ┆ 058 ┆ 000 ┆ 000 ┆     ┆ 40. ┆ 057 ┆ PTH ┆     ┆     ┆     ┆     ┆     ┆     ┆ gly ┆ Z_C ┆ _NZ ┆ _NZ ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PLD ┆ AML ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆ ass ┆ 29] ┆ se  ┆ 29] ┆ 582 ┆ 003 ┆     ┆ 640 ┆ 8;I ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆     ┆ cin ┆ P04 ┆ _CP ┆ _CP ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PTV ┆ PYL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ (EC ┆     ┆     ┆     ┆     ┆ emb ┆ ;   ┆ act ┆ ;   ┆ 9;  ┆ ;3. ┆     ┆ .10 ┆ PR0 ┆ 601 ┆     ┆     ┆     ┆     ┆     ┆     ┆ is  ┆ 280 ┆ 042 ┆ 042 ┆     ┆     ┆ "Am ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Am ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FEA ┆ INY ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 2.8 ┆     ┆     ┆     ┆     ┆ ly  ┆ mit ┆ ivi ┆ mit ┆ GO: ┆ 90. ┆     ┆ ;   ┆ 102 ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_D ┆ 807 ┆ 807 ┆     ┆     ┆ ino ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ino ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MRP ┆ YGN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ .1… ┆     ┆     ┆     ┆     ┆ [GO ┆ och ┆ ty  ┆ och ┆ 000 ┆ 115 ┆     ┆     ┆ 40; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nd_ ┆ _02 ┆ _02 ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ YFL ┆ PHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :…  ┆ on… ┆ …   ┆ on… ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Q47 ┆ A0A ┆ 167 ┆ Q8I ┆ unr ┆ GTP ┆ nul ┆ 158 ┆ nul ┆ nul ┆ reg ┆ cyt ┆ GTP ┆ cyt ┆ GO: ┆ 1.1 ┆ nul ┆ 1.1 ┆ IPR ┆ PTH ┆ PF0 ┆ PS0 ┆ nul ┆ nul ┆ Dpd ┆ Dpd ┆ Col ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ DOM ┆ Dpd ┆ 0.9 ┆ 0.8 ┆ 1.2 ┆ 0.3 ┆ 835 ┆ 146 ┆ 1   ┆ 156 ┆ 6   ┆ 164 ┆ 0.0 ┆ fal ┆ 182 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 89. ┆ 97. ┆ 2.5 ┆ 4.3 ┆ 4.3 ┆ 6.5 ┆ afd ┆ afd ┆ ok  ┆ fal ┆ 0.9 ┆ mod ┆     ┆ nul ┆ MTI ┆ AYS ┆ 57. ┆ 134 ┆ 57  ┆ 0   ┆ 7   ┆ 140 ┆ 2   ┆ 135 ┆ 1.2 ┆ 180 │
│ ZY9 ┆ 2E5 ┆ 879 ┆ ZH8 ┆ evi ┆ cyc ┆ l   ┆     ┆ l   ┆ l   ┆ ula ┆ opl ┆ bin ┆ opl ┆ 000 ┆ 0.2 ┆ l   ┆ 0.2 ┆ 043 ┆ R11 ┆ 122 ┆ 085 ┆ l   ┆ l   ┆     ┆     ┆ wel ┆ _00 ┆ _00 ┆ _00 ┆     ┆     ┆ AIN ┆ __F ┆ 645 ┆ 401 ┆ 3   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 02  ┆ 12  ┆ 535 ┆ 343 ┆ 343 ┆ 280 ┆ b_v ┆ b_v ┆     ┆ se  ┆ 825 ┆ el_ ┆     ┆ l   ┆ ENN ┆ SIL ┆ 463 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 400 ┆ .0  │
│     ┆ CU0 ┆     ┆     ┆ ewe ┆ loh ┆     ┆     ┆     ┆     ┆ tio ┆ asm ┆ din ┆ asm ┆ 393 ┆ 86. ┆     ┆ 86. ┆ 133 ┆ 109 ┆ 7;  ┆ 9;P ┆     ┆     ┆     ┆     ┆ lia ┆ 001 ┆ 001 ┆ 001 ┆     ┆     ┆ 2.. ┆ olE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.. ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆ e-1 ┆ e-1 ┆ e-9 ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ YRE ┆ SSL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-6 ┆     │
│     ┆ 8   ┆     ┆     ┆ d   ┆ ydr ┆     ┆     ┆     ┆     ┆ n   ┆ [GO ┆ g   ┆ [GO ┆ 4;  ┆ 10: ┆     ┆ 10; ┆ ;IP ┆ :SF ┆     ┆ S00 ┆     ┆     ┆     ┆     ┆ psy ┆ 232 ┆ 232 ┆ 232 ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 180 ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ILA ┆ GEN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     ┆ of  ┆ :00 ┆ [GO ┆ :00 ┆ GO: ┆ FF: ┆     ┆ 3.3 ┆ R04 ┆ 11; ┆     ┆ 860 ┆     ┆     ┆     ┆     ┆ chr ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TIG ┆ PQR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆ blo ┆ 057 ┆ :00 ┆ 057 ┆ 000 ┆ 000 ┆     ┆ 0.1 ┆ 313 ┆ PTH ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆ ery ┆ C_0 ┆ _NC ┆ _NC ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDI ┆ QGL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [ ]:
# ============================================================
#       In -- C Marshall panel
# ============================================================

df_marshall_panel = pl.concat([
    pl.read_excel(
        FILE_MARSHALL_AI,
        sheet_name=sheet
    ).with_columns(
        pl.lit(sheet).alias("source_sheet")
    )
    for sheet in ["RFS", "HLH", "AI", "AG"]
])

df_marshall_panel

shape: (53, 4)
┌──────────┬─────────────┬───────────────┬──────────────┐
│ Subpanel ┆ snpEff_gene ┆ snpEff_refseq ┆ source_sheet │
│ ---      ┆ ---         ┆ ---           ┆ ---          │
│ str      ┆ str         ┆ str           ┆ str          │
╞══════════╪═════════════╪═══════════════╪══════════════╡
│ RFS      ┆ MEFV        ┆ NM_000243.2   ┆ RFS          │
│ RFS      ┆ MVK         ┆ NM_000431.3   ┆ RFS          │
│ RFS      ┆ NLRP12      ┆ NM_144687.3   ┆ RFS          │
│ RFS      ┆ NLRP3       ┆ NM_004895.4   ┆ RFS          │
│ RFS      ┆ TNFRSF1A    ┆ NM_001065.3   ┆ RFS          │
│ …        ┆ …           ┆ …             ┆ …            │
│ AG       ┆ RNASEH2A    ┆ NM_006397.2   ┆ AG           │
│ AG       ┆ RNASEH2B    ┆ NM_024570.3   ┆ AG           │
│ AG       ┆ RNASEH2C    ┆ NM_032193.3   ┆ AG           │
│ AG       ┆ SAMHD1      ┆ NM_015474.3   ┆ AG           │
│ AG       ┆ TREX1       ┆ NM_033629.4   ┆ AG           │
└──────────┴─────────────┴───────────────┴──────────────┘

In [23]:
# ============================================================
#       In -- target schema
# ============================================================

target_schema_cols = pl.read_excel(FILE_TARGET_SCHEMA, has_header=True, read_options={"n_rows": 0}).columns
target_schema_cols

['composite_score',
 'defense_uniprot_ac',
 'human_uniprot_ac',
 'human_gene_name_primary',
 'human_gene_names',
 'griid_gene',
 'iuis_iei',
 'human_gene_in_IUIS',
 'uniprot_ref_proteome_chr',
 'human_protein_names',
 'Gene Ontology (molecular function)',
 'Gene Ontology IDs',
 'RefSeq',
 'defense_type',
 'defense_subtype',
 'defense_duplicate_count',
 'defense_gene_name',
 'defense_species',
 'human_length_AAs',
 'human_aligned_start',
 'human_aligned_end',
 'bacterial_length',
 'bact_aligned_start',
 'bact_aligned_end',
 'pymol_aligned_residues',
 'pymol_rmsd',
 'plddt_human_mean',
 'human_AA_sequence',
 'plddt_bacteria_mean',
 'defense_AA_sequence',
 'blastp_pident',
 'blastp_length',
 'blastp_mismatch',
 'blastp_gapopen',
 'blastp_qstart',
 'blastp_qend',
 'blastp_sstart',
 'blastp_send',
 'blastp_evalue',
 'blastp_bitscore']

In [ ]:
# ============================================================
#       Annotate Marshall subpanel status
# ============================================================

subpanel_name_mappings = {
    "RFS": "Recurrent Fever Syndrome",
    "HLH": "Hemophagocytic Lymphohistiocytosis",
    "AI": "Autoinflammatory Diseases",
    "AG": "Aicardi-Goutieres Syndrome"
}

df_gene_list_ann = df_gene_list.join(
    df_marshall_panel.select(
        pl.col("snpEff_gene").alias("human_gene_name_primary"),
        pl.col("Subpanel").alias("marshall_immune_subpanel")
    ),
    on="human_gene_name_primary",
    how="left"
)

n_panel_hits = df_gene_list_ann["marshall_immune_subpanel"].len() - df_gene_list_ann["marshall_immune_subpanel"].null_count()
logger.info(f"Number of Marshall panel hits: {n_panel_hits}")

df_gene_list_ann = df_gene_list_ann.with_columns(
    pl.col("marshall_immune_subpanel").str.replace_many(
        list(subpanel_name_mappings.keys()),
        list(subpanel_name_mappings.values())
    )
)

df_gene_list_ann.filter(
    pl.col("marshall_immune_subpanel").is_not_null()
)

INFO:__main__:Number of Marshall panel hits: 9

shape: (9, 78)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ def ┆ def ┆ def ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ uni ┆ Gen ┆ Gen ┆ Gen ┆ Gen ┆ Gen ┆ Fun ┆ CDD ┆ Gen ┆ Int ┆ PAN ┆ Pfa ┆ PRO ┆ SMA ┆ Ref ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ def ┆ hum ┆ def ┆ tm_ ┆ tm_ ┆ rms ┆ pym ┆ pym ┆ pym ┆ hum ┆ hum ┆ bac ┆ bac ┆ eva ┆ gri ┆ bac ┆ bac ┆ in_ ┆ mod ┆ mod ┆ pld ┆ pld ┆ tm_ ┆ tm_ ┆ tm_ ┆ q_v ┆ str ┆ str ┆ ali ┆ imm ┆ com ┆ alp ┆ run ┆ hum ┆ def ┆ hum ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ mar │
│ ens ┆ ens ┆ ens ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ an_ ┆ pro ┆ e   ┆ e   ┆ e   ┆ e   ┆ e   ┆ Fam ┆ --- ┆ e3D ┆ erP ┆ THE ┆ m   ┆ SIT ┆ RT  ┆ Seq ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ an_ ┆ ens ┆ sco ┆ sco ┆ d   ┆ ol_ ┆ ol_ ┆ ol_ ┆ an_ ┆ an_ ┆ t_a ┆ t_a ┆ lue ┆ id_ ┆ ter ┆ ter ┆ con ┆ ule ┆ ule ┆ dt_ ┆ dt_ ┆ pva ┆ pva ┆ pva ┆ alu ┆ uct ┆ uct ┆ gnm ┆ une ┆ pos ┆ haf ┆ _da ┆ an_ ┆ ens ┆ an_ ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ sha │
│ e_u ┆ e_f ┆ e_t ┆ uni ┆ uni ┆ pro ┆ gen ┆ len ┆ gen ┆ t_r ┆ Ont ┆ Ont ┆ Ont ┆ Ont ┆ Ont ┆ --- ┆ str ┆ --- ┆ ro  ┆ R   ┆ --- ┆ E   ┆ --- ┆ --- ┆ e_t ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ e_d ┆ e_r ┆ dom ┆ e_g ┆ re_ ┆ re_ ┆ --- ┆ rms ┆ ali ┆ ali ┆ ali ┆ ali ┆ lig ┆ lig ┆ _fo ┆ gen ┆ ial ┆ ial ┆ ser ┆ _co ┆ _pa ┆ hum ┆ bac ┆ lue ┆ lue ┆ lue ┆ e   ┆ ure ┆ ure ┆ ent ┆ _re ┆ ite ┆ old ┆ te  ┆ gen ┆ e_A ┆ AA_ ┆ _pi ┆ _le ┆ _mi ┆ _ga ┆ _qs ┆ _qe ┆ _ss ┆ _se ┆ _ev ┆ _bi ┆ ll_ │
│ nip ┆ old ┆ axI ┆ pro ┆ pro ┆ tei ┆ e_n ┆ gth ┆ e_n ┆ ef_ ┆ olo ┆ olo ┆ olo ┆ olo ┆ olo ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ ype ┆ ubt ┆ pec ┆ ys_ ┆ ys_ ┆ ys_ ┆ upl ┆ ank ┆ ain ┆ ene ┆ hum ┆ bac ┆ f64 ┆ d   ┆ gne ┆ gne ┆ gne ┆ gne ┆ ned ┆ ned ┆ lds ┆ e   ┆ _le ┆ _do ┆ ved ┆ unt ┆ rtn ┆ an_ ┆ ter ┆ _hu ┆ _ba ┆ --- ┆ --- ┆ _so ┆ _so ┆ _st ┆ lev ┆ _sc ┆ _mo ┆ --- ┆ e_i ┆ A_s ┆ seq ┆ den ┆ ngt ┆ sma ┆ pop ┆ tar ┆ nd  ┆ tar ┆ nd  ┆ alu ┆ tsc ┆ imm │
│ rot ┆ see ┆ d   ┆ t_a ┆ t_r ┆ n_n ┆ ame ┆ _AA ┆ ame ┆ pro ┆ gy  ┆ gy  ┆ gy  ┆ gy  ┆ gy  ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ ype ┆ ies ┆ id  ┆ beg ┆ end ┆ ica ┆ --- ┆ s   ┆ _na ┆ an  ┆ ter ┆     ┆ --- ┆ d_a ┆ d_r ┆ d_s ┆ d_e ┆ _st ┆ _en ┆ eek ┆ --- ┆ ngt ┆ mai ┆ _mo ┆ --- ┆ er_ ┆ mea ┆ ia_ ┆ man ┆ cte ┆ f64 ┆ f64 ┆ urc ┆ urc ┆ atu ┆ ant ┆ ore ┆ del ┆ str ┆ n_I ┆ equ ┆ uen ┆ t   ┆ h   ┆ tch ┆ en  ┆ t   ┆ --- ┆ t   ┆ --- ┆ e   ┆ ore ┆ une │
│ _ac ┆ k_r ┆ --- ┆ c   ┆ evi ┆ ame ┆ s   ┆ s   ┆ _pr ┆ teo ┆ (bi ┆ (ce ┆ (mo ┆ (GO ┆ IDs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ te_ ┆ i64 ┆ --- ┆ me  ┆ --- ┆ ia  ┆     ┆ f64 ┆ tom ┆ esi ┆ tar ┆ nd  ┆ art ┆ d   ┆ --- ┆ boo ┆ h   ┆ ns  ┆ dul ┆ i64 ┆ gen ┆ n   ┆ mea ┆ --- ┆ ria ┆     ┆     ┆ e_h ┆ e_b ┆ s   ┆ --- ┆ --- ┆ _ve ┆     ┆ UIS ┆ enc ┆ ce  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ i64 ┆ --- ┆ i64 ┆ --- ┆ --- ┆ _su │
│ --- ┆ epI ┆ i64 ┆ --- ┆ ewe ┆ s   ┆ --- ┆ --- ┆ ima ┆ me_ ┆ olo ┆ llu ┆ lec ┆ )   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ cou ┆     ┆ str ┆ --- ┆ f64 ┆ --- ┆     ┆     ┆ s   ┆ due ┆ t   ┆ --- ┆ --- ┆ --- ┆ f64 ┆ l   ┆ --- ┆ --- ┆ e   ┆     ┆ es  ┆ --- ┆ n   ┆ f64 ┆ --- ┆     ┆     ┆ uma ┆ act ┆ --- ┆ boo ┆ f64 ┆ rsi ┆     ┆ --- ┆ e   ┆ --- ┆ f64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆ f64 ┆ f64 ┆ bpa │
│ str ┆ d   ┆     ┆ str ┆ d   ┆ --- ┆ str ┆ i64 ┆ ry  ┆ chr ┆ gic ┆ lar ┆ ula ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆ str ┆     ┆ f64 ┆     ┆     ┆ --- ┆ s   ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ str ┆ --- ┆     ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆ n   ┆ eri ┆ str ┆ l   ┆     ┆ on  ┆     ┆ boo ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nel │
│     ┆ --- ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ --- ┆ al  ┆ com ┆ r   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆     ┆ str ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ a   ┆     ┆     ┆     ┆ --- ┆     ┆ l   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- │
│     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆ pro ┆ pon ┆ fun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c…  ┆ …   ┆ ct… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ A0A ┆ A0A ┆ 674 ┆ Q9N ┆ rev ┆ Thr ┆ TRE ┆ 314 ┆ TRE ┆ UP0 ┆ act ┆ cyt ┆ 3'- ┆ cyt ┆ GO: ┆ 3.3 ┆ nul ┆ 3.3 ┆ IPR ┆ PTH ┆ nul ┆ nul ┆ SM0 ┆ NP_ ┆ Cas ┆ CAS ┆ Bac ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ nul ┆ DED ┆ 0.4 ┆ 0.8 ┆ 2.2 ┆ 1.7 ┆ 657 ┆ 142 ┆ 13  ┆ 227 ┆ 2   ┆ 167 ┆ 2.9 ┆ tru ┆ 180 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 80. ┆ 94. ┆ 0.0 ┆ 2.0 ┆ 0.0 ┆ 0.0 ┆ afd ┆ afd ┆ ok  ┆ tru ┆ 0.8 ┆ mod ┆     ┆ tru ┆ MKN ┆ MGS ┆ 25. ┆ 67  ┆ 43  ┆ 3   ┆ 67  ┆ 129 ┆ 130 ┆ 193 ┆ 0.7 ┆ 15. ┆ Aic │
│ 3E5 ┆ 7U2 ┆ 529 ┆ SU2 ┆ iew ┆ ee- ┆ X1  ┆     ┆ X1  ┆ 000 ┆ iva ┆ opl ┆ 5'  ┆ opl ┆ 000 ┆ 0.4 ┆ l   ┆ 0.4 ┆ 013 ┆ R13 ┆ l   ┆ l   ┆ 047 ┆ 009 ┆     ┆ _Cl ┆ ter ┆ _02 ┆ _02 ┆ _02 ┆     ┆     ┆ l   ┆ Dh_ ┆ 818 ┆ 028 ┆ 9   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 730 ┆ e   ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 23  ┆ 31  ┆ 000 ┆ 247 ┆ 000 ┆ 000 ┆ b_v ┆ b_v ┆     ┆ e   ┆ 991 ┆ el_ ┆     ┆ e   ┆ FAA ┆ QAL ┆ 373 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 8   ┆ ard │
│ G8Z ┆ YKB ┆     ┆     ┆ ed  ┆ pri ┆     ┆     ┆     ┆ 056 ┆ tio ┆ asm ┆ exo ┆ asm ┆ 028 ┆ 20. ┆     ┆ 20. ┆ 520 ┆ 058 ┆     ┆     ┆ 9;  ┆ 179 ┆     ┆ ass ┆ oid ┆ 009 ┆ 009 ┆ 009 ┆     ┆     ┆     ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆     ┆     ┆ 3.. ┆     ┆     ┆     ┆     ┆     ┆ 01  ┆ e-1 ┆ 01  ┆ 34  ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ IDF ┆ PPG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i-G │
│ 5   ┆ 2   ┆     ┆     ┆     ┆ me  ┆     ┆     ┆     ┆ 40: ┆ n   ┆ [GO ┆ nuc ┆ [GO ┆ 7;  ┆ 10: ┆     ┆ 10; ┆ ;IP ┆ ;PT ┆     ┆     ┆     ┆ .2  ┆     ┆ 2-S ┆ es  ┆ 150 ┆ 150 ┆ 150 ┆     ┆     ┆     ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 169 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ETA ┆ PMQ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ out │
│     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆ Chr ┆ of  ┆ :00 ┆ lea ┆ :00 ┆ GO: ┆ FF: ┆     ┆     ┆ R01 ┆ HR1 ┆     ┆     ┆     ┆ [Q9 ┆     ┆ ubt ┆ fae ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆     ┆ II_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NDK ┆ TLI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ier │
│     ┆     ┆     ┆     ┆     ┆ air ┆     ┆     ┆     ┆ omo ┆ imm ┆ 057 ┆ se  ┆ 057 ┆ 000 ┆ 000 ┆     ┆     ┆ 233 ┆ 305 ┆     ┆     ┆     ┆ NSU ┆     ┆ ype ┆ cis ┆ Z_C ┆ _NZ ┆ _NZ ┆     ┆     ┆     ┆ IV_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RTS ┆ FFD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  │
│     ┆     ┆     ┆     ┆     ┆ exo ┆     ┆     ┆     ┆ som ┆ une ┆ 37] ┆ act ┆ 37] ┆ 156 ┆ 046 ┆     ┆     ┆ 7;I ┆ 8:S ┆     ┆     ┆     ┆ 2-2 ┆     ┆ -II ┆     ┆ P08 ┆ _CP ┆ _CP ┆     ┆     ┆     ┆ V_V ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VCS ┆ MEA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Syn │
│     ┆     ┆     ┆     ┆     ┆ nuc ┆     ┆     ┆     ┆ e 3 ┆ res ┆ ;   ┆ ivi ┆ ;   ┆ 8;  ┆ ;   ┆     ┆     ┆ PR0 ┆ F27 ┆     ┆     ┆     ┆ ];N ┆     ┆ -C  ┆     ┆ 191 ┆ 081 ┆ 081 ┆     ┆     ┆     ┆ I_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Ex ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VGI ┆ TGL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dro │
│     ┆     ┆     ┆     ┆     ┆ lea ┆     ┆     ┆     ┆     ┆ pon ┆ cyt ┆ ty  ┆ cyt ┆ GO: ┆     ┆     ┆     ┆ 363 ┆ ;   ┆     ┆     ┆     ┆ P_3 ┆     ┆     ┆     ┆ 6_C ┆ 916 ┆ 916 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VIV ┆ PFS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me  │
│     ┆     ┆     ┆     ┆     ┆ se… ┆     ┆     ┆     ┆     ┆ se  ┆ oso ┆ [GO ┆ oso ┆ 000 ┆     ┆     ┆     ┆ 97; ┆     ┆     ┆     ┆     ┆ 385 ┆     ┆     ┆     ┆ AS_ ┆ _03 ┆ _04 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNG ┆ QPK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ A0A ┆ A0A ┆ 540 ┆ Q5T ┆ unr ┆ exo ┆ TRE ┆ 304 ┆ TRE ┆ nul ┆ DNA ┆ cyt ┆ DNA ┆ cyt ┆ GO: ┆ 3.3 ┆ nul ┆ 3.3 ┆ IPR ┆ PTH ┆ nul ┆ nul ┆ SM0 ┆ NP_ ┆ Cas ┆ CAS ┆ Pep ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ DOM ┆ DED ┆ 0.5 ┆ 0.8 ┆ 2.3 ┆ 1.4 ┆ 647 ┆ 152 ┆ 2   ┆ 223 ┆ 11  ┆ 177 ┆ 6.2 ┆ fal ┆ 178 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 78. ┆ 92. ┆ 4.1 ┆ 6.5 ┆ 4.1 ┆ 0.0 ┆ afd ┆ afd ┆ ok  ┆ fal ┆ 0.8 ┆ mod ┆     ┆ tru ┆ MKK ┆ MQT ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Aic │
│ 2X1 ┆ 316 ┆ 05  ┆ ZT0 ┆ evi ┆ deo ┆ X1  ┆     ┆ X1  ┆ l   ┆ rep ┆ oso ┆ bin ┆ oso ┆ 000 ┆ 0.4 ┆ l   ┆ 0.4 ┆ 013 ┆ R13 ┆ l   ┆ l   ┆ 047 ┆ 009 ┆     ┆ _Cl ┆ ton ┆ _01 ┆ _01 ┆ _01 ┆     ┆     ┆ AIN ┆ Dh_ ┆ 068 ┆ 3   ┆ 4   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 580 ┆ se  ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 7   ┆ 78  ┆ 532 ┆ 803 ┆ 532 ┆ 000 ┆ b_v ┆ b_v ┆     ┆ se  ┆ 99  ┆ el_ ┆     ┆ e   ┆ SID ┆ LIF ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ard │
│ XYZ ┆ L5U ┆     ┆     ┆ ewe ┆ xyr ┆ hCG ┆     ┆     ┆     ┆ air ┆ l   ┆ din ┆ l   ┆ 367 ┆ 20. ┆     ┆ 20. ┆ 520 ┆ 058 ┆     ┆     ┆ 9;  ┆ 179 ┆     ┆ ass ┆ iph ┆ 672 ┆ 672 ┆ 672 ┆     ┆     ┆ 3.. ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆     ┆     ┆ 12. ┆     ┆     ┆     ┆     ┆     ┆ e-7 ┆ e-1 ┆ e-7 ┆ 19  ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ KKE ┆ FDM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i-G │
│ 4   ┆ 4   ┆     ┆     ┆ d   ┆ ibo ┆ _19 ┆     ┆     ┆     ┆ [GO ┆ [GO ┆ g   ┆ [GO ┆ 7;  ┆ 10: ┆     ┆ 10; ┆ ;IP ┆ ;PT ┆     ┆     ┆     ┆ .2; ┆     ┆ 1-S ┆ ilu ┆ 648 ┆ 648 ┆ 648 ┆     ┆     ┆ 207 ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ .17 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IKK ┆ EAT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ out │
│     ┆     ┆     ┆     ┆     ┆ nuc ┆ 978 ┆     ┆     ┆     ┆ :00 ┆ :00 ┆ [GO ┆ :00 ┆ GO: ┆ FF: ┆     ┆     ┆ R01 ┆ HR1 ┆     ┆     ┆     ┆     ┆     ┆ ubt ┆ s   ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆ ;   ┆ II_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7;  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ YAV ┆ GLP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ier │
│     ┆     ┆     ┆     ┆     ┆ lea ┆ 49  ┆     ┆     ┆     ┆ 062 ┆ 058 ┆ :00 ┆ 058 ┆ 000 ┆ 000 ┆     ┆     ┆ 233 ┆ 305 ┆     ┆     ┆     ┆     ┆     ┆ ype ┆ har ┆ Z_C ┆ _NZ ┆ _NZ ┆     ┆     ┆ /no ┆ IV_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LDL ┆ FSQ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  │
│     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆ 81] ┆ 29] ┆ 036 ┆ 29] ┆ 563 ┆ 046 ┆     ┆     ┆ 7;I ┆ 8:S ┆     ┆     ┆     ┆     ┆     ┆ -I- ┆ ei  ┆ P06 ┆ _CP ┆ _CP ┆     ┆     ┆ te= ┆ V_V ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ te= ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ETD ┆ PKV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Syn │
│     ┆     ┆     ┆     ┆     ┆ III ┆     ┆     ┆     ┆     ┆     ┆ ;   ┆ 77] ┆ ;   ┆ 4;  ┆ ;   ┆     ┆     ┆ PR0 ┆ F27 ┆     ┆     ┆     ┆     ┆     ┆ E   ┆     ┆ 810 ┆ 068 ┆ 068 ┆     ┆     ┆ "Ex ┆ I_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Ex ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GLN ┆ TEL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dro │
│     ┆     ┆     ┆     ┆     ┆ (EC ┆     ┆     ┆     ┆     ┆     ┆ nuc ┆ ;   ┆ nuc ┆ GO: ┆     ┆     ┆     ┆ 363 ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_C ┆ 103 ┆ 103 ┆     ┆     ┆ onu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PFN ┆ CLL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me  │
│     ┆     ┆     ┆     ┆     ┆ 3…  ┆     ┆     ┆     ┆     ┆     ┆ leu ┆ dou ┆ leu ┆ 000 ┆     ┆     ┆     ┆ 97; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AS_ ┆ _00 ┆ _00 ┆     ┆     ┆ cle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cl… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DNI ┆ AVH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s … ┆ b…  ┆ s … ┆ …   ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ A0A ┆ A0A ┆ 540 ┆ Q6I ┆ unr ┆ exo ┆ TRE ┆ 304 ┆ TRE ┆ nul ┆ DNA ┆ nuc ┆ DNA ┆ nuc ┆ GO: ┆ 3.3 ┆ nul ┆ 3.3 ┆ IPR ┆ PTH ┆ nul ┆ nul ┆ SM0 ┆ nul ┆ Cas ┆ CAS ┆ Pep ┆ GCF ┆ GCF ┆ GCF ┆ 1   ┆ 202 ┆ DOM ┆ DED ┆ 0.5 ┆ 0.8 ┆ 2.3 ┆ 1.7 ┆ 674 ┆ 151 ┆ 2   ┆ 223 ┆ 11  ┆ 177 ┆ 6.2 ┆ fal ┆ 178 ┆ DOM ┆ fal ┆ 0   ┆ nul ┆ 78. ┆ 92. ┆ 4.1 ┆ 6.4 ┆ 4.1 ┆ 0.0 ┆ afd ┆ afd ┆ ok  ┆ fal ┆ 0.8 ┆ mod ┆     ┆ tru ┆ MKK ┆ MQT ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Aic │
│ 2X1 ┆ 316 ┆ 05  ┆ AN5 ┆ evi ┆ deo ┆ X1  ┆     ┆ X1  ┆ l   ┆ rep ┆ leu ┆ bin ┆ leu ┆ 000 ┆ 0.4 ┆ l   ┆ 0.4 ┆ 013 ┆ R13 ┆ l   ┆ l   ┆ 047 ┆ l   ┆     ┆ _Cl ┆ ton ┆ _01 ┆ _01 ┆ _01 ┆     ┆     ┆ AIN ┆ Dh_ ┆ 069 ┆ 303 ┆ 4   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 580 ┆ se  ┆     ┆ AIN ┆ se  ┆     ┆ l   ┆ 54  ┆ 78  ┆ 361 ┆ 992 ┆ 361 ┆ 000 ┆ b_v ┆ b_v ┆     ┆ se  ┆ 912 ┆ el_ ┆     ┆ e   ┆ SID ┆ LIF ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ard │
│ XYZ ┆ L5U ┆     ┆     ┆ ewe ┆ xyr ┆     ┆     ┆     ┆     ┆ air ┆ s   ┆ din ┆ s   ┆ 367 ┆ 20. ┆     ┆ 20. ┆ 520 ┆ 058 ┆     ┆     ┆ 9;  ┆     ┆     ┆ ass ┆ iph ┆ 672 ┆ 672 ┆ 672 ┆     ┆     ┆ 3.. ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆     ┆     ┆ 12. ┆     ┆     ┆     ┆     ┆     ┆ e-7 ┆ e-1 ┆ e-7 ┆ 19  ┆ 6   ┆ 6   ┆     ┆     ┆     ┆ v6  ┆     ┆     ┆ KKE ┆ FDM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i-G │
│ 4   ┆ 4   ┆     ┆     ┆ d   ┆ ibo ┆     ┆     ┆     ┆     ┆ [GO ┆ [GO ┆ g   ┆ [GO ┆ 7;  ┆ 10: ┆     ┆ 10; ┆ ;IP ┆ ;PT ┆     ┆     ┆     ┆     ┆     ┆ 1-S ┆ ilu ┆ 648 ┆ 648 ┆ 648 ┆     ┆     ┆ 207 ┆ I_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ .17 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IKK ┆ EAT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ out │
│     ┆     ┆     ┆     ┆     ┆ nuc ┆     ┆     ┆     ┆     ┆ :00 ┆ :00 ┆ [GO ┆ :00 ┆ GO: ┆ FF: ┆     ┆     ┆ R01 ┆ HR1 ┆     ┆     ┆     ┆     ┆     ┆ ubt ┆ s   ┆ 5_N ┆ 5.1 ┆ 5.1 ┆     ┆     ┆ ;   ┆ II_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7;  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ YAV ┆ GLP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ier │

In [26]:
# ============================================================
#       Target schema: wrangle cols
# ============================================================

# In accordance with `target_schema_cols`, a list of str ...
#   1. drop extraneous cols not in `target_schema_cols`
#   2. reorder cols in accordance with `target_schema_cols`

df_gene_list_cl = df_gene_list_ann.select(
    [col for col in target_schema_cols if col in df_gene_list_ann.columns]
)

df_gene_list_cl.write_csv(
    f"{OUT_DIR}/2026-10-15_for_c_marshal.tsv",
    separator="\t",
    include_header=True,
    null_value="NA"
)


df_gene_list_cl

shape: (1_848, 39)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ com ┆ def ┆ hum ┆ hum ┆ hum ┆ gri ┆ hum ┆ uni ┆ hum ┆ Gen ┆ Gen ┆ Ref ┆ def ┆ def ┆ def ┆ def ┆ def ┆ hum ┆ hum ┆ hum ┆ bac ┆ bac ┆ bac ┆ pym ┆ pym ┆ pld ┆ hum ┆ pld ┆ def ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla ┆ bla │
│ pos ┆ ens ┆ an_ ┆ an_ ┆ an_ ┆ id_ ┆ an_ ┆ pro ┆ an_ ┆ e   ┆ e   ┆ Seq ┆ ens ┆ ens ┆ ens ┆ ens ┆ ens ┆ an_ ┆ an_ ┆ an_ ┆ ter ┆ t_a ┆ t_a ┆ ol_ ┆ ol_ ┆ dt_ ┆ an_ ┆ dt_ ┆ ens ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp ┆ stp │
│ ite ┆ e_u ┆ uni ┆ gen ┆ gen ┆ gen ┆ gen ┆ t_r ┆ pro ┆ Ont ┆ Ont ┆ --- ┆ e_t ┆ e_s ┆ e_d ┆ e_g ┆ e_s ┆ len ┆ ali ┆ ali ┆ ial ┆ lig ┆ lig ┆ ali ┆ rms ┆ hum ┆ AA_ ┆ bac ┆ e_A ┆ _pi ┆ _le ┆ _mi ┆ _ga ┆ _qs ┆ _qe ┆ _ss ┆ _se ┆ _ev ┆ _bi │
│ _sc ┆ nip ┆ pro ┆ e_n ┆ e_n ┆ e   ┆ e_i ┆ ef_ ┆ tei ┆ olo ┆ olo ┆ str ┆ ype ┆ ubt ┆ upl ┆ ene ┆ pec ┆ gth ┆ gne ┆ gne ┆ _le ┆ ned ┆ ned ┆ gne ┆ d   ┆ an_ ┆ seq ┆ ter ┆ A_s ┆ den ┆ ngt ┆ sma ┆ pop ┆ tar ┆ nd  ┆ tar ┆ nd  ┆ alu ┆ tsc │
│ ore ┆ rot ┆ t_a ┆ ame ┆ ame ┆ --- ┆ n_I ┆ pro ┆ n_n ┆ gy  ┆ gy  ┆     ┆ --- ┆ ype ┆ ica ┆ _na ┆ ies ┆ _AA ┆ d_s ┆ d_e ┆ ngt ┆ _st ┆ _en ┆ d_r ┆ --- ┆ mea ┆ uen ┆ ia_ ┆ equ ┆ t   ┆ h   ┆ tch ┆ en  ┆ t   ┆ --- ┆ t   ┆ --- ┆ e   ┆ ore │
│ --- ┆ _ac ┆ c   ┆ _pr ┆ s   ┆ boo ┆ UIS ┆ teo ┆ ame ┆ (mo ┆ IDs ┆     ┆ str ┆ --- ┆ te_ ┆ me  ┆ --- ┆ s   ┆ tar ┆ nd  ┆ h   ┆ art ┆ d   ┆ esi ┆ f64 ┆ n   ┆ ce  ┆ mea ┆ enc ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ i64 ┆ --- ┆ i64 ┆ --- ┆ --- │
│ f64 ┆ --- ┆ --- ┆ ima ┆ --- ┆ l   ┆ --- ┆ me_ ┆ s   ┆ lec ┆ --- ┆     ┆     ┆ str ┆ cou ┆ --- ┆ str ┆ --- ┆ t   ┆ --- ┆ --- ┆ --- ┆ --- ┆ due ┆     ┆ --- ┆ --- ┆ n   ┆ e   ┆ f64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆ f64 ┆ f64 │
│     ┆ str ┆ str ┆ ry  ┆ str ┆     ┆ boo ┆ chr ┆ --- ┆ ula ┆ str ┆     ┆     ┆     ┆ nt  ┆ str ┆     ┆ i64 ┆ --- ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ s   ┆     ┆ f64 ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ --- ┆     ┆     ┆ l   ┆ --- ┆ str ┆ r   ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ fun ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ct… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.9 ┆ Q47 ┆ Q8I ┆ nul ┆ nul ┆ fal ┆ nul ┆ nul ┆ GTP ┆ GTP ┆ GO: ┆ NP_ ┆ Dpd ┆ Dpd ┆ 1   ┆ Dpd ┆ Col ┆ 177 ┆ 1   ┆ 176 ┆ 182 ┆ 6   ┆ 181 ┆ 175 ┆ 0.2 ┆ 95. ┆ AYS ┆ 97. ┆ MTI ┆ 56. ┆ 175 ┆ 77  ┆ 0   ┆ 7   ┆ 181 ┆ 2   ┆ 176 ┆ 7.3 ┆ 227 │
│ 962 ┆ ZY9 ┆ ZH9 ┆ l   ┆ l   ┆ se  ┆ l   ┆ l   ┆ cyc ┆ bin ┆ 000 ┆ 001 ┆     ┆     ┆     ┆ __F ┆ wel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 53  ┆ SIL ┆ 12  ┆ ENN ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆ .0  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ loh ┆ din ┆ 393 ┆ 019 ┆     ┆     ┆     ┆ olE ┆ lia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SSL ┆     ┆ YRE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-8 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ydr ┆ g   ┆ 4;  ┆ 195 ┆     ┆     ┆     ┆     ┆ psy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GEN ┆     ┆ ILA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆ [GO ┆ GO: ┆ .1; ┆     ┆     ┆     ┆     ┆ chr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PQR ┆     ┆ TIG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ :00 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆ ery ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ QGL ┆     ┆ EDI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 055 ┆ 552 ┆     ┆     ┆     ┆     ┆     ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LKT ┆     ┆ NRG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (EC ┆ 25] ┆ 5;  ┆     ┆     ┆     ┆     ┆     ┆ aea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PWR ┆     ┆ GLL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.5 ┆ ;   ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AAS ┆     ┆ DTP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .4… ┆ GTP ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AMQ ┆     ┆ KRA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.9 ┆ A0A ┆ Q5Q ┆ NFS ┆ NFS ┆ fal ┆ fal ┆ nul ┆ Cys ┆ cys ┆ GO: ┆ nul ┆ Dnd ┆ Dnd ┆ 1   ┆ Dnd ┆ Rho ┆ 397 ┆ 1   ┆ 376 ┆ 386 ┆ 9   ┆ 386 ┆ 367 ┆ 0.5 ┆ 94. ┆ MDV ┆ 95. ┆ MSD ┆ 44. ┆ 378 ┆ 208 ┆ 3   ┆ 9   ┆ 385 ┆ 1   ┆ 376 ┆ 5.3 ┆ 326 │
│ 863 ┆ 5B9 ┆ P19 ┆ 1   ┆ 1   ┆ se  ┆ se  ┆ l   ┆ tei ┆ tei ┆ 000 ┆ l   ┆     ┆ _AB ┆     ┆ __D ┆ dan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 52  ┆ QAT ┆ 11  ┆ GRP ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 700 ┆ .0  │
│     ┆ E1W ┆     ┆     ┆ hCG ┆     ┆     ┆     ┆ ne  ┆ ne  ┆ 565 ┆     ┆     ┆ CDE ┆     ┆ ndA ┆ oba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TPL ┆     ┆ IYL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-1 ┆     │
│     ┆ 6   ┆     ┆     ┆ _38 ┆     ┆     ┆     ┆ des ┆ des ┆ 4;  ┆     ┆     ┆     ┆     ┆     ┆ cte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DPR ┆     ┆ DHN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     │
│     ┆     ┆     ┆     ┆ 220 ┆     ┆     ┆     ┆ ulf ┆ ulf ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VLD ┆     ┆ ATT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ura ┆ ura ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆ gly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AML ┆     ┆ PLD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆ 582 ┆     ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PYL ┆     ┆ PTV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (EC ┆ act ┆ 9;  ┆     ┆     ┆     ┆     ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ INY ┆     ┆ FEA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.8 ┆ ivi ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ YGN ┆     ┆ MRP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .1… ┆ ty  ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PHS ┆     ┆ YFL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.9 ┆ Q47 ┆ Q8I ┆ nul ┆ nul ┆ fal ┆ nul ┆ nul ┆ GTP ┆ GTP ┆ GO: ┆ nul ┆ Dpd ┆ Dpd ┆ 1   ┆ Dpd ┆ Col ┆ 158 ┆ 1   ┆ 156 ┆ 182 ┆ 6   ┆ 164 ┆ 146 ┆ 0.3 ┆ 89. ┆ AYS ┆ 97. ┆ MTI ┆ 57. ┆ 134 ┆ 57  ┆ 0   ┆ 7   ┆ 140 ┆ 2   ┆ 135 ┆ 1.2 ┆ 180 │
│ 825 ┆ ZY9 ┆ ZH8 ┆ l   ┆ l   ┆ se  ┆ l   ┆ l   ┆ cyc ┆ bin ┆ 000 ┆ l   ┆     ┆     ┆     ┆ __F ┆ wel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 02  ┆ SIL ┆ 12  ┆ ENN ┆ 463 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 400 ┆ .0  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ loh ┆ din ┆ 393 ┆     ┆     ┆     ┆     ┆ olE ┆ lia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SSL ┆     ┆ YRE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-6 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ydr ┆ g   ┆ 4;  ┆     ┆     ┆     ┆     ┆     ┆ psy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GEN ┆     ┆ ILA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆ [GO ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆ chr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PQR ┆     ┆ TIG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ :00 ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆ ery ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ QGL ┆     ┆ EDI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 055 ┆ 552 ┆     ┆     ┆     ┆     ┆     ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LKT ┆     ┆ NRG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (EC ┆ 25] ┆ 5;  ┆     ┆     ┆     ┆     ┆     ┆ aea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PWR ┆     ┆ GLL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.5 ┆ ;   ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AAS ┆     ┆ DTP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .4… ┆ GTP ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AMQ ┆     ┆ KRA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.9 ┆ Q47 ┆ P30 ┆ GCH ┆ GCH ┆ fal ┆ fal ┆ UP0 ┆ GTP ┆ GTP ┆ GO: ┆ NP_ ┆ Dpd ┆ Dpd ┆ 1   ┆ Dpd ┆ Col ┆ 250 ┆ 70  ┆ 250 ┆ 182 ┆ 2   ┆ 182 ┆ 180 ┆ 0.3 ┆ 86. ┆ MEK ┆ 97. ┆ MTI ┆ 56. ┆ 175 ┆ 77  ┆ 0   ┆ 7   ┆ 181 ┆ 75  ┆ 249 ┆ 1.1 ┆ 227 │
│ 766 ┆ ZY9 ┆ 793 ┆ 1   ┆ 1   ┆ se  ┆ se  ┆ 000 ┆ cyc ┆ bin ┆ 000 ┆ 000 ┆     ┆     ┆     ┆ __F ┆ wel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 5   ┆ GPV ┆ 12  ┆ ENN ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 400 ┆ .0  │
│     ┆     ┆     ┆     ┆ DYT ┆     ┆     ┆ 056 ┆ loh ┆ din ┆ 392 ┆ 152 ┆     ┆     ┆     ┆ olE ┆ lia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RAP ┆     ┆ YRE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-8 ┆     │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆ 40: ┆ ydr ┆ g   ┆ 4;  ┆ .1  ┆     ┆     ┆     ┆     ┆ psy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AEK ┆     ┆ ILA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     │
│     ┆     ┆     ┆     ┆ GCH ┆     ┆     ┆ Chr ┆ ola ┆ [GO ┆ GO: ┆ [P3 ┆     ┆     ┆     ┆     ┆ chr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRG ┆     ┆ TIG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ omo ┆ se  ┆ :00 ┆ 000 ┆ 079 ┆     ┆     ┆     ┆     ┆ ery ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ARC ┆     ┆ EDI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ som ┆ 1   ┆ 055 ┆ 393 ┆ 3-1 ┆     ┆     ┆     ┆     ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SNG ┆     ┆ NRG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ (EC ┆ 25] ┆ 4;  ┆ ];N ┆     ┆     ┆     ┆     ┆ aea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FPE ┆     ┆ GLL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆ 3.5 ┆ ;   ┆ GO: ┆ P_0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RDP ┆     ┆ DTP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .4… ┆ GTP ┆ 000 ┆ 010 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRP ┆     ┆ KRA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.9 ┆ W5Y ┆ H0Y ┆ REX ┆ REX ┆ fal ┆ fal ┆ UP0 ┆ Oli ┆ 3'- ┆ GO: ┆ nul ┆ Cas ┆ CAS ┆ 1   ┆ DED ┆ Cor ┆ 188 ┆ 1   ┆ 169 ┆ 209 ┆ 19  ┆ 188 ┆ 168 ┆ 0.6 ┆ 91. ┆ MTG ┆ 94. ┆ MTE ┆ 47. ┆ 167 ┆ 87  ┆ 1   ┆ 19  ┆ 185 ┆ 1   ┆ 166 ┆ 3.5 ┆ 161 │
│ 729 ┆ 3L4 ┆ G54 ┆ O2  ┆ O2  ┆ se  ┆ se  ┆ 000 ┆ gor ┆ 5'- ┆ 000 ┆ l   ┆     ┆ _Cl ┆     ┆ Dh_ ┆ yne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 31  ┆ LDI ┆ 35  ┆ PVA ┆ 305 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆ .0  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 056 ┆ ibo ┆ RNA ┆ 017 ┆     ┆     ┆ ust ┆     ┆ I_I ┆ bac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EKD ┆     ┆ PKN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-5 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 40: ┆ nuc ┆ exo ┆ 5;  ┆     ┆     ┆ er  ┆     ┆ I_I ┆ ter ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ QII ┆     ┆ DRL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Chr ┆ lea ┆ nuc ┆ GO: ┆     ┆     ┆     ┆     ┆ II_ ┆ ium ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EMA ┆     ┆ VWI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ omo ┆ se, ┆ lea ┆ 000 ┆     ┆     ┆     ┆     ┆ IV_ ┆ vit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CLI ┆     ┆ DLE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ som ┆ mit ┆ se  ┆ 367 ┆     ┆     ┆     ┆     ┆ V_V ┆ aer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TDS ┆     ┆ MTG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ och ┆ act ┆ 6;  ┆     ┆     ┆     ┆     ┆ I_1 ┆ umi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DLN ┆     ┆ LDI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆ ond ┆ ivi ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆ nis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ILA ┆     ┆ HRH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ri… ┆ ty… ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EGP ┆     ┆ TIV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 0.8 ┆ A0A ┆ B7Z ┆ ATG ┆ ATG ┆ fal ┆ fal ┆ nul ┆ Aut ┆ ide ┆ GO: ┆ nul ┆ Sep ┆ Sep ┆ 1   ┆ Sep ┆ Cys ┆ 561 ┆ 265 ┆ 560 ┆ 759 ┆ 424 ┆ 716 ┆ 293 ┆ 1.8 ┆ 84. ┆ QRQ ┆ 53. ┆ MYV ┆ 24. ┆ 287 ┆ 199 ┆ 7   ┆ 422 ┆ 697 ┆ 264 ┆ 542 ┆ 8.6 ┆ 79. │
│ 501 ┆ 250 ┆ LM5 ┆ 16L ┆ 16L ┆ se  ┆ se  ┆ l   ┆ oph ┆ nti ┆ 000 ┆ l   ┆ tu  ┆ tu  ┆     ┆ tu_ ┆ tob ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 98  ┆ AFE ┆ 22  ┆ RSL ┆ 042 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 700 ┆ 7   │
│     ┆ IWT ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆ agy ┆ cal ┆ 042 ┆     ┆     ┆     ┆     ┆ _Pt ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EII ┆     ┆ TIQ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e-2 ┆     │
│     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ -re ┆ pro ┆ 1;  ┆     ┆     ┆     ┆     ┆ uA  ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LQY ┆     ┆ NLR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆ tei ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆ fus ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NKL ┆     ┆ SFE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ n   ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆ cus ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LEK ┆     ┆ SVE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ bin ┆ 576 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SDL ┆     ┆ LPL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tei ┆ din ┆ 5;  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HSV ┆     ┆ CHP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ g   ┆ GO: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LAQ ┆     ┆ GDG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16- ┆ [GO ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ KLQ ┆     ┆ APP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1…  ┆ :…  ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.8 ┆ L0D ┆ Q14 ┆ RBM ┆ RBM ┆ fal ┆ fal ┆ UP0 ┆ RNA ┆ RNA ┆ GO: ┆ NP_ ┆ Cas ┆ CAS ┆ 1   ┆ cas ┆ Sin ┆ 530 ┆ 150 ┆ 392 ┆ 209 ┆ 23  ┆ 202 ┆ 35  ┆ 2.0 ┆ 66. ┆ MAD ┆ 92. ┆ MPI ┆ 33. ┆ 15  ┆ 10  ┆ 0   ┆ 10  ┆ 24  ┆ 501 ┆ 515 ┆ 5.1 ┆ 14. │
│ 5   ┆ 6C1 ┆ 498 ┆ 39  ┆ 39  ┆ se  ┆ se  ┆ 000 ┆ -bi ┆ bin ┆ 000 ┆ 001 ┆     ┆ _Cl ┆     ┆ 6_I ┆ gul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 79  ┆ DID ┆ 92  ┆ IDL ┆ 333 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   │