### Get gene list from composite scoring results
### Julian Moran
### 2026-09-02

In [1]:
import boto3
import glob
import logging
import math
import os
import requests
import s3fs
import time

import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from dotenv import load_dotenv
from pathlib import Path

# Env
load_dotenv("../.env", override=True)
REPO_ROOT = os.environ["INSTALL_PATH"]
MINIO_KEY = os.environ["MINIO_KEY"]
MINIO_SECRET = os.environ["MINIO_SECRET"]

# Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(name)s:%(message)s"
)
logger = logging.getLogger(__name__)

In [10]:
# ============================================================
#       Args
# ============================================================

# Notebook variables
COMP_THRESHOLD = 0.65

# File intake
BUCKET = "iei-project"
PREFIX_GOLD = "03_gold/defense_finder/"
PREFIX_SILVER = "02_silver/defense_finder/"
FILE_FINAL_OUTPUT = "human_bacteria_structural_analogs_enriched.parquet"
FILE_IUIS_IEI = f"{REPO_ROOT}/data_sync/IUIS-IEI_geneList_cleaned.tsv"

# Dirs
OUT_DIR_PLOT = f"{REPO_ROOT}/vis/plots"

# Check live objects in MinIO silver
client = boto3.client(
    "s3",
    endpoint_url="http://eagle.tcag.ca:9000",
    aws_access_key_id=MINIO_SECRET,
    aws_secret_access_key=MINIO_KEY,
)
response = client.list_objects_v2(
    Bucket=BUCKET,
    Prefix=PREFIX_GOLD
)
live_objects = [
    obj["Key"]
    for obj in response.get("Contents", [])
]
live_objects

['03_gold/defense_finder/composite_score.parquet/_SUCCESS',
 '03_gold/defense_finder/composite_score.parquet/part-00000-ac5574c4-cf3c-48a9-98b6-077d4db394f9-c000.snappy.parquet',
 '03_gold/defense_finder/conserved_modules.parquet',
 '03_gold/defense_finder/defense_human_domain_annotated.parquet',
 '03_gold/defense_finder/defense_islands.manifest.json',
 '03_gold/defense_finder/defense_islands.parquet',
 '03_gold/defense_finder/final_output.parquet',
 '03_gold/defense_finder/final_output_spark.parquet/_SUCCESS',
 '03_gold/defense_finder/final_output_spark.parquet/part-00000-bb778272-db05-479f-a79a-2d18e89fe363-c000.snappy.parquet',
 '03_gold/defense_finder/griid_gene_subset.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_enriched.manifest.json',
 '03_gold/defense_finder/human_bacteria_structural_analogs_enriched.parquet',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.manifest.json',
 '03_gold/defense_finder/human_bacteria_structural_analogs_with_scores.parquet']

In [3]:
# ============================================================
#       In -- `df_comp_score`
# ============================================================

df_comp_score = pl.read_parquet(
    f"s3://{BUCKET}/{PREFIX_GOLD}{FILE_FINAL_OUTPUT}",
    storage_options={
        "aws_endpoint_url": "http://eagle.tcag.ca:9000",
        "aws_access_key_id": MINIO_SECRET,
        "aws_secret_access_key": MINIO_KEY,
    }
).drop([
    "Entry", 
    "Entry Name",
    "Organism",
    "Gene Names (ordered locus)",
    "Gene Names (ORF)",
    "Gene Names (synonym)"
]).rename({
    "Reviewed": "human_uniprot_reviewed",
    "cluster_repId": "defense_foldseek_repId",
    "human_entryId": "human_uniprot_ac",
    "Protein names": "human_protein_names",
    "Gene Names": "human_gene_names",
    "Length": "human_length_AAs",
    "Gene Names (primary)": "human_gene_name_primary",
    "Proteomes": "uniprot_ref_proteome_chr"
}).sort("composite_score", descending=True)

# `df_comp_score: count number of non-null gene names
col = "human_gene_name_primary"
n = df_comp_score.height
non_null = df_comp_score[col].is_not_null().sum()
p_w_gene_name = round(non_null / n, 2)

logger.info(f"Pipeline output with non-null gene names {p_w_gene_name}")

df_comp_score

INFO:__main__:Pipeline output with non-null gene names 0.67

shape: (1_097_291, 66)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ defense_f ┆ defense_t ┆ human_uni ┆ … ┆ immune_re ┆ composite ┆ alphafold ┆ run_date │
│ niprot_ac ┆ oldseek_r ┆ axId      ┆ prot_ac   ┆   ┆ levant    ┆ _score    ┆ _model_ve ┆ ---      │
│ ---       ┆ epId      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ rsion     ┆ str      │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ bool      ┆ f64       ┆ ---       ┆          │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH9    ┆ … ┆ false     ┆ 0.9962    ┆ model_v6  ┆          │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A0A5B9E1W ┆ A0A7C2NS9 ┆ 582702    ┆ Q5QP19    ┆ … ┆ false     ┆ 0.9863    ┆ model_v6  ┆          │
│ 6         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A0A1D7QWY ┆ A0A7C2NS9 ┆ 632773    ┆ Q5QP19    ┆ … ┆ false     ┆ 0.986     ┆ model_v6  ┆          │
│ 7         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A0A5B9QMN ┆ A0A7C2NS9 ┆ 980254    ┆ Q5QP19    ┆ … ┆ false     ┆ 0.9852    ┆ model_v6  ┆          │
│ 2         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q16C13    ┆ A0A7C2NS9 ┆ 375451    ┆ Q5QP19    ┆ … ┆ false     ┆ 0.9838    ┆ model_v6  ┆          │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ C3N4E9    ┆ A0A0N0A1H ┆ 427318    ┆ A0A024QZ4 ┆ … ┆ false     ┆ 0.1357    ┆ model_v6  ┆          │
│           ┆ 2         ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ Q97YA9    ┆ A0A0N0A1H ┆ 273057    ┆ A0A024QZ4 ┆ … ┆ false     ┆ 0.1351    ┆ model_v6  ┆          │
│           ┆ 2         ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A024R2W ┆ … ┆ false     ┆ 0.1338    ┆ model_v6  ┆          │
│ 5         ┆ 2         ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ A0A157T2K ┆ A0A0N0A1H ┆ 2287      ┆ A0A024QZ4 ┆ … ┆ false     ┆ 0.1337    ┆ model_v6  ┆          │
│ 1         ┆ 2         ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A087X02 ┆ … ┆ false     ┆ 0.1311    ┆ model_v6  ┆          │
│ 5         ┆ 2         ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# ============================================================
#       In -- IUIS-IEI
# ============================================================

df_iuis_iei = pl.read_csv(
    FILE_IUIS_IEI,
    separator="\t",
    has_header=True,
    null_values="NA",
    infer_schema_length=None,
)

df_iuis_iei

shape: (591, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Major     ┆ Subcatego ┆ Disease   ┆ Genetic   ┆ … ┆ median_pr ┆ max_prob  ┆ q1_prob   ┆ q3_prob  │
│ category  ┆ ry        ┆ ---       ┆ defect    ┆   ┆ ob        ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│ str       ┆ str       ┆           ┆ str       ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1. CID    ┆ 1. T-B+   ┆ CD3z defi ┆ CD247     ┆ … ┆ 2.6799e-7 ┆ 5.1799e-7 ┆ 1.4299e-7 ┆ 3.9299e- │
│           ┆ SCID      ┆ ciency    ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 1. CID    ┆ 1. T-B+   ┆ CD3d defi ┆ CD3D      ┆ … ┆ 2.0976e-8 ┆ 1.0403e-7 ┆ 2.0966e-8 ┆ 6.2503e- │
│           ┆ SCID      ┆ ciency    ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 1. CID    ┆ 1. T-B+   ┆ CD3e defi ┆ CD3E      ┆ … ┆ 1.2023e-7 ┆ 9.5964e-7 ┆ 1.2020e-7 ┆ 5.3993e- │
│           ┆ SCID      ┆ ciency    ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 1. CID    ┆ 1. T-B+   ┆ Coronin-1 ┆ CORO1A    ┆ … ┆ 6.8292e-8 ┆ 6.8292e-8 ┆ 6.8292e-8 ┆ 6.8292e- │
│           ┆ SCID      ┆ A deficie ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆           ┆ ncy       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1. CID    ┆ 1. T-B+   ┆ gc defici ┆ IL2RG     ┆ … ┆ 4.0313e-8 ┆ 1.6147e-7 ┆ 4.0313e-8 ┆ 1.0089e- │
│           ┆ SCID      ┆ ency      ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆           ┆ (common   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ gamma ch… ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 9. BMF    ┆ null      ┆ BMFS5     ┆ TP53      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 9. BMF    ┆ null      ┆ Fanconi   ┆ UBE2T     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ Anemia    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Type T    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9. BMF    ┆ null      ┆ DKCB3     ┆ WRAP53    ┆ … ┆ 0.00001   ┆ 0.00001   ┆ 0.00001   ┆ 0.00001  │
│ 9. BMF    ┆ null      ┆ Fanconi   ┆ XRCC2     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ Anemia    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Type U    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9. BMF    ┆ null      ┆ Fanconi   ┆ XRCC9     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ Anemia    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Type G    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# ============================================================
#       Pare down, clean up `df_comp_score`
# ============================================================

# Pare down to ...
#   - only highest-composite-score pair for each unique human UniProt accession

df_comp_unq_hs_proteins = df_comp_score.unique(
    subset=["human_uniprot_ac"],
    keep="first",
    maintain_order=True
)

# Count number of unique human gene names in this dataset
df_comp_unq_hs_genes = df_comp_score.unique(subset=["human_gene_name_primary"], keep="first", maintain_order=True)
logger.info(f"Number of unique genes in this dataset: {len(df_comp_unq_hs_genes):,}")
df_comp_unq_hs_proteins

INFO:__main__:Number of unique genes in this dataset: 3,748

shape: (15_572, 66)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ defense_u ┆ defense_f ┆ defense_t ┆ human_uni ┆ … ┆ immune_re ┆ composite ┆ alphafold ┆ run_date │
│ niprot_ac ┆ oldseek_r ┆ axId      ┆ prot_ac   ┆   ┆ levant    ┆ _score    ┆ _model_ve ┆ ---      │
│ ---       ┆ epId      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ rsion     ┆ str      │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ bool      ┆ f64       ┆ ---       ┆          │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH9    ┆ … ┆ false     ┆ 0.9962    ┆ model_v6  ┆          │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A0A5B9E1W ┆ A0A7C2NS9 ┆ 582702    ┆ Q5QP19    ┆ … ┆ false     ┆ 0.9863    ┆ model_v6  ┆          │
│ 6         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH8    ┆ … ┆ false     ┆ 0.9825    ┆ model_v6  ┆          │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ P30793    ┆ … ┆ false     ┆ 0.9766    ┆ model_v6  ┆          │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ W5Y3L4    ┆ A0A6P6EXW ┆ 1224164   ┆ H0YG54    ┆ … ┆ false     ┆ 0.9729    ┆ model_v6  ┆          │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ B2JBD0    ┆ A0A2T2SPB ┆ 63737     ┆ A0A024R1T ┆ … ┆ false     ┆ 0.1398    ┆ model_v6  ┆          │
│           ┆ 3         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ A0A372FQI ┆ A0A0F3NF6 ┆ 2294034   ┆ A0A024R64 ┆ … ┆ false     ┆ 0.1394    ┆ model_v6  ┆          │
│ 4         ┆ 8         ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A024RAZ ┆ … ┆ false     ┆ 0.1391    ┆ model_v6  ┆          │
│ 5         ┆ 2         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ C9J8J7    ┆ … ┆ false     ┆ 0.1378    ┆ model_v6  ┆          │
│ 5         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A024R2W ┆ … ┆ false     ┆ 0.1338    ┆ model_v6  ┆          │
│ 5         ┆ 2         ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# ============================================================
#       Annotate by IUIS-IEI membership
# ============================================================

iuis_iei_genes = df_iuis_iei["Genetic defect"]
df_comp_ann = df_comp_unq_hs_proteins.with_columns(
    pl.col("human_gene_name_primary")
    .is_in(iuis_iei_genes.implode())
    .alias("human_gene_in_IUIS")
)

# Measure how many rows have a valid IUIS-IEI annotation
n_rows_w_iuis = df_comp_ann["human_gene_in_IUIS"].sum()
logger.info(f"n rows with IUIS-IEI membership: {n_rows_w_iuis}")
p_rows_w_iuis = round((df_comp_ann["human_gene_in_IUIS"].sum() / len(df_comp_ann)), 4)
logger.info(f"p rows with IUIS-IEI membership: {p_rows_w_iuis}")

df_comp_ann

INFO:__main__:n rows with IUIS-IEI membership: 387
INFO:__main__:p rows with IUIS-IEI membership: 0.0249

shape: (15_572, 67)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ defense_u ┆ defense_f ┆ defense_t ┆ human_uni ┆ … ┆ composite ┆ alphafold ┆ run_date ┆ human_gen │
│ niprot_ac ┆ oldseek_r ┆ axId      ┆ prot_ac   ┆   ┆ _score    ┆ _model_ve ┆ ---      ┆ e_in_IUIS │
│ ---       ┆ epId      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ rsion     ┆ str      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ f64       ┆ ---       ┆          ┆ bool      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆ str       ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH9    ┆ … ┆ 0.9962    ┆ model_v6  ┆          ┆ null      │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ A0A5B9E1W ┆ A0A7C2NS9 ┆ 582702    ┆ Q5QP19    ┆ … ┆ 0.9863    ┆ model_v6  ┆          ┆ false     │
│ 6         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ Q8IZH8    ┆ … ┆ 0.9825    ┆ model_v6  ┆          ┆ null      │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ Q47ZY9    ┆ A0A2E5CU0 ┆ 167879    ┆ P30793    ┆ … ┆ 0.9766    ┆ model_v6  ┆          ┆ false     │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ W5Y3L4    ┆ A0A6P6EXW ┆ 1224164   ┆ H0YG54    ┆ … ┆ 0.9729    ┆ model_v6  ┆          ┆ false     │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ B2JBD0    ┆ A0A2T2SPB ┆ 63737     ┆ A0A024R1T ┆ … ┆ 0.1398    ┆ model_v6  ┆          ┆ null      │
│           ┆ 3         ┆           ┆ 9         ┆   ┆           ┆           ┆          ┆           │
│ A0A372FQI ┆ A0A0F3NF6 ┆ 2294034   ┆ A0A024R64 ┆ … ┆ 0.1394    ┆ model_v6  ┆          ┆ null      │
│ 4         ┆ 8         ┆           ┆ 3         ┆   ┆           ┆           ┆          ┆           │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A024RAZ ┆ … ┆ 0.1391    ┆ model_v6  ┆          ┆ null      │
│ 5         ┆ 2         ┆           ┆ 1         ┆   ┆           ┆           ┆          ┆           │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ C9J8J7    ┆ … ┆ 0.1378    ┆ model_v6  ┆          ┆ null      │
│ 5         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ A0A0F7P5S ┆ A0A0G0LG6 ┆ 1604004   ┆ A0A024R2W ┆ … ┆ 0.1338    ┆ model_v6  ┆          ┆ null      │
│ 5         ┆ 2         ┆           ┆ 4         ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [18]:
n = df_comp_ann["human_gene_in_IUIS"].sum()
n

387